### ISSUE TITLE
Staff or admin cannot add self as admin of pages, but can add others

### ISSUE THREAD

**Issue by DonnaScriptTechs** [PHPfox-Official/phpfox-v4-feature-requests#100]
_From @lueung on March 24, 2016 3:8_

Staff or admin cannot add self as admin of pages while in the pages admincp, but can add anyone else.

_Copied from original issue: moxi9/phpfox#1247_

**Comment by Data66PF** [comment]
Well, this was designed to add friends as admin to the page. It was not designed to add self to page so really, it is working as designed. I'll move this to feature requests as we should have this ability to add ourselves as admin to a page/group.
