### ISSUE TITLE
Event - notification to be sent to all attendees when a change to the event is made

### ISSUE THREAD

**Issue by 0Paul-Zhu0** [PHPfox-Official/phpfox-v4-feature-requests#1006]
Hi, 

Would it be possible to introduce a notification when the host of an event changes the event details such as the time of the event, to all attendees?

Currently changes to events are not notified to attendees and they may end up missing the event if the time is changed.

Thank you,

**Comment by harrison05** [comment]
Implemented in Events 4.8.0

Regards
