### ISSUE TITLE
Main Search box is awesome...but the results can be confusing.

### ISSUE THREAD

**Issue by PhpFoxJohnJr** [PHPfox-Official/phpfox-v4-feature-requests#104]
Would be nice on the search/results page had a filter drop down box.  This should be very simple...

Filter by:  
Member
Photo
Pages
Blog
etc.

Depending on what module you have active :)

**Comment by Data66PF** [comment]
If you mean and advanced search, this would be better by a third party but we might look at it in a future release perhaps. It depends on how big it could be and how involved. I'll ask one of our core developers once we release 4.4 so he has time to see.

**Comment by PhpFoxJohnJr** [comment]
Data, I do understand that you are not a serious coder...neither am I anymore.  But you would add a simple drop down box and write 5-6 SQL/mySQL statements that should take less than an hour .  The way it is set up now you are query several tables and bringing back all the records sorting by who knows.  You said this next upgrade was security and speed.  Well querying a few table compared to a dozen would save you lots of CPU time and Ram storing that info on that one process.  Security...well although I like it the way it is set up I would guess some may think it is odd that I can go to the PAGES menu and do a search on the PAGES section and only the only PAGES that come up is the ones you are friend with...which make sense...but I can go to the Main menu on the home page and type the same word and see everything...pages, photos, blogs...etc.  So setting permission or allowing us to choose which records are available for search would help us control security.  I know...not the security you were thinking :)  Just hate me a little...it's ok :)

**Comment by Data66PF** [comment]
You are a member of my site. On my site I remove the main search and only allow searching via individual modules for security.  As for this request, we will look at it once we get these optimizations done and security fixes. It is possible this is already going to be looked at since we are looking at everything for it. I can't say for sure. I do make add ons and I am serious about my coding btw.

**Comment by PhpFoxJohnJr** [comment]
"You are a member of my site. On my site I remove the main search and only allow searching via individual modules for security."  Yes I know and it is annoying...sorry.  When I look for something it should be as easy as falling down...why?  Because the easier it is the lest hits on my server.  So say I am looking to solve a problem.  I should be able...
1. Hit the login button.  The cursor in my program would automatically goes to the email text box and then I would enter requirements and hit enter.
2. enter search text in search box.
4. Click on the drop down box to narrow my search.  Whether it has it's own table to set up privacy settings well that is something else.  In no settings than list the static area...photo, pages..etc in the drop down box.
4. Be able to click the search button...I mean icon (being able to click the button instead of making sure my cursor is in the text box and then clicking enter - another issue that needs to be solved).  Now my query on the server is two tables instead of a dozen tables.


The way it is set up now for your site.
1. Hit the login button.
2. Place my cursor manually in the email text.  Enter the requirement and hit enter.
3.  Click on forum Menu button...hit on server pulling back info to screen.
4.  Click on Search drop down box to show entry box.
5.  Put cursor into entry box.
6.  Time in search text.
7.  click off of show threads  and click show post because 99% of answers are not in the heading.
8.  click on Go button

**Comment by Data66PF** [comment]
For my ScriptTechs, the search won't be changing as the default global search allows for scraping and I won't have my member data scraped like that. 

For this feature request, as I said I would ask once we will be working on that if there are not already optimizations done on the search. If it seems too big a feature, this will need to move to the community forum where the bigger features are as this one is only for small improvements.

**Comment by IsabellaJolie** [comment]
Hi JohnJr,
This feature is already supported by phpFox from the first version of phpfox 4. You can see detail at https://v4.phpfox.com/search/?q=test&view=PHPfox_Videos&encode=1&history=groups,PHPfox_Videos,user,music,blog
Sorry for making you confuse about our answers.

**Comment by PhpFoxJohnJr** [comment]
IsabellaJollie,

At the time this was open it was not right...don't remember the results like it is now and data would have caught it as soon as I started complaining :) but here are my review of what you missed in the conversation listed above.

Good things:  
-Main search button is a button :)
-Main search has categories after total search...still a lot of queries but ok.
able to break down search within categories and see results.

Bad things (missed improvements)
-Everytime someone clicks the button to login or maybe also registration the focus of the cursor is not automatically put into the first name field.  I am pretty sure you learn that in the first week of coding and it is only one line of code and it is good coding.
-The forum search (which we were discussing above on Data site) still has the image of a button.  So it was fixed on the front page but maybe not though out the entire software...all search buttons need to be real buttons and the code can be reused on each.
-If you did a poll you would see a lot more than 50% of people search the forum by post compared to the current default of show threads because most thread titles are not great and you want to see the complete results anyways.  So which ever is used more (I think show post) is the one that should be the default first.

Any of course the worst is the search itself as it is from the 90's and I know as I was coding a lot in the 90's.  We need the ability to search exact, all words, any words...etc.

Don't take this as complaining as I am only trying to improve your product so you can sell more and make more money :)

**Comment by IsabellaJolie** [comment]
JohnJr,
It's so great to hear all your valued feedback. All of them will be added to 4.6.0. 
Best regards.

**Comment by IsabellaJolie** [comment]
Hi JohnJr,
Regarding the feature "Any of course the worst is the search itself as it is from the 90's and I know as I was coding a lot in the 90's. We need the ability to search exact, all words, any words...etc.", our team has already checked and saw that the change in current search might affect to our plan for 4.6.0 so much. So we will put it in low priority in 4.6.0 and may move this feature to 4.7.0 to check the solution later. Sorry for this inconvenience.
