### ISSUE TITLE
Timeline photo album

### ISSUE THREAD

**Issue by Ylmzef** [PHPfox-Official/phpfox-v4-feature-requests#110]
Please add album for added photos from feed.
So the system can collect photos uploaded from feed.
It can be more useful for users.

**Comment by Data66PF** [comment]
http://scripttechs.com/article/338/have-your-status-shared-photos-grouped-into-an-album/ this free plugin from Webwolf might help you for now if you ask him if it works in v4.

**Comment by jhayden2000** [comment]
God knows we need this.. im not sure why this hasnt been done yet.
