### ISSUE TITLE
Supporting Gif's in E-gifts

### ISSUE THREAD

**Issue by Lukey199223** [PHPfox-Official/phpfox-v4-feature-requests#123]
Hello :) I Hope I've moved this to the right place aha

But on E-gifts, when adding an E-gift, it'd be awesome if we had the option to support Gif files :) aswell as png and jpg :)

**Comment by Data66PF** [comment]
You want to show the animation, is that correct?

**Comment by Lukey199223** [comment]
Ye :)that's correct :) , I used a gif image as an e-gift and obviously its showing the image as a normal image not animated aha :)

**Comment by Lukey199223** [comment]
I think this would be more of an "Enhancement" than a feature request

**Comment by Data66PF** [comment]
Enhancements are feature requests.

**Comment by Lukey199223** [comment]
Ah right :) , sorry it took me ages to reply, been quite busy aha

**Comment by Lukey199223** [comment]
thanks by the way :)

**Comment by neil96** [comment]
Hi @Lukey199223 ,
Gif files are already supported, could you double check again.

Regards.
