### ISSUE TITLE
Points: Need to be able to create package or manage the amount of points that can be purchased

### ISSUE THREAD

**Issue by darksolar1** [PHPfox-Official/phpfox-v4-feature-requests#125]
Currently, there's no way to create a package or manage the amount of points that can be purchased. This would add fill some seriously lacking improvements.

**Comment by erick260** [comment]
Yes, i agree with you there.

**Comment by dawn2323** [comment]
Yes Needed!

**Comment by harrison05** [comment]
Implemented in the new Activity Points App.
