### ISSUE TITLE
Separate payment methods for Gifts and Points

### ISSUE THREAD

**Issue by darksolar1** [PHPfox-Official/phpfox-v4-feature-requests#126]
For example, I want to allow people to purchase points with paypal and only only allow egift to be purchased with points. The problem is if I disable the payment gateway, they will no longer will be able to purchase points.

The point system is not very user friendly at all and could definitely use some improvements for ease of accessibility and features.

**Comment by vizruta** [comment]
exactly i agree on darksolar1......point system should be improved for betterment and ease of usage for example in my website i want users to purchase products in marketplace with the points they have earned in the website with their activity hence no money is involved over here and only points are used but the site prompts using payment gateway which i dont require in my site....hence there should be an improvement made towards the point system ...the script should show uniqueness or else it will be ''just another social networking script in the block'' .

**Comment by Spaninet** [comment]
I like this feature.

**Comment by neil96** [comment]
Hi @darksolar1  ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
