### ISSUE TITLE
Reply to comments 

### ISSUE THREAD

**Issue by Lukey199223** [PHPfox-Official/phpfox-v4-feature-requests#131]
Hello :) 

If we had a "Reply to comments" like facebook has, that'd be awesome :)

**Comment by Data66PF** [comment]
This feature request seems to be to bring back our Comment settings, specifically, the Threaded Comments (which would require us to also include the Nested Comment setting for how many to show).

**Comment by Lukey199223** [comment]
Thank you :) , I just think this feature would help us keep up with other social networks :)

**Comment by SalmanKhan86** [comment]
how can i get reply option in comment box.i have fresh install 4.5.2 latest.i can't find this option.
