### ISSUE TITLE
ADD button to the right of DELETE in manage states / provinces will be so much more productive 

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-feature-requests#132]
Hi when managing states / provinces in settings >> countries>> managing
it only allows you to add one and then you have to go to step 1 again
can we create an ADD button to the right of DELETE in manage states / provinces will be so much more productive and we can just keep adding :) PLEASE

found the right place on github :)
![add-more-from-manage-page-not-from-settings-countries add-easier](https://cloud.githubusercontent.com/assets/17736688/14932745/5c692402-0e41-11e6-8796-764682255b6a.JPG)

**Comment by spirogg** [comment]
Possible for version 4.40 RC 1 ?? Thanks.

**Comment by neil96** [comment]
Dear @spirogg ,

This feature is now available on phpFox 4.6.0.

Regards.
