### ISSUE TITLE
Add word/text wrap for editing Pages 

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-feature-requests#133]
windows 10 pro, firefox browser latest version of phpfox as of today..

add word/text wrap for editing Pages - like Privacy page - Terms Page etc please

thanks

Spiro 

see photo
![privacy-and-terms-all-pages-add-word-wrap-please](https://cloud.githubusercontent.com/assets/17736688/14933948/fb6f97e2-0e65-11e6-8c9c-304224e452bd.JPG)

**Comment by Data66PF** [comment]
Please see our instructions for submitting feature requests. This is not conforming to the instructions as it has more than one requested thing in it. Please edit to include one thing and please put the other thing you want in a different request. Note that we will not be adding editors though as that would be best for third parties.
