### ISSUE TITLE
Unlimited user names

### ISSUE THREAD

**Issue by Lukey199223** [PHPfox-Official/phpfox-v4-feature-requests#134]
Hello :) 

it'd be awesome if phpfox had the option to have unlimited user name changes :)

**Comment by Data66PF** [comment]
Please read our instructions for submitting feature requests and please fix your request. It is not detailed and has more than one thing.

**Comment by Lukey199223** [comment]
My Apologies Donna, Its done :)

**Comment by Data66PF** [comment]
I'm not sure about this request. When you go to User Group Settings and change the number of allowed username changes in the User settings, let's say to 9999, does it not work?

**Comment by Lukey199223** [comment]
That does work yes :) , but I mean, some members wont want to see 1 of 500 username changes, if you get me ? :) , So if we can put "0" without the quotes for unlimited like  other options in admin cp, its only a small feature, but it'd be nice :)

**Comment by neil96** [comment]
Dear @Lukey199223 ,

This feature is now available on phpFox 4.6.0.

Regards.
