### ISSUE TITLE
Add full closed group capability to admin new group configuration

### ISSUE THREAD

**Issue by Gatsby-PF** [PHPfox-Official/phpfox-v4-feature-requests#142]
While phpFox allows group modes as a means of adding or removing privileges to users, it cannot be used to create closed groups as a 100% segregated community (SC) within the larger network wherein each SC has its own subset of all services inaccessible to any other non member of that community (closed nation within a nation concept).

Here is a scenario:

Two corporations that are arch rivals each desire to buy their own private closed community groups  on the same phpFox network.  Both have competing products, both have an interest in knowing what each the other is up to, and both seek to gain knowledge of, and access to each others best human resources for purposes of pirating them.  

Both likewise have an interest in preventing the other company from having the ability to accessing their communities content, communication, and access to either the existence or identities of their members. 

Content and communication within each group are intended for internal employees "eyes only", unavailable to the community public at large.

Each can only access and friend users in their group.  

Each will have a public relations asset running a public page for their company in the networks main public area that has no pathway for the public to their closed group, and public users within the main network at large or in any other group should not so much as have the ability to discover the existence of these groups, have the ability to discover or identify their members, or access them via messaging or any other app.  It would be as they never exited. Members in each closed group should only see and friend members in that group, access only their forums, their blogs, their anything.

This level of closed group operation is not possible in the current phpFox. It should be as it opens up and entirely new monetization opportunity for admins, and thus another reason to buy the script. It is way too broad of a task for an app as it will likely involve core changes, which is why it was proposed here.

The change:
When creating a new user group in admincp, addition of a new control "Is a closed group"   Yes   No, selected as YES would instruct the system to create a closed partition for the group across all services, which would allow a closed subset of all modules and their associated content and communication to be restricted to users that group only.  Any users invited from that groups designated inviter, register to that group by default. 

If the proposed control is not enabled (selected NO), the group defaults to its currently existing mode of operation... as a means of adding or removing public user privilege.

**Comment by Data66PF** [comment]
This is actually something in the longer plans. Something similar. I'll leave this at Interested for now.

**Comment by Gatsby-PF** [comment]
This capability would also mesh nicely with compartmenaltization for language pack enclaves where groups can be set up for each language for which a language pack is installed. Users selecting their language/flag on registration would be auto-enrolled into the group created for their own language where they can communicate among like speaking people.  This would avoid users the inconvenience of tolerating multilingual garbage they do not and care not to understand among their own threads, forums, blog catalogs, albums catalogs etc.

**Comment by spirogg** [comment]
I agree. Very nice idea and well purposes. Hope PF owner creates this.

**Comment by IsabellaJolie** [comment]
Hi Gatsby-PF and all,
Since this feature is very special, it should be implemented by 3rd devs
