### ISSUE TITLE
Option to choose what info displays in the profile photo info section 

### ISSUE THREAD

**Issue by Lukey199223** [PHPfox-Official/phpfox-v4-feature-requests#143]
Hello :) 

It'd be awesome to see Phpfox add an option for the admin to choose what info gets displayed by the side of the profile picture (on the cover photo) 

right now for example I have 

Luke Jones
Lives in Aberdare, United Kingdom · Born on October 3, 1992    · Male

and I tested, I put myself in a relationship just to test, and "in a Relationship" shows up too, so if we had the option to choose what info to show in that area, it'd be awesome :) 

I hope this was more clear than my Last requests have been :)

**Comment by SalmanKhan86** [comment]
https://github.com/moxi9/phpfox-feature-requests/labels/Interest
