### ISSUE TITLE
video count flexibilty

### ISSUE THREAD

**Issue by queenmother305** [PHPfox-Official/phpfox-v4-feature-requests#148]
add the option in the video app for admin to select whether they want video views to be counted per unique ip address or per each actual hit. this is something that has been in the forums of every single version of fox. videos with low view count numbers make newer sites look inactive and less appealing to join.

**Comment by Data66PF** [comment]
So to be clear, we want a setting to show counts regardless of the IP. How do we treat the person that refreshes the page just to get their count up? This is why it was done by unique IP due to client complaints when they were running video contests and such. It caused many issues.

**Comment by queenmother305** [comment]
I think that should be up to the admin whether or not they want the option to allow or disallow by ip or by actual page refresh. someone refreshing the page just to get to their view count up is a problem for big well known sites. but what about the smaller lesser known sites? it is important to cater to their needs as well. communities are similar to nightclubs, they have to be popular to take off. when someone starts a new fox site, it is important to give the illusion of popularity to encourage growth. there are many threads posted regarding people seeking the hook/plugin info to adjust view counts. definitely enough discussion where I think this topic deserves to be transformed into a feature to assist in the growth of smaller fox communities. if they don't get their sites off the ground it dies and they are no longer a fox customer. but with tools that assist in giving their site the appearance of being popular, thus more desirable they will grow and be fox customers for life. it will become their primary income as my sites have become to me. 

in my opinion faking view counts is no different than the current apps that allow us to add stock users to make the site look more full. a party isn't a party if you are the only one in an empty room. people want to be where everybody is at. thanks for the consideration donna.

**Comment by spirogg** [comment]
I second this vote.

**Comment by SalmanKhan86** [comment]
good

**Comment by neil96** [comment]
Hi @queenmother305 ,

This feature is now available on phpFox Video 4.6.0.

Regards.
