### ISSUE TITLE
Events, Forum discussion, RSS feeds for page/groups should be configurable

### ISSUE THREAD

**Issue by srikumar101** [PHPfox-Official/phpfox-v4-feature-requests#160]
Dear team, 

In the recent release of V. 4.3 events, forum discussion, RSS feeds started appearing in pages and/or groups. While we can control displaying or hiding these modules on main menu, it is not configurable to show or hide it on pages/groups. Please approve this request and provide us an option to configure these modules for pages/groups from admincp.

**Comment by Data66PF** [comment]
Please see our feature request submittal instructions. This is a bit vague and the title is confusing. 

Do you mean you want an option to set what menus show in Pages module or in Groups app? These are two different things completely. If you want it for both, you need a new request for the Groups app as that can't be in this request.

**Comment by srikumar101** [comment]
Yes.. I meant to say that there should be an option to set what menus should show up on Pages and Groups app. I will create another request for Groups app.

**Comment by SalmanKhan86** [comment]
nice feature
