### ISSUE TITLE
Set an existing photo as cover photo 

### ISSUE THREAD

**Issue by Lukey199223** [PHPfox-Official/phpfox-v4-feature-requests#163]
Hello :) 

It'd be awesome if we could set an existing photo as cover photo instead of needing to duplicate the picture you want by uploading it just so its on your profile and uploading it as your cover photo :)

**Comment by Data66PF** [comment]
We used to have this feature but it caused issues. I don't know if we can bring it back.

**Comment by akvaskov** [comment]
It would be great to have the siimilar possibility for posting statuses and comments. Should it be a separete feather request? Or will you consider that within this ticket?

**Comment by SalmanKhan86** [comment]
in which version this feature is implemented. pls apply it soon
