### ISSUE TITLE
Upload Multiple photo's on status 

### ISSUE THREAD

**Issue by Lukey199223** [PHPfox-Official/phpfox-v4-feature-requests#164]
Hello  :) 

Neil told me this was an Enhancement and it should be posted here :) 

but when your uploading a photo from the photo's page, you can select multiple photo's at once, but when your uploading a photo from the status , you can only select one 

it'd be awesome if we could select multiple from status upload aswel :)

**Comment by Data66PF** [comment]
A status post is a comment on the site. It is not content on the site. This feature seems ill advised since you would be making a comment with too much in it.

**Comment by jhayden2000** [comment]
im with Lukey. This feature on facebook makes life quite easy. i would like to see it in PHpfox also.

**Comment by SalmanKhan86** [comment]
yes this feature is required.

**Comment by Lukey199223** [comment]
I definitely need this feature for my Social network and by the looks of things, so do loads of others aha, I'm glad to see phpfox are interested in this feature :) 

thank you Raymond for tagging it :)

**Comment by akvaskov** [comment]
That's really strange: this request is so old but not fixed yet. This feature is "must have". 

Other social network engines have already started working on that. For example, Jomsocial has this functionality by default. SE have third-party plugins (from Hire Experts and Younetco) with a possibility of multi-uploading of photos to the feed. If I'm not mistakem, they promised to do it as a built-in feather.
![younet](https://cloud.githubusercontent.com/assets/18528411/17238424/34d0480c-5564-11e6-8f3e-218ff6ca70af.png)
------
![he_wall plugin](https://cloud.githubusercontent.com/assets/18528411/17238425/34e2cf40-5564-11e6-9634-5fb9ada7f515.png)


I would also reccommend to add two options more to this feather:
1. User can choose an album where photos will be uploaded, when posting to the feed (JomSocial implemented it). It will be really covinient option.
![jomsocial](https://cloud.githubusercontent.com/assets/18528411/17238420/2eea6878-5564-11e6-96ef-8c342be2e7e3.png)
2. If an album isn't selected, photos should be uploded in some dedicated album like "Wall photos". The similar logic is when uploading profile images.

**Comment by akvaskov** [comment]
Comment on my previous comment :) There is a ticket about the [thing ](https://github.com/moxi9/phpfox-feature-requests/issues/110) I talked in the end of my message. It seems that an ability to keep feed photos in some dedicated album is really wanted.
