### ISSUE TITLE
hashtag Auto Suggestion

### ISSUE THREAD

**Issue by SalmanKhan86** [PHPfox-Official/phpfox-v4-feature-requests#170]
when we put some hash tag in status share and in comment box we have to type full name of tag.Better option is here after typing one or two character its Auto suggest.

**Comment by SalmanKhan86** [comment]
how much time its takes to implement

**Comment by neil96** [comment]
Hi @SalmanKhan86 ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
