### ISSUE TITLE
Pages ...like unlike should say follow unfollow  

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-feature-requests#184]
hi beta 4.4.0-1 win10 firefox latest php5.5

when you click on PAGES it asks you to like or unlike.

I think this should say Follow and UnFollow instead since it is saying how many followers

**Comment by Data66PF** [comment]
You can change this in phrase manager but we can look at changing it next time we look at feature requests.

**Comment by neil96** [comment]
Hi @spirogg ,

On 4.6.0, we use Like/UnLike for these sections.

Regards.
