### ISSUE TITLE
Copy Feed Link Feature

### ISSUE THREAD

**Issue by SalmanKhan86** [PHPfox-Official/phpfox-v4-feature-requests#191]
it would be nice if we have direct copy feed link feature.then one can easily copy any feed link and use it.
copy feed link may be integrated under Report link.when we click on it a pop up box open with same feed url.. currently we have to open time-stamp link in order to copy particular feed url.
![copy link](https://cloud.githubusercontent.com/assets/13433124/17046665/6d1080a4-4ff3-11e6-8ae1-93d0de2397fe.png)

**Comment by Data66PF** [comment]
You can already share it. I am not clear on the purpose of this since you can share it already.

**Comment by SalmanKhan86** [comment]
we can give that feed url link to someone same as
![twitter copy link](https://cloud.githubusercontent.com/assets/13433124/17125927/8ca76610-5315-11e6-9263-75410e64763d.png)

**Comment by neil96** [comment]
Hi @SalmanKhan86 ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
