### ISSUE TITLE
Nothing happens when photo uploading failed

### ISSUE THREAD

**Issue by akvaskov** [PHPfox-Official/phpfox-v4-feature-requests#205]
Hi,
When I'm posting big photos, uploading stops due to a size limit for images. The PF shows a respective list of failed uploads and that's all: there are no any buttons, for an instance, "Cancel" or "Continue". It makes users confused, they don't know what to do further.
![photo upload failed](https://cloud.githubusercontent.com/assets/18528411/17164247/1b3a55e0-53cf-11e6-809b-61fe10784219.png)

Moved from [here](https://github.com/moxi9/phpfox/issues/1585#issuecomment-236071680).

**Comment by Data66PF** [comment]
I'm not sure I see the need for a cancel or continue as the process is already done. Cancelling would do nothing at this point.

Do you instead want a different message than "failed" such as "Failed due to...(reason)"?

**Comment by akvaskov** [comment]
In normal cases, after successful uploading, an user is automatically redirected to a page to update info of uploaded photos. But, as I mentioned above, in a case if there was some problem with uploading, nothing happens, no redirection. I think it would be better if there was a "Continue" button and after clicking it you are redirected to the mentioned page.

**Comment by akvaskov** [comment]
Hi, any news or decesion about this request?

**Comment by Data66PF** [comment]
When we are looking at features again we will check this one. We already looked at features for 4.5 a few weeks ago.

**Comment by Silkonchord** [comment]
Hi, Any news about this please, am having the same issue!
