### ISSUE TITLE
Show all menus in Pages

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-feature-requests#208]
It's quite annoying when you have a full screen and not all the menu are shown in pages. 

![screenshot](https://cloud.githubusercontent.com/assets/19594886/17275658/59013bc6-56dd-11e6-9b69-0ef3a65c7c9d.png)

It would be nice to have an option to control the number of menus that are displayed for pages similar to how you can enter how many you want to display on the main menu.

**Comment by neil96** [comment]
It's working as our designed, please open a new request [here](https://github.com/moxi9/phpfox-feature-requests).

**Comment by comemoreru** [comment]
It already is

**Comment by prepperz** [comment]
The main menu does, the pages menu does not.

**Comment by comemoreru** [comment]
there is

**Comment by comemoreru** [comment]
/admincp/setting/edit/?group-id=general    .......... Number items of main menu

**Comment by prepperz** [comment]
I don't think you understand what I'm talking about. it's for pages on v4.4

**Comment by comemoreru** [comment]
you want to change the menu for pages and groups?

**Comment by prepperz** [comment]
Yes, that is what I'm pointing out.

**Comment by neil96** [comment]
Dear all,

This feature is now available on phpFox 4.6.0.

Regards.
