### ISSUE TITLE
Make Default Bootstrap untouchable from admin cp

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-feature-requests#211]
I'm seeing many people run into issues, so if the default bootstrap is not to ever be touched why not make so it can't be touched from the admin cp? This way there is no chance that it will ever be modified from the admincp.

**Comment by neil96** [comment]
Hi @prepperz ,

We supported feature revert theme. Admin can revert their change.

Regards.

**Comment by neil96** [comment]
Hi @prepperz ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
