### ISSUE TITLE
total post count

### ISSUE THREAD

**Issue by SalmanKhan86** [PHPfox-Official/phpfox-v4-feature-requests#219]
it would be great if we have shown total count of how many no of post posted by user in his profile.
just like twitter show count of tweets.
![total post count](https://cloud.githubusercontent.com/assets/13433124/18026759/d9d28ad8-6c6e-11e6-9f0d-bcd47e903a60.png)

**Comment by Data66PF** [comment]
We have something coming similar to this after 4.5. We will look at this one when we see what our own feature has for it.

**Comment by neil96** [comment]
Do you mean **user status**?

**Comment by SalmanKhan86** [comment]
yes

**Comment by neil96** [comment]
Hi @SalmanKhan86 ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
