### ISSUE TITLE
Gifts

### ISSUE THREAD

**Issue by Criotin** [PHPfox-Official/phpfox-v4-feature-requests#229]
1) Make a block with the gifts that the user has received.
2) Make sure that the gifts are displayed horizontally.

![gifts](https://cloud.githubusercontent.com/assets/15389101/18691431/4be70e88-7f9c-11e6-890f-90d73779612c.png)

**Comment by djafrika** [comment]
Maybe something like this...

![gift concept](https://cloud.githubusercontent.com/assets/22333440/20102086/0e3e14a6-a5c5-11e6-9f9d-8963be0741b5.jpg)

Gifts having it's own tab and nice alignment with mouseover effect...

**Comment by Criotin** [comment]
Maybe yes.

**Comment by neil96** [comment]
Dear @Criotin ,

This feature is now available on phpFox 4.6.0.

Regards.
