### ISSUE TITLE
Expanding Points System: Tracking

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-feature-requests#243]
Over the years I'm surprised no one has focused on the points system. This could have huge impact on a site if used properly and is one of the most neglected and under utilized assets.

Currently there is no way to track where points are going and coming from. For example when gifting points it simply goes out, and there's no record of who it was sent to and who points are received from. We need a way to track points.

**Comment by djafrika** [comment]
Definitely. Activity points could make website more interesting. 
My suggestion is radical change. Make activity points backbone of the script. Something that will distance phpfox from competitors. 

- **Recurring Payouts** - gift points hourly, daily, weekly. Depending on how active user is on the site.
- **Ranks** - rank users based on how many points user has. User has icon next to his name. 
- **Achievements** - when user posts blogs, forum posts, comments, whatever. He receives achievement badge that he can show next to his name. 
- **Lottery Game** - users can buy lottery ticket and win points
- **Central Banking** - ability to have central banking system. Points don't come out of nothing. Admin sets starting amount and this amount can be increased only by purchasing more points. Every point gained by users is deducted from admin and any purchased goes to admin. (great for monetisation)
- **Sell Content** - charge x points to be able to see content. Video, blog, etc...
- **Fees** - charge fee on sold content. x% of charged content goes to admin
- **Coupons** - win, buy or earn coupons. coupons can be set to win free points or to lower price of items on marketplace, etc...
- **Points History** - users can see where they have earned points and where did they spend it.
- **Statistic** - admins have statistic of points gained, purchased, gifted, etc...
- **Buy Points** - admin have option to set points packages for purchase.
- **Notifications** - users must receive notifications for everything regarding activity points

I know that this is time consuming and you will probably ignore this post but at least take some time to think about benefits phpfox would have if it had something like this. It would definitely be something to brag about...

**Comment by neil96** [comment]
@djafrika Thanks for you requests. But please separate your request to new issue. Posting 1 request per issue. It will easy for us to check and implement your request.
You can check [here](https://github.com/moxi9/phpfox-feature-requests) to know our guideline for posting new request.
