### ISSUE TITLE
Video is way too big! Make it a reasonable size. Just look at youtube for reference.

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-feature-requests#256]
Video is way too big! 

I don't know who thought it was a good idea to display the video in such a way that takes up almost the entire browser space that you need to scroll up and down. Not only is this really annoying, but it shows lack of care in development given this issue was brought up before and then is told it should be left up to 3rd parties.. Is phpfox intentionally trying to drive customers away by not addressing concerns?

Also lower video resolution videos looks like crap when it is so big. Now let me ask you this. Has anyone seen any sites that display it in the same way?
.

**Comment by neil96** [comment]
Hi @prepperz ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
