### ISSUE TITLE
video url is not seo friendly 

### ISSUE THREAD

**Issue by maniacscorpio** [PHPfox-Official/phpfox-v4-feature-requests#261]
Kindly do something video url is not SEO friendly ..

http://www.mywebsite.com/v/play/795092/

but it must be like this -

http://www.mywebsite.com/v/play/video-topic-name/

**Comment by IsabellaJolie** [comment]
Hi maniacscorpio,
This feature is available in newest video app. Please check it at https://store.phpfox.com/product/1819/video
