### ISSUE TITLE
Activities permalink

### ISSUE THREAD

**Issue by djafrika** [PHPfox-Official/phpfox-v4-feature-requests#263]
I think it would be nice to have permalink for every activity.
![ss](https://cloud.githubusercontent.com/assets/22333440/19961297/29c46408-a1b2-11e6-9b9b-fb90af38a60f.jpg)
same as it is when viewing single forum post.

**Comment by neil96** [comment]
Hi @djafrika ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
