### ISSUE TITLE
The report

### ISSUE THREAD

**Issue by Criotin** [PHPfox-Official/phpfox-v4-feature-requests#265]
Make it so that it would be possible to mark the report as "processed".

**Comment by neil96** [comment]
Please add more information in your request. We have guideline for feature request here: https://github.com/moxi9/phpfox-feature-requests

**Comment by Criotin** [comment]
After the administrator has handled the received report, it must be marked as "processed". Make a button with which the administrator will be able to mark the complaint as "processed".
![reports](https://cloud.githubusercontent.com/assets/15389101/20064240/0ec35148-a51b-11e6-99d2-91b5d143193b.png)

**Comment by neil96** [comment]
Dear @Criotin ,

This feature is now available on phpFox 4.6.0.

Regards.
