### ISSUE TITLE
Show and Hide Photo File Name

### ISSUE THREAD

**Issue by juniortimeline** [PHPfox-Official/phpfox-v4-feature-requests#278]
Hi, All social network site now haven't a file name to be clear the theme/page and more simple like twitter and facebook. I suggest to add some control on admincp if we would like to hide a photo name or show. Thank You

**Comment by SalmanKhan86** [comment]
really this option is very important for social networking site

**Comment by neil96** [comment]
Dear @juniortimeline ,

This feature is now available on phpFox 4.6.0.

Regards.

**Comment by juniortimeline** [comment]
Hello @neil96 I already check all the photo settings but I did not see any option to hide filename of photos. Thank You

**Comment by neil96** [comment]
Hi @juniortimeline 

It's hidden by default.

Regards.

**Comment by juniortimeline** [comment]
Hi @neil96  the file name of photo is still show http://prntscr.com/hyvr1n

Regards

**Comment by neil96** [comment]
Hi @juniortimeline ,

It's title. You can change it anytime.

**Comment by juniortimeline** [comment]
Hello @neil96 

Yes It's a File name of photos becomes a title on our website. There is no need a photo title show like other social network site because they avoid the non proper look like this http://prntscr.com/hyvukk 98% of people using social network doesn't need a title of photos because they already have a text post and this photo title already avoid of this social network generation because people use a #hashtag. That's why I suggest to have an option on admincp to hide or show photo title on depends. Thank You so much and regards.
