### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by one44123** [PHPfox-Official/phpfox-v4-feature-requests#279]
Not sure if this is where features are requested but I am sure an improved menu feature would be welcomed by most users as when new pages etc are added they are all added to the last drop down "more" in the menus. Adding and grouping menus under drop down headings is needed.

**Comment by prepperz** [comment]
This was part of the core feature in v3.8 stuff like this shouldn't be left 3rd parties. This should be a default core feature.
