### ISSUE TITLE
Edit Video title

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-feature-requests#280]
We used to be able to edit video title in the old versions. Bring this feature back.

**Comment by neil96** [comment]
It's working normal.

**Comment by prepperz** [comment]
we used to be able to do this pre-v4 like in v3.x.x

**Comment by prepperz** [comment]
This is why I say that when v4.x.x came out it was like taking 20 steps backwards because it didn't come with the core feature of 3.8 by default. So anyone that had a succesful community with 3.8 and updated they'd be crippled because they suddenly lose critical core features.

**Comment by IsabellaJolie** [comment]
Hi prepperz,
We will consider to implement it in phpFox 4.6. Thanks for your help.

**Comment by IsabellaJolie** [comment]
Hi prepperz,
This feature is available in the newest video app. Please help to check it at https://store.phpfox.com/product/1819/video
