### ISSUE TITLE
Video categories.

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-feature-requests#281]
We used to be able select categories. Bring this back.

**Comment by Rodios** [comment]
I will like that to 👍 If I share a video, I have no option to choose a category for the video either in the video section

**Comment by neil96** [comment]
Video app allows you select category when you edit. It has been working like this from the beginning.

**Comment by Rodios** [comment]
We know it. But how many users will know that haft to edit the video for choose a category and if the will understand that it will be too much to do for one video.
The correct way is to choose the category the moment you add the video

**Comment by IsabellaJolie** [comment]
Hi Rodios,
We will consider to add this feature in phpFox 4.6. Thanks for your help.

**Comment by chena321** [comment]
yes.  we need it.

**Comment by IsabellaJolie** [comment]
Hi all,
This feature is available on new Video app. Please help us to check it at https://store.phpfox.com/product/1819/video
