### ISSUE TITLE
Activity Points (Radical Changes)

### ISSUE THREAD

**Issue by djafrika** [PHPfox-Official/phpfox-v4-feature-requests#287]
Posting new issue due to issue policy.
My suggestion is radical change. Make activity points backbone of the script. Throughout the lifetime of phpfox activity points are being neglected and that must change because it could be something that will distance phpfox from competitors. 

- **Recurring Payouts** - gift points hourly, daily, weekly. Depending on how active user is on the site.
- **Ranks** - rank users based on how many points user has. User has icon next to his name. 
- **Achievements** - when user posts blogs, forum posts, comments, whatever. He receives achievement badge that he can show next to his name. 
- **Lottery Game** - users can buy lottery ticket and win points
- **Central Banking** - ability to have central banking system. Points don't come out of nothing. Admin sets starting amount and this amount can be increased only by purchasing more points. Every point gained by users is deducted from admin and any purchased goes to admin. (great for monetisation)
- **Sell Content** - charge x points to be able to see content. Video, blog, etc...
- **Fees** - charge fee on sold content. x% of charged content goes to admin
- **Coupons** - win, buy or earn coupons. coupons can be set to win free points or to lower price of items on marketplace, etc...
- **Points History** - users can see where they have earned points and where did they spend it.
- **Statistic** - admins have statistic of points gained, purchased, gifted, etc...
- **Buy Points** - admin have option to set points packages for purchase.
- **Notifications** - users must receive notifications for everything regarding activity points

I know that this is time consuming and you will probably ignore this post but at least take some time to think about benefits phpfox would have if it had something like this. It would definitely be something to brag about...

**Comment by IsabellaJolie** [comment]
Hi djafrika,
Thanks for your suggestion. After we finish the phpFox 4.5, we will check it carefully. In general, some feature should be considered:
1. Recurring Payouts - gift points hourly, daily, weekly. Depending on how active user is on the site.
2. Points History - users can see where they have earned points and where did they spend it.
3. Statistic - admins have statistic of points gained, purchased, gifted, etc...
4. Buy Points - admin have option to set points packages for purchase.
5. Notifications - users must receive notifications for everything regarding activity points

Beside, some features should be developed by other developers as following:
1. Ranks - rank users based on how many points user has. User has icon next to his name.
2. Achievements - when user posts blogs, forum posts, comments, whatever. He receives achievement badge that he can show next to his name.
3. Lottery Game - users can buy lottery ticket and win points
4. Central Banking - ability to have central banking system. Points don't come out of nothing. Admin sets starting amount and this amount can be increased only by purchasing more points. Every point gained by users is deducted from admin and any purchased goes to admin. (great for monetisation)
5. Sell Content - charge x points to be able to see content. Video, blog, etc...
6. Fees - charge fee on sold content. x% of charged content goes to admin
7. Coupons - win, buy or earn coupons. coupons can be set to win free points or to lower price of items on marketplace, etc...
Regards,

**Comment by prepperz** [comment]
#4 should be a core capability, but let 3rd party dev extend the capability. We need this badly. It's long overdue. 

Being able to use points to purchase stuff around the site is imperative.

**Comment by Promastertr** [comment]
This feature must be done urgently. Activity points can be used and tracked as site money

**Comment by Scheinwelt-Media** [comment]
there is an app in the store for ranking with activity points. check it out here https://store.phpfox.com/product/1633/ranking-system-activity-icon

**Comment by djafrika** [comment]
Thank you but I'm not interested into spending any more money into this script. I'm considering switching to open source alternative that is much, much better, has a lot of plugins, most of them are free, and best of all, it works flawlessly...

**Comment by prepperz** [comment]
This should be a priority and core function of the script aside from having it as bug free as possible, but I highly doubt the bug free part from the crew.

**Comment by chena321** [comment]
yes.  this helps us to earn something.

**Comment by dawn2323** [comment]
Very good suggestions!

**Comment by starplan** [comment]
I had to think for a while before posting on this topic and can understand why the follow would be considered.

1. Recurring Payouts - gift points hourly, daily, weekly. Depending on how active user is on the site.
2. Points History - users can see where they have earned points and where did they spend it.
3. Statistic - admins have statistic of points gained, purchased, gifted, etc...
4. Buy Points - admin have option to set points packages for purchase.
5. Notifications - users must receive notifications for everything regarding activity points

However, that said, the central banking concept is something that phpFoX should also consider as an app. Even if it is a paid app depending on the version of phpFoX license purchased.
