### ISSUE TITLE
Pages - Adding blocks

### ISSUE THREAD

**Issue by dreddmarketing** [PHPfox-Official/phpfox-v4-feature-requests#288]
1 - Need to be able to insert existing Phpfox blocks in each created page, in the html code used to build the page.
This should be very helpfull to create dynamics landing pages for SEO.

Thanks

**Comment by IsabellaJolie** [comment]
Hi dreddmarketing, 
We will consider this feature in phpFox 4.6. Thanks a lot for your suggestion.

**Comment by neil96** [comment]
Hi @dreddmarketing ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
