### ISSUE TITLE
Referral link with automatic friend add

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-feature-requests#289]
Currently when someone tells a friend about the site and when a friend joins they are not automatically connected. A referral link is something that should be a core part of phpfox. When people invite their friends via a link they post on a website or a forum, they should be automatically added on their friends list when they join via the link.

**Comment by IsabellaJolie** [comment]
Hi prepperz,
This feature is available in our core script. You can configure this by going to ACP --> Apps --> Invite --> configure the setting "Make invited users friends with their host"
