### ISSUE TITLE
Search under members

### ISSUE THREAD

**Issue by one44123** [PHPfox-Official/phpfox-v4-feature-requests#290]
Detail search includes all custom Fields. Can custom fields be made show/not show as some foelds are not required as they are write blocks of explanation etc. and should be excluded.

**Comment by Scheinwelt-Media** [comment]
check out my app for this feature https://store.phpfox.com/product/1688/search-custom-mod

**Comment by IsabellaJolie** [comment]
Hi one44123,
This feature is available in our core script. Please help to check this feature by going to ACP --> Custom Fields --> Edit a custom field and configure the setting "Include on search user".
