### ISSUE TITLE
Better menu management system.

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-feature-requests#291]
Currently, the menu is a complete mess. This also goes for pages and group menus. There's no way to organize the menu items in groups and you also cannot hide. Neil suggested deleting the menu item, which is different then simply hiding the item.

The menu management system has been neglected since the intro of v4. 

v3.8 had a decent core menu management system. Please bring these features back so we can at least have a semblance of organization. 

Also the menu should also have the option to select which group member can see each menu item.

**Comment by IsabellaJolie** [comment]
Hi prepperz,
Thanks for your suggest. We will consider to implement the feature to allow hide / show menu in 4.6.0.

**Comment by prepperz** [comment]
It should be at the least be what it was in v3.8

**Comment by neil96** [comment]
#86
