### ISSUE TITLE
Redesign AdminCP

### ISSUE THREAD

**Issue by Spaninet** [PHPfox-Official/phpfox-v4-feature-requests#293]
I would like to see a better AdminCP using Bootstrap with clean, modern  and more functional design.

- Use Bootstrap
- Allow Theme Developers/Designers to create and publish themes in Store

Example:

![Example](https://v4.phpfox.com/cdn/file/file/pic/photo/2016/12/9895192f305eca266b7a3d51bcf5e5f1.png)

**Comment by Ylmzef** [comment]
Also mobile ready!

**Comment by IsabellaJolie** [comment]
Hi Spaninet,
We're implementing new layout for Back End and we hope that this will meet your expectation

Hi Ylmzef
Regarding the new layout for Back End in mobile, we will consider it. Thanks for your suggestion.
