### ISSUE TITLE
Make the name in Menu (mobile) clickable

### ISSUE THREAD

**Issue by Spaninet** [PHPfox-Official/phpfox-v4-feature-requests#294]
Add link to user's profile for Name in menu (mobile device).

![](https://v4.phpfox.com/cdn/file/file/pic/photo/2016/12/a3fadcc130adc91c471b8312477913cc.png)

**Comment by Spaninet** [comment]
When you are logged in from a small screen device like a smartphone or if you resize the window in a computer the user name / name of the user in the main menu is not clickable because has no link to user profile like the user photo.

**Comment by neil96** [comment]
Hi @Spaninet ,

This feature will be available on martial theme.

Regards.
