### ISSUE TITLE
Add registration step

### ISSUE THREAD

**Issue by robert9592** [PHPfox-Official/phpfox-v4-feature-requests#296]
The add multi step registration feature needs to be brought back. It helps break up registration and many old sites that use it find it a great feature rather then a long single registration process. It also adds sections to the profile which can be made optional. Allows more flexibility for site individuation and types of sites to run.
Maybe allowing entry of input fields like text block, radio selection, multi selection etc as well as option to be in detailed search or not will make it a smoking hot module and give 100% flexibility for site creation.

From **one44** on [coummunity](https://community.phpfox.com/forum/thread/55745/add-registration-step/)

**Comment by shashankguitarist** [comment]
Also including Profile types and conditional questions ?

**Comment by shashankguitarist** [comment]
http://support.socialengine.com/php/customer/portal/articles/1644307-admin-panel---settings-&gt;-profile-questions
