### ISSUE TITLE
fields set to required at signup but skipped

### ISSUE THREAD

**Issue by shashankguitarist** [PHPfox-Official/phpfox-v4-feature-requests#303]
Create a Subscription Package named Musician , assign it to usergroup "Musician" ..Now create a custom field for the usergroup "Musician" name it  "Instrument" , tick on  "required" and "include on registration"......
Now if a new user chooses Package "Musician" , he will not be forced to fill the Required Custom Field "Instrument"  . 
how to deal with this ?

**Comment by neil96** [comment]
By default, the custom field for specific user group CAN'T BE REQUIRED at signup.

**Comment by shashankguitarist** [comment]
Can I expect this enhancement in the next release ?
