### ISSUE TITLE
Selecting a category when uploading a photo

### ISSUE THREAD

**Issue by theoplooy** [PHPfox-Official/phpfox-v4-feature-requests#308]
I noticed a feature request for picking a category when sharing or uploading a video
https://github.com/moxi9/phpfox-feature-requests/issues/281

I'd like to have this implemented also for photos.

Theo

**Comment by chena321** [comment]
Yes.  I think we had this on V3.

**Comment by neil96** [comment]
Dear @theoplooy ,

This feature is now available on phpFox 4.6.0.

Regards.
