### ISSUE TITLE
Soggestion for buttons

### ISSUE THREAD

**Issue by one44123** [PHPfox-Official/phpfox-v4-feature-requests#309]
Hi

Just a suggestion to use what is wasted real estate and may enhance user UI and make sites more user friendly. See suggestion here https://community.phpfox.com/forum/thread/55782/enhancement/

**Comment by aakash83** [comment]
Good suggestion.

**Comment by IsabellaJolie** [comment]
Hi one44123,
We will have new layout for Front End and we hope that this will meet your suggestion. Thanks
