### ISSUE TITLE
Create additional pages for groups and pages that can run code by admin

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-feature-requests#311]
It would be really nice if phpfox site owner/admins can create additional pages for groups and pages can run code.

For example a user creates a group or a page, but need specific function for their specific page. The site admin, then creates a new page, that can insert phpfox blocks that can run custom code created by the admin.

The services possibilities are endless.

**Comment by neil96** [comment]
This feature is available. The widget feature on pages/group can do that.

**Comment by prepperz** [comment]
Why did you close this? 

No it can't run code in the content of the created page.

**Comment by neil96** [comment]
> code

Is it `php code` or `html code`?

**Comment by prepperz** [comment]
it's html... should it matter?

**Comment by prepperz** [comment]
What's the detail to this?

**Comment by IsabellaJolie** [comment]
Hi prepperz,
Sorry for the misunderstanding. After checking the feature carefully, we see that it is not in any version of phpFox until now. If you really want to have this feature, we will consider to implement it in next versions.
