### ISSUE TITLE
Relocate the uper imposed friend add button. It's blocking faces.

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-feature-requests#317]
See here: https://github.com/PHPfox-Official/phpfox-v4-issues/issues/1764#event-912865951

Move it to the lower left or right

![stuff](https://cloud.githubusercontent.com/assets/19594886/22067098/c3b62b3c-dd5d-11e6-9f03-fcc579fd5291.png)

**Comment by prepperz** [comment]
It would be nice to get this into 4.5.2 so it looks at least half decent, since it will be another 3-4 months before 4.6 and who knows what kind of issue that will present given past releases.

**Comment by neil96** [comment]
Hi @prepperz 

We improved this on phpFox 4.6.0.

Regards.
