### ISSUE TITLE
Hide Forum Files from Guests

### ISSUE THREAD

**Issue by Lidercan** [PHPfox-Official/phpfox-v4-feature-requests#318]
- Hide forum files (Attachment) from guest to download. Guest should read forum threads but files not download without Registration. 
- Attachment files (zip, rar etc.)  after Browser refresh not visible.  Only in line visible. Make please the files also visible.

**Comment by neil96** [comment]
Hi @Lidercan ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
