### ISSUE TITLE
Add video tab to profile feed

### ISSUE THREAD

**Issue by Spaninet** [PHPfox-Official/phpfox-v4-feature-requests#32]
Add videos tab to profiles page. Should be the same style as in dashboard.
#### Profile page:

![Screenshot](https://camo.githubusercontent.com/e6d50b9fa3c19ee99e35a49f540864d346a40515/68747470733a2f2f73746167652e706870666f782e636f6d2f66696c652f7069632f70686f746f2f323031362f30312f62666239313765313866643166323437333130643831346233323537313562625f313032342e706e67)
#### Dashboard/home page

![Screenshot](https://community.phpfox.com/file/attachment/2016/02/8a29888017ac9098949248e9cbf382b7.png)

**Comment by jhayden2000** [comment]
Please add this.. The one thing all my testers keep asking is why the video tab is everyone where else, except the profile feed and the events feed. This seems more like an oversight then anything else.

**Comment by IsabellaJolie** [comment]
Hi Spaninet and jhayden2000,
We've already added this feature request to our new video app which will be released soon in April. Thanks for your suggestion.
