### ISSUE TITLE
Members search sort

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-feature-requests#324]
in the members -> search section it would be nice to be able to sort capabilities. It would make administrative tasks a bit easier. For example, if someone creates a bunch of spam accounts you'd be able to easily spot because it has the same IP address. 

![stuff](https://cloud.githubusercontent.com/assets/19594886/22018685/1dad246e-dc7e-11e6-8174-fa8c0740be3f.png)

**Comment by shashankguitarist** [comment]
also if this option is added in the frontend , will be a great tool to search members

**Comment by neil96** [comment]
#67
