### ISSUE TITLE
Option to Change color of titles of pages and group.

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-feature-requests#325]
There needs to be an option to change the color of the pages and group title. When uploading a white cover image renders the title invisible as it's the same color as the background.

![stuff](https://cloud.githubusercontent.com/assets/19594886/22022319/7b1ddb96-dc8f-11e6-9a1f-e6aec8288cf2.png)

**Comment by neil96** [comment]
Dear @prepperz ,

This feature is now available on phpFox 4.6.0.

Regards.
