### ISSUE TITLE
Pages and group menu needs to be darker

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-feature-requests#326]
Obviously, phpfox didn't see this as an issue so I'm putting this as feature request:

You can reference it to here: https://github.com/PHPfox-Official/phpfox-v4-issues/issues/1849

**Comment by IsabellaJolie** [comment]
Hi prepperz,
In 4.6.0, we will re-design all pages and we hope that it will solve your issue. We will try to use color as good as your expectation. Thanks for your contribution.
