### ISSUE TITLE
Save search

### ISSUE THREAD

**Issue by makfoulie** [PHPfox-Official/phpfox-v4-feature-requests#328]
Hello,

I would like members can save their search settings. 
For example if a user search members in a country he can save this search with a personnal name. More he can search members in another country and can save this new search with another personnal name.

More he can click on these searches names to view members with predefined parameters.

Hope you can understand what I'm talking about^^.

Regards.

**Comment by IsabellaJolie** [comment]
Hi makfoulie,
This feature should be implemented by other developers. Regards.
