### ISSUE TITLE
Track which emails have already been sent to inactive members to prevent getting blacklisted

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-feature-requests#330]
Currently the system doesn't track any emails being sent, so If the process get stuck and the admin restarts it, it will keep sending emails to the same users over again. This can get a server ip black listed by mail service providers.

The reference to this issue is here: https://github.com/PHPfox-Official/phpfox-v4-issues/issues/1797#issuecomment-275394840

**Comment by neil96** [comment]
Hi @prepperz ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
