### ISSUE TITLE
List public pages/group videos option

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-feature-requests#331]
I've noticed that in the latest build that videos added to pages no longer show up in the main video section. It would be nice to have an option that let the users select to show videos from public pages in the main video section as well as search as being able to search them.

This way it enables users to explorer content in which they may have never known about and ultimately lead them to the pages or groups.

**Comment by IsabellaJolie** [comment]
Hi prepperz,
This feature will be available from phpFox 4.6.0. Regards.

**Comment by shashankguitarist** [comment]
Same for music
