### ISSUE TITLE
Pages and Groups, Add Category to Forums

### ISSUE THREAD

**Issue by Promastertr** [PHPfox-Official/phpfox-v4-feature-requests#333]
I think that it will be more efficient if category and sub-category facilities are provided by the administrators in the pages and groups and in the forums

**Comment by Promastertr** [comment]
Pages and Groups should be allowed to add categories to Forums

**Comment by neil96** [comment]
Hi @Promastertr ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
