### ISSUE TITLE
Facebook emoji reaction system on phpfox v4 !

### ISSUE THREAD

**Issue by crea7web** [PHPfox-Official/phpfox-v4-feature-requests#339]
Facebook emoji reaction system on phpfox v4 for users like comment post to all site from phpfox v4 (Edit on admin cp) !

![facebook-emojis-today-160224-tease_5405c105acc2da6fdbf9336038d2a262 today-inline-large](https://cloud.githubusercontent.com/assets/25670447/23331386/3c3f320e-fb65-11e6-9577-7994124b80ac.jpg)

**Comment by neil96** [comment]
Hi @crea7web ,

There is a similar app on the store: https://store.phpfox.com/product/1133/reactions

Regards.
