### ISSUE TITLE
Shares made, read, watched or watched, the sharing activity gain points

### ISSUE THREAD

**Issue by Promastertr** [PHPfox-Official/phpfox-v4-feature-requests#341]
Site members can earn activity points when they are read or watched on the site, in the Shares, on the shares, by other members. On this Say, people can pay for quality, more, share, these scores, wake up money.

**Comment by Promastertr** [comment]
Members can pay small fee per visit just like youtube

**Comment by neil96** [comment]
Hi @Promastertr ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
