### ISSUE TITLE
"Users you may know" as feed entry

### ISSUE THREAD

**Issue by makfoulie** [PHPfox-Official/phpfox-v4-feature-requests#343]
Hello,
The feature "Users you may know" exist in all social networks. It appears as feed entries

Screenshots here:
https://www.google.fr/search?q=users+you+may+know&espv=2&source=lnms&tbm=isch&sa=X&ved=0ahUKEwimiK-mkuPSAhXJuhQKHdrKBxcQ_AUIBygC&biw=1920&bih=960

Ideas for AdminCP settings:
- Show only users with Pictures? Yes/No
- Show only members of the opposite sex? Yes/No
- How many users in common?
- How many members to show?
- Use slider? Yes/No
- Where to show entry feed? Ramdomly or set a number. For example if you set "2", every 2 feed entry the "block" is dispalyed

Front end:
- Possibility for users to ask member as friend

Maybe you have other ideas ;).

I know a block already exist, but my idead is to display as feed entry, as we can see on facebook, twitter, instagram...

**Comment by neil96** [comment]
Hi @makfoulie ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
