### ISSUE TITLE
Payment Gateway integration for Events

### ISSUE THREAD

**Issue by srikumar101** [PHPfox-Official/phpfox-v4-feature-requests#344]
Events should be integrated with Payment Gateway. 

Admin should have an option to enable or disable payment gateway integration with events.  
Only creators/users/organizers who belong to a certain user group can receive payments. Creators/users should have updated their bank account details and verified can only receive payments. 
Creator of the event has an option to enable receiving payments if payment gateway is enabled by the admin and if he belongs to the verified user group.
Creator can view who all made the payment and how much for a particular event. 
Admin can set a % which will be deducted as processing fee and rest will be paid to the creator. 
When user clicks on RSVP button he should be prompted to make the payment, RSVP will be confirmed only after payment is successful.

**Comment by IsabellaJolie** [comment]
Hi srikumar101 ,
This feature should be implemented by other developers. Regards.
