### ISSUE TITLE
temporary promotion for birthdays

### ISSUE THREAD

**Issue by erick260** [PHPfox-Official/phpfox-v4-feature-requests#353]
If you have your account set to your correct birthday you can get a temporary promotion to another user group (for a set number of days). After the set time is up, your membership goes back to the normal user group. 
   To help fight the abuse of this system  the birthday promotions should only happen once a year per account.

**Comment by erick260** [comment]
This will be our gift to the birthday users!

**Comment by neil96** [comment]
Hi @erick260 ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
