### ISSUE TITLE
Option To Add More SSL Pages

### ISSUE THREAD

**Issue by erick260** [PHPfox-Official/phpfox-v4-feature-requests#355]
I noticed by default phpfox already has certain pages that use https like the login, registration and account setting pages, but i noticed it does not have https on one of the most important page subscribe and subscribe/compare pages. 
 -   IF we had a feature that would allow us to add more pages to the https that would be grate. 

    * That option would also solve my next problem  (example)
   I have a 3rd party app from the app store paymentwall. On my site it comes up http://mysite.com/paymentwall by us having that option i can easy make this page, and other pages i want secure with https.

**Comment by neil96** [comment]
Hi @erick260 ,

From 4.6.0, admin only have two options: turn on or turn off https. https for some specific pages does not work with ajax mode.

Regards.
