### ISSUE TITLE
Management for IM app

### ISSUE THREAD

**Issue by Ylmzef** [PHPfox-Official/phpfox-v4-feature-requests#356]
Please add more management for IM app
* See all private messages
* Add report link for message
* Limitations (Daily message limit, Allow to send first 2 message untill get answer)
* Notification mail when message received while offline (also disable enabled notification)

**Comment by neil96** [comment]
Hi @Ylmzef ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
