### ISSUE TITLE
Can can add -movflags +faststart as an output option for new video app please

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-feature-requests#358]
https://trac.ffmpeg.org/wiki/Encode/H.264#faststartforwebvideo

Can You can add -movflags +faststart as an output option ??

If your videos are going to be viewed in a browser, This will move some information to the beginning of your file and allow the video to begin playing before it is completely downloaded by the viewer.
please

**Comment by neil96** [comment]
Hi ,

Thanks for your suggestion. But currently it does not map with our plan.

Regards.
