### ISSUE TITLE
rule for category - no sub category

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-feature-requests#359]
what about a drop down sub category

so category always shows ? 

Example Category

( Music ) click on music link and a drop down of sub categories appear
Dance
Waltz
pop
country etc..
if no sub category exists all the categories are still there ?

would be so much more user friendly

thanks for your time, hope you can make this work somehow

**Comment by neil96** [comment]
Dear @spirogg ,

This feature is now available on phpFox 4.6.0.

Regards.
