### ISSUE TITLE
New email on login

### ISSUE THREAD

**Issue by darksolar1** [PHPfox-Official/phpfox-v4-feature-requests#36]
Sometimes a user's email goes bad for various reason (email full, server no longer active, etc...) and causes a bunch of bounced mail. It would be a great to have an option for the admin to temporarily disable any email notification for the member and require them to change their email the next time they login. After they enter a new email, the email notification would automatically be re-enabled again.

**Comment by Data66PF** [comment]
I do that in the edit user screen where it lets admin change the notifications. Have you tried that? I know this is so the user will have to change their email, which is a good idea, I'm just mentioning how you can already disable the notifications just to help you.

**Comment by lueung** [comment]
ThanksYes. I currently do that, but it's not quite the solution I was looking for.  Most of the time, they are unaware that something with there email even if they don't get notification so they don't bother changing their email. So it would be easier to automate the process and instruct them to change their email when they login very much in the manner as the force profile image upload. On large site this can be a lifesaver to the admin.

**Comment by lueung** [comment]
So today I have another user with a similar issue. I can't imagine if this issue is multiplied by thousands of users if you have a large site. Wow, it would be a total nightmare.
