### ISSUE TITLE
Set specificcategory permission for  pages/groups creation

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-feature-requests#360]
Currently there is no way to set category permission to disallow users in any other group other than site admin to create pages in a certain category.

For example,  I want to have a category called, "Site services. only" 

In this "site services only" category, it is reserved for only the site admin can create pages, but not regular users. Hoever, they can participate on the pages like normal.

...or better yet, exclude it from the category selections during page/group creation.

**Comment by neil96** [comment]
Hi @prepperz ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
