### ISSUE TITLE
Do not allow to upload photo or video or anything without having to select a category

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-feature-requests#361]
can we restrict users to select a category when uploading a photo video music etc.. ?
it seems if they don't select a category, it is in a blank empty category.

 Problem is we have to search for that video music photo (s) and edit it to put it in the correct category it belongs too.

 if we made a restriction that all users had to select a category otherwise their photo, video, music etc.. would not be uploaded.. keeping some structure on the website

thanks hope this is an easy fix

Spiro

**Comment by neil96** [comment]
Hi @spirogg ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
