### ISSUE TITLE
Suggested Videos in New App 

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-feature-requests#362]
Suggested Videos Limit 
Define the limit of how many suggested videos can be displayed when viewing a video detail.

---------------------------------------------------------------------------------------------------------------
<<< my suggestion is this below >>>
( Suggested Videos More limit )
Define the more button limit of how many videos can be displayed under suggested videos when viewing a video detail ??

---------------------------------------------------------------------------------------------------------------
HI can we have a more button at the bottom of the last video . 

example : we set 6 videos in video app for suggested videos. 
under the last video we have a (more button) to show more videos under . 

Create another area in videos that has the more option we can set how many more videos to show when we click more button 

i think this would be a good feature

**Comment by neil96** [comment]
Dear @spirogg ,

This feature is now available on phpFox 4.6.0.

Regards.
