### ISSUE TITLE
New Video App - Random feature

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-feature-requests#363]
I would also like to suggest a feature that can give us the option to make videos Random when you click the video link.. 

even though it says latest, we want to fool this setting and make videos random for viewing, this will  make our site look fresh to users - guests 

So somewhere in the video app we can have 

**Set Videos to Random = YES - NO**

lets say you don't have a busy site and just starting out, this would be a good feature for videos to look like there are users uploading videos.. instead of seeing the same videos when you click the video app

** please can we have this also for photos, blogs, music, videos ??**

thank you

**Comment by neil96** [comment]
Hi @spirogg ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
