### ISSUE TITLE
selection of pages feature to enable 

### ISSUE THREAD

**Issue by erick260** [PHPfox-Official/phpfox-v4-feature-requests#368]
When you create page and what if you don't want your page to have all the menus, How about selecting/Enabling what features your page will be using. So not all tabs are necessary.   
![navy field2 19social com](https://cloud.githubusercontent.com/assets/19263189/26477103/20852ef2-4178-11e7-9889-2e276093a780.png)

**Comment by neil96** [comment]
Hi @erick260 ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
