### ISSUE TITLE
Crop/Move Cover Photo for Event

### ISSUE THREAD

**Issue by CimborNet** [PHPfox-Official/phpfox-v4-feature-requests#371]
Hello,

Is it possible to add functionality so that you can edit the photo for the cover of the event? Well, for example, move it up or down, as it is done with the covers of the user or group profile.
Thank you.
![1](https://cloud.githubusercontent.com/assets/11414490/26557827/877f2aac-44a4-11e7-991b-07756460a2db.jpg)
![2](https://cloud.githubusercontent.com/assets/11414490/26557826/877f0c48-44a4-11e7-9bbd-908ef79fe8ec.jpg)
![3](https://cloud.githubusercontent.com/assets/11414490/26557828/878275f4-44a4-11e7-8a77-54c9b680d614.jpg)

**Comment by neil96** [comment]
Hi @CimborNet ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
