### ISSUE TITLE
Continue playing music while navigating the pages of the site.

### ISSUE THREAD

**Issue by CimborNet** [PHPfox-Official/phpfox-v4-feature-requests#372]
Is it possible to make sure that when visiting different pages of the site the music does not stop (did not break) and continue to play the songs?

How it is done for example in the social network vk.com

![8](https://cloud.githubusercontent.com/assets/11414490/26558049/3231889a-44a6-11e7-930d-0fdcbf37deb7.jpg)

There, music continues to play even when moving from one page of the site to another.

![9](https://cloud.githubusercontent.com/assets/11414490/26558048/323091e2-44a6-11e7-9b88-28f772aaa9de.jpg)

**Comment by neil96** [comment]
Hi @CimborNet ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
