### ISSUE TITLE
Playlist for user songs.

### ISSUE THREAD

**Issue by CimborNet** [PHPfox-Official/phpfox-v4-feature-requests#373]
You need to make a playlist for the user's songs.

In this playlist user can:

1. Create his own playlists. Sort by groups and share a playlist with others, Play songs not as they are uploaded to a music album, but in any order and sort at its discretion.

2. That the user himself could sort these songs, and indicate their order of reproduction

3. And most importantly! The user should be able to add to the playlist music that he liked on the page of other users, without having to download and re-upload to his profile ..

Just put the label "Add to my playlist" and he will be able to listen to it without rebooting to the server of the same MP3.
![12](https://cloud.githubusercontent.com/assets/11414490/26558363/5761ec16-44a8-11e7-98c2-1ed00b59ff70.jpg)

Adding this method of music to his playlist, he can hear it as if he had downloaded it himself.

This will save users from routine searching, downloading and uploading one and the same MP3 to themselves in their own musik album.

**Comment by neil96** [comment]
Hi  @CimborNet ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.

**Comment by bennington111** [comment]
"Add to my music" is very importment option. Why upload the same song if it already exists? If user can just add it to yourself. This will also save space on the server.
