### ISSUE TITLE
Capital letters in the name

### ISSUE THREAD

**Issue by CimborNet** [PHPfox-Official/phpfox-v4-feature-requests#374]
I would be very happy if the names of all users were automatically corrected when output to the screen.

Or, once all new users were registered, their names were corrected and only after that they were recorded in the database.

It is necessary to make so that all words in the name have Capital First Letters, and the remaining letters were small.

What I mean.

for example name:

DUSHAN -> Dushan
DushaN ->Dushan
DUSHAN -> Dushan
DUSHAN BERCIK -> Dushan Bercik
DUSHAN bercik -> Dushan Bercik

etc...

Thank you

P.S.
Well, or make it as an option, so that you can adjust it at the request of the administrator, that would change these settings for different groups. For example: VIP users to allow, everyone else is not!

**Comment by neil96** [comment]
Hi @CimborNet ,

This can be done by adding css in manage theme. You can refer here for more information : https://www.w3schools.com/cssref/pr_text_text-transform.asp

Regards.

**Comment by neil96** [comment]
Hi @CimborNet ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
