### ISSUE TITLE
Editing feeds

### ISSUE THREAD

**Issue by CimborNet** [PHPfox-Official/phpfox-v4-feature-requests#375]
I would like to be able to edit feeds written by users! It often happens that the user writes spam sites in the text. But at the same time the feed itself is not deleted.
![untitled-2](https://cloud.githubusercontent.com/assets/11414490/26738989/708a1800-47d0-11e7-9265-f4510cb4a24e.jpg)

**Comment by neil96** [comment]
Dear @CimborNet ,

This feature is now available on phpFox 4.6.0.

Regards.
