### ISSUE TITLE
In addition to the feeds and playlist

### ISSUE THREAD

**Issue by CimborNet** [PHPfox-Official/phpfox-v4-feature-requests#376]
In light of the talk about the convenience of working with the site and a playlist for music, I want to suggest adding a few options, which in my opinion should make life easier for users.

Add these options directly to the feed, such as "Delete feed."

Because, for example, to recommend a ONE song, I need to find it, go to it on site pege, click on the "Actions" (in top-right) icon and click again on the word "Recommend".

And so for every song you like.
And if there are hundreds of songs in the feed?

There would be an icon in the feed - it would be possible to recommend a song by one click.

-------------------

We all need quick editing and administration of the site to cope with thousands of feeds and tons of publications.

It takes a lot of time to click on the pages of the site only to "Recommend" the song, for example.

The best option is this:
I saw a song in the feed? Liked it and immediately recommend it. Two clicks and it's ready!

Finally, you can also add the "Add to My Playlist" button when the playlist system is ready.

![untitled-2](https://cloud.githubusercontent.com/assets/11414490/26753318/0dd14bb8-4864-11e7-85bb-c6b37f52a279.jpg)

**Comment by neil96** [comment]
Hi @CimborNet ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
