### ISSUE TITLE
Need links to pointers

### ISSUE THREAD

**Issue by CimborNet** [PHPfox-Official/phpfox-v4-feature-requests#379]
Hello.
It would be very good if you could not only know the number of users, blogs, videos, etc., but also see their list by clicking on the appropriate link.

![untitled-3](https://user-images.githubusercontent.com/11414490/27260388-5539072a-542b-11e7-9951-9ecf13e0fae3.jpg)

How it is done with the users online!

**Comment by neil96** [comment]
Hi @CimborNet ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
