### ISSUE TITLE
Big texts ,same sizes of texts,  large spaces , same colors of texts

### ISSUE THREAD

**Issue by shashankguitarist** [PHPfox-Official/phpfox-v4-feature-requests#386]
Version 4.5.2 looks not so good to eyes on mobile ..when we visit other Social giants and even the new competitors of Phpfox and comeback , it looks like a very basic thing which needs many improvements ..I hope 4.6 will be coming with these improvements

**Comment by neil96** [comment]
Dear @shashankguitarist ,

This feature is now available on phpFox 4.6.0.

Regards.
