### ISSUE TITLE
Clearing cache also clears all messages in core IM app? Please allow to exclude this.

### ISSUE THREAD

**Issue by Candrom87** [PHPfox-Official/phpfox-v4-feature-requests#387]
Clearing the cache via AdminCP also purges all user messages in the core IM app. 
Please add an option to exclude the deletion of IM messages while clearing cache.

**Comment by neil96** [comment]
Hi @Candrom87 ,

Please do not use the same redis instance for IM app and phpFox cache. In the same server, you can open many instance of redis.

Regards.
