### ISSUE TITLE
Better way of viewing images marked as mature content

### ISSUE THREAD

**Issue by Erick000** [PHPfox-Official/phpfox-v4-feature-requests#388]
:When adding Photos to the site, to have a required question/next to it. Does this image contain Mature Content? Options Yes/NO If the image is marked as Yes, then the image is hidden, and applies to the option on the account settings page. 

   On the account settings page to have a question:  would you like to view content on this site marked as Mature Content? Options Yes/NO. (IF Yes, then all images marked as mature content is now visible. If No, then images marked as mature content will be hidden from view for that user.)
![better photo](https://user-images.githubusercontent.com/29802466/27747240-3836f7a6-5d7f-11e7-801a-2cc456f0351b.png)

**Comment by neil96** [comment]
Hi @Erick000 ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
