### ISSUE TITLE
Enhancement for polls

### ISSUE THREAD

**Issue by shashankguitarist** [PHPfox-Official/phpfox-v4-feature-requests#391]
When we create a new poll, ideally the options to select from should appear along with the question on the news feed just like on facebook!..but first we need to go to poll page and then give answer which should not be the case! Poll results should also be visible in newsfeed

**Comment by harrison05** [comment]
Hi @shashankguitarist , It's a long time but I hope you still work with phpFox, we released the new version of Poll App and this feature was implemented. Please check

Regards.
