### ISSUE TITLE
Cannot poke friends in 4.5.2 ?

### ISSUE THREAD

**Issue by shashankguitarist** [PHPfox-Official/phpfox-v4-feature-requests#392]
After update , I can only see poke option in profiles , which are not in my friend list

**Comment by neil96** [comment]
Hi @shashankguitarist ,

This feature works normally in 4.5.2. If it does not work on your site, please [submit a ticket](https://clients.phpfox.com/submitticket.php) with your site information, so we can do an investigation and resolve your problem.

Regards.
