### ISSUE TITLE
Messages marked as read

### ISSUE THREAD

**Issue by Erick000** [PHPfox-Official/phpfox-v4-feature-requests#393]
messages: 
for when users send a message, the ability to see marked as read. this mean (If the message has been read) it will be marked as read.  

    in admincp to have a new setting under Message. 
       - For us to be able to set what usergroups can have this new feature.

**Comment by neil96** [comment]
Hi @Erick000 ,

We have feature "mark all as read". However, this feature does not add in notification. We added this on phpFox 4.6.0. We do not add this setting for this.

Regards.
