### ISSUE TITLE
Group Messaging

### ISSUE THREAD

**Issue by Erick000** [PHPfox-Official/phpfox-v4-feature-requests#395]
For a profile to be able to send a message to all friends at one time. 

   In admincp to have an new option for friends, of allowing Group Messages per usergroup.

**Comment by neil96** [comment]
Hi @Erick000 ,

Your suggestion `For a profile to be able to send a message to all friends at one time.`  is not good for a social network. It annoys  other uses and your email server might send thousand of emails in a short time.

We will put this suggestion `In admincp to have an new option for friends, of allowing Group Messages per usergroup.` in poll of features list and decide later. Thanks

Regards.

**Comment by Erick000** [comment]
well how about letting friends send a group message to users inboxes?

**Comment by neil96** [comment]
Hi @Erick000 ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
