### ISSUE TITLE
Better view for premium members 

### ISSUE THREAD

**Issue by Erick000** [PHPfox-Official/phpfox-v4-feature-requests#397]
For when members chooses  to upgrade there account, to get better view on high-lights on User browse, and profile reviews.  This will be give our upgraded members more attention, and making upgraded members stick out of all others.
![bgclive com](https://user-images.githubusercontent.com/29802466/27983049-6c4ccc48-6368-11e7-957c-9f0164530dd8.png)

**Comment by neil96** [comment]
Hi @Erick000 ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
