### ISSUE TITLE
credit system

### ISSUE THREAD

**Issue by Erick000** [PHPfox-Official/phpfox-v4-feature-requests#398]
:It would be cool if phpfox comes with with a credit system known as Gold, credits, or in site currency. 

  - Admins can create new gold packages, for users to buy
  -Admins can mange each users gold. (Add/subtract gold)

     Have a setting for Earning credits, gold::
  - We can award you credits by loging into your account per day, adding comments, or other. 
Actions | Price in credits
Daily login | 5
User join | 20
Add event | 5
Comment event | 1
Add blog posts | 3
Comment blogs | 1
Post in group forum | 3
Create group | 5
Comment group walll

Have a setting for using gold/spending gold..  
- Each feature on the site has its own value of what we want to charge per that feature. For example, if we wnat to charge you per message you send. Or for each, comment, or add photos. 
 - Actions | Price in credits
Write on comment wall | -5
Add photo | -10
Comment photo | -5
Send private message | -10
Add your profile to the Hot List | -20
Send virtual gifts | Edit
Continue mail dialog | -20
DISABLEContinue chat dialog | -20
![my dating site admin page 2](https://user-images.githubusercontent.com/29802466/27983338-f13d3d42-636e-11e7-9814-305772ea1da1.png)
![beyonce female 40 berkeley ca usa my dating site 1](https://user-images.githubusercontent.com/29802466/27983339-f2369bb2-636e-11e7-9e22-de3bb78d011d.png)

![my dating site admin page   ##3](https://user-images.githubusercontent.com/29802466/27983347-1755d5fc-636f-11e7-9e36-0d338e30284b.png)
![beyonce female 40 berkeley ca usa my dating site 3](https://user-images.githubusercontent.com/29802466/27983365-68ed7e42-636f-11e7-822e-c83c025704da.png)

**Comment by neil96** [comment]
Hi @Erick000 ,

These features are very similar with our activity points system.

Regards.
