### ISSUE TITLE
freezing Account 

### ISSUE THREAD

**Issue by Erick000** [PHPfox-Official/phpfox-v4-feature-requests#400]
offer  the option to FREEZE your account without deleting it.By freezing your account, it will not be visible to other members and you will not receive any messages until you unfreeze it. This option is better than deleting the account because it allows you to reactivate it if you choose to return. It also allows you to keep the same username when you return. If you choose to delete your account, your username will not be available for you to use in the future as all deleted accounts are permanently deleted and can not be reopened.

**Comment by starplan** [comment]
When someone deletes/freezes their account it could be available to undeleted/unfreeze for lets say 30 days by user simply logging in. Permanent deletion as far the user is concerned will occur after 30 days. The number of days set by admin.

**Comment by neil96** [comment]
Hi @Erick000 ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
