### ISSUE TITLE
Run ads though ad-blockers

### ISSUE THREAD

**Issue by Erick000** [PHPfox-Official/phpfox-v4-feature-requests#401]
I noticed some major sites, are still running- showing ads when we have ad-blocker enabled.  I think this would be a grate feature suggestion for phpfox sites as it will also help increase our revenue form ads. 
   - I know we can have the option of blocking access to people that use ad-blockers, but this can also make us loose members too. 
   - by you creating a feature where we can still run ads though ad-blockers will be awesome, and much better off for everyone, this will make all happy instead of making them disalbe there ad-blockers, or white listing us to view our site.

**Comment by neil96** [comment]
Hi @Erick000 ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
