### ISSUE TITLE
Smart Blocking

### ISSUE THREAD

**Issue by Erick000** [PHPfox-Official/phpfox-v4-feature-requests#403]
This would be a user preference:
Smart Blocking- Block users from your profile based on their Age, Position, Gender, Race, etc... gives you lots of power to say who can contact you, or view your profile. 
   
In admincp have a new setting for users to enable this feature per usergroup we want to allow.

**Comment by neil96** [comment]
Hi @Erick000 ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
