### ISSUE TITLE
premium users to turn off site ads

### ISSUE THREAD

**Issue by Erick000** [PHPfox-Official/phpfox-v4-feature-requests#405]
On account settings page to have another option for premium users to turn off site ads. this also gives us a new reason why members should upgrade. 
* This way, we dont have to disable ads to that whole usergroup, by giving upgrading member this option would be better. 

  In admincp to have an this option per usergroup.

**Comment by neil96** [comment]
Hi @Erick000 ,

This is a feature of [better ads app.](https://store.phpfox.com/product/1665/better-ads)

Regards.

**Comment by Erick000** [comment]
Yes, you have it where, we have to disable ads to that whole usergroup. IF we give the the option for that members , then we still can run ads to that usergroup.

**Comment by Erick000** [comment]
On better ads- new option this usergroup can remove ads? (optional) for that user?

**Comment by neil96** [comment]
Hi @Erick000 ,

We also have this user group setting `Should ads be shown to members of this user group?`. It will hide all ads for a specific user group.

Regards.
