### ISSUE TITLE
members can buy/gift membership for other users

### ISSUE THREAD

**Issue by Erick000** [PHPfox-Official/phpfox-v4-feature-requests#408]
I just came across this it would be nice to allow members to buy membership for members. Or the ability to Gift membership 
![bgclive com 1](https://user-images.githubusercontent.com/29802466/28101185-9f58ac54-667b-11e7-96fa-3fccae23ceb6.png)

**Comment by Erick000** [comment]
In Egift, the ability to gift membership, on profile pages, the ability to buy membership for that user? Or just how ever you wanna do it :+1:

**Comment by neil96** [comment]
Hi @Erick000 ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
