### ISSUE TITLE
Replace Core-Dash with:

### ISSUE THREAD

**Issue by Erick000** [PHPfox-Official/phpfox-v4-feature-requests#410]
**I noticed the Core-dash.html file is is outdated.** 
![b6d8a4f0-9354-416e-5dde-d22c35af9077](https://user-images.githubusercontent.com/29802466/28103132-130a22b0-6689-11e7-953d-c072996ef5df.png)

   **How about replacing core-dash.html for a more dashboard look?** 
![202acb02-2dae-4a4e-780a-54c58dd8e4bf](https://user-images.githubusercontent.com/29802466/28136512-d4a2d5f0-66fe-11e7-9027-5ea6868a1294.png)
![7094a535-dd59-4667-7bff-d9ef85df9293](https://user-images.githubusercontent.com/29802466/28136520-db1831f0-66fe-11e7-9433-355606e6cbf3.png)
![19social com](https://user-images.githubusercontent.com/29802466/28136540-e5e59dca-66fe-11e7-9924-be6651e2babc.png)

**Comment by neil96** [comment]
Hi @Erick000 ,

phpFox v4 does not have a feature such that.

Regards.

**Comment by Erick000** [comment]
I know yall dont have a feature such as this, thats why i'm suggesting it, for a more feel,and looks of a dashboard.

**Comment by neil96** [comment]
Hi @Erick000 ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
