### ISSUE TITLE
new feed block type

### ISSUE THREAD

**Issue by Erick000** [PHPfox-Official/phpfox-v4-feature-requests#411]
i've been trying to display Activity Feeds in a page, as i would like to reserve my Home- dashboard for other content, instead of just showing all user-feeds.. I've noticed theirs no other way for us to do this.

   How about creating another block type  for display for feeds, where we can click on a link, and the Activity feeds Popup/or pop out. 
    
   Or create a page just for the Activity feed. yoursite.com/userfeeds

**Comment by neil96** [comment]
Hi @Erick000 ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
