### ISSUE TITLE
Improve currency settings

### ISSUE THREAD

**Issue by ESA55** [PHPfox-Official/phpfox-v4-feature-requests#412]
The currencies of different countries are written differently from the option available in phpfox. Offer writing options with dots to mark thousands, commas to cents and symbols with 2 letters (R$, for example). It would be great to offer the payment redirection option to the paypal site of the respective country.

https://community.phpfox.com/forum/thread/56370/improve-currencies-settings/

**Comment by ESA55** [comment]
The feature is not working properly. The price field shows the default "0.00" and does not accept 0,00 for the Brazilian currency, for example

**Comment by neil96** [comment]
Hi @ESA55 ,

On 4.6.0, you can add any type of currency by this rule: 

> Add a format to show of this currency. Please add format with some rules:
> {0} mean currency symbol ($, €, ...)
> {1} mean currency id (USD, EUR,...)
> Decimal point and thousand separator (#,###.00 ...)
> Example, format is: {0} #,###.00 {1} , and price show: $ 1,000.00 USD

Do you test on 4.6.0beta1?

Regards.

**Comment by ESA55** [comment]
Hi @neil96,

Yes, I created the brazilian currency with the new format in version 4.6.0beta1. I can not type 1.000,00 in price field (narketplace).
![currency](https://user-images.githubusercontent.com/13573330/34040748-40e8a4b8-e17c-11e7-8b71-24e47df6e21d.jpg)
![currency1](https://user-images.githubusercontent.com/13573330/34040749-417f2a5a-e17c-11e7-8a83-bef8498d7abb.jpg)

Thanks

**Comment by neil96** [comment]
Hi @ESA55 ,

For now, we only support format current at view. The input field follow number format rule. We can consider adding this feature in next versions if you post another request.

Thanks!

**Comment by ESA55** [comment]
Hi @neil96 ,

I opened a new request. https://github.com/PHPfox-Official/phpfox-v4-issues/issues/2082

Thanks a lot
