### ISSUE TITLE
control shortcuts/menus in AdminCP

### ISSUE THREAD

**Issue by shashankguitarist** [PHPfox-Official/phpfox-v4-feature-requests#413]
every admin will need the ability to add/remove some links/shortcuts like , "Create a Page" ,"Upload a Video" , "Upgrade your account" , " Items in your cart" etc HERE http://prntscr.com/fv8ppb .
It should be a core feature , please consider this and implement in the core code or as an app asap

**Comment by shashankguitarist** [comment]
Please implement this in 4.6  ...I dont see memberships,last logins, login as a page on desktop version ...having difficulty.

**Comment by neil96** [comment]
#99
