### ISSUE TITLE
Update Services Integration Like Pingomatic

### ISSUE THREAD

**Issue by Elshara** [PHPfox-Official/phpfox-v4-feature-requests#415]
Update services are services such as pingomatic which allow rpc pings using xml templates to notify search engines and directories when new content is added to a site. Used by word press and several other blogging platforms successfully for years such as Ning 2.0, every time activity is posted, you have the option of notifying site update services when you share something new. This allows search engines to immediately be linked to the article of choice as soon as you publish or schedule an update. Doing so directly allows the page itself when ever it is created, updated or removed, to immediately be added to an indexing queue. This usually happens fairly quickly as the pings to different site services at once, allow the article to be discoverable by them.

This leads to instant traffic as the page gets not only indexed, but also remain in the index as new pings happen based on the frequency of new activity on your site. This is why viral content along with site maps of your site and rss feeds along with email subscriptions of new content, allow both search engines and people to stay updated with the news and latest posts, pages and people who visit you.

Ping services are not considered spammy unless they ping too often, or duplicate content is found on pages which haven't changed much. For instance, just pinging the home page when new updates happen, will only work if the home page displays the most recent changes such as the activity feed. But pinging the actual page or setting what pages get pinged when the update occurs, will fix this and always keep search engines and new perspective visitors coming back. This works in tandem with good search engine optimization.

This service is free and always will be. If you wish to include it.

**Comment by neil96** [comment]
Hi @Elshara ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
