### ISSUE TITLE
Allow users to create site email

### ISSUE THREAD

**Issue by Erick000** [PHPfox-Official/phpfox-v4-feature-requests#416]
I came across this today, it could be  good suggestion allow members to have another email, allow them to create an on site email address chooseemail@yoursite.com.

   in admincp have a new setting for us to enable this per usergroup. 
  
![image](https://user-images.githubusercontent.com/29802466/28253496-75ff9020-6a59-11e7-989d-2d99daebfa6b.png)

**Comment by neil96** [comment]
Hi @Erick000 

Do you mean "site.com" is your own site?

Regards.

**Comment by Erick000** [comment]
NO. "Site.com" was just a suggestion. We could allow members to create their own email address for our site.

**Comment by neil96** [comment]
Hi @Erick000 ,

This feature can't be done with php language.

Regards.
