### ISSUE TITLE
Allow signup via google

### ISSUE THREAD

**Issue by Erick000** [PHPfox-Official/phpfox-v4-feature-requests#417]
in addition to join with facebook, how about joining with your google account.

**Comment by dawn2323** [comment]
Yes needed!!

**Comment by spirogg** [comment]
hello @harrison05 did you guys implement this already ? I did not see it

**Comment by harrison05** [comment]
Signup via Google is now available on phpFox v4.8.4.
Admin can enable it at AdminCP > Settings > Registration Settings.

Regards.
