### ISSUE TITLE
GIF profile pics

### ISSUE THREAD

**Issue by Erick000** [PHPfox-Official/phpfox-v4-feature-requests#418]
i noticed we can allow members to upload a gif as a profile picture, but when members do have a GIF, the main profile image dont move like it should, its just stationary.  
     - On profile pages, and user browse, gif images should move like it should. 
    - On the photos page, the gif images move, just not on Main photo.

**Comment by neil96** [comment]
Hi @Erick000 ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
