### ISSUE TITLE
Limitations 

### ISSUE THREAD

**Issue by Erick000** [PHPfox-Official/phpfox-v4-feature-requests#419]
I noticed, we have account storage limit, but we do not have any limitations on how many photos, videos a user can upload in total.  
   - What if we wanted to allow members to upload just a certain  amount of photos, and upgrade to have more. 
- some dating sites, match.com, pof, have a photo limit a user is allowed to upload.

**Comment by neil96** [comment]
Hi @Erick000 ,

FYI, On 4.6.0, we limit total disk space user can upload.

Regards.

**Comment by neil96** [comment]
Hi @Erick000 ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
