### ISSUE TITLE
Rating system: Part 2

### ISSUE THREAD

**Issue by Erick000** [PHPfox-Official/phpfox-v4-feature-requests#421]
This is an AUTOMATIC list of the top 50 on the site that has the highest ratings and have at least 2 different public images with at least 25 reviews and rated by at least 25 different members. Your account must also be active for at least 1 month.

![image](https://user-images.githubusercontent.com/29802466/28282675-1d26e070-6ae0-11e7-86d0-aaf99f86662a.png)

**Comment by neil96** [comment]
Hi @Erick000 ,

This feature is very specific to a site, and we do not have feature rating now.

Regards.
