### ISSUE TITLE
Db Soft delete option

### ISSUE THREAD

**Issue by SalmanKhan86** [PHPfox-Official/phpfox-v4-feature-requests#423]
Option needed so that we can enabled soft db delete . There is boolean filed needed in db so that whenever any feed deleted its becomes true and items not shown on website.later on if we want to enabled we can change its status.

**Comment by neil96** [comment]
Hi @SalmanKhan86 ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
