### ISSUE TITLE
friend broadcast 

### ISSUE THREAD

**Issue by Erick000** [PHPfox-Official/phpfox-v4-feature-requests#425]
Allow a user to be able to send a message to all friends inboxes on site at one time.. 
- IF they have something they want to say, no need of sending a message one by one, or selecting friends to send too. this is much faster and also gives the user  quicker responses.
 
   in admincp have a new setting for us to allow this per usergroup. If we want to give it free, or premium users.

**Comment by neil96** [comment]
Hi @Erick000 ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.

**Comment by kirkkhua** [comment]
There is a product like this that allows to broadcast messages from AdminCP: [Message Broadcasting for phpFox](https://store.phpfox.com/product/1953/message-broadcasting/)
