### ISSUE TITLE
Feed filter 

### ISSUE THREAD

**Issue by Erick000** [PHPfox-Official/phpfox-v4-feature-requests#426]
When members view feeds, to be able to have a feed filter, so that user will able to see exactly what they wanna see.  
    Feed filter included browsing feeds based on gender, age, country, State OR city.
    ![10 tagged home](https://user-images.githubusercontent.com/29802466/28397487-ce1a081c-6cb6-11e7-9e42-fa9f40b9e8f0.png)

**Comment by neil96** [comment]
Hi @Erick000 ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
