### ISSUE TITLE
please consider this in multistep registration and custom fields enhancements

### ISSUE THREAD

**Issue by shashankguitarist** [PHPfox-Official/phpfox-v4-feature-requests#427]
This is a core feature of the competitors, i had to spend so much on my phpfox site to get the same thing, but still, could not attain the reliable functionality ...please consider this in 4.6 ..
http://support.socialengine.com/php/customer/portal/articles/1644307-admin-panel---settings-&gt;-profile-questions

**Comment by neil96** [comment]
Dear @shashankguitarist ,

This feature is now available on phpFox 4.6.0.

Regards.
