### ISSUE TITLE
adding field type to custom fields

### ISSUE THREAD

**Issue by shashankguitarist** [PHPfox-Official/phpfox-v4-feature-requests#428]
adding more field types to custom fields like "Document Upload (pdf,jpg, etc ) will solve the problem of verifying Unique member at signup , and adding more field types such as "video,youtube link etc" will serve my and many other members requirements..PLEASE IMPLEMENT i 4.6

**Comment by neil96** [comment]
Hi @shashankguitarist ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
