### ISSUE TITLE
Profile fields: Text areas

### ISSUE THREAD

**Issue by JOJOA1** [PHPfox-Official/phpfox-v4-feature-requests#433]
On some sites like match.com, and a lot of other dating sites, they want to review profile changes , so make sure that user profiles also comply with there terms of service, or policy's . Some users really actually put way to much info or  including: offsite links, phone numbers, contact email addresses, real names, spam material, advertising material, and other. By us having an option to review profile changes, can cut-out most of these issues. 
Options:
  -   Approve, or Reject Profile changes to text areas. 

   (scenario) On our sites, we have the option of allowing users to send messages or not, what whats the purpose  of that when the users can just add anything they want to their profile fields. "Oh yea i cant send messages on here, but here is  my number, and my facebook info, contact me there. "

![image](https://user-images.githubusercontent.com/30337528/28483668-4eec3e7a-6e23-11e7-9c08-06b627968814.png)

**Comment by neil96** [comment]
Hi @JOJOA1 ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
