### ISSUE TITLE
Visit Notify

### ISSUE THREAD

**Issue by JOJOA1** [PHPfox-Official/phpfox-v4-feature-requests#434]
Adds a new alert when you have a new profile view. 
![image](https://user-images.githubusercontent.com/30337528/28488999-810a2d56-6e6c-11e7-8296-c8eacec294f2.png)
![image](https://user-images.githubusercontent.com/30337528/28489006-ae77e058-6e6c-11e7-9529-b2de551ef983.png)

**Comment by dawn2323** [comment]
Good one

**Comment by neil96** [comment]
Hi  @JOJOA1 ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
