### ISSUE TITLE
Better Profile Viewers List 

### ISSUE THREAD

**Issue by JOJOA1** [PHPfox-Official/phpfox-v4-feature-requests#435]
You only have  block of 4-5 people that viewed your profile. We need a page of profile visitors. 

![image](https://user-images.githubusercontent.com/30337528/28488954-557971b6-6e6b-11e7-81f8-c3c4b40ee0b8.png)

**Comment by dawn2323** [comment]
Nice. Will be fun!

**Comment by neil96** [comment]
Hi @JOJOA1 ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
