### ISSUE TITLE
AUDIO COMMENTS 

### ISSUE THREAD

**Issue by Erick000** [PHPfox-Official/phpfox-v4-feature-requests#436]
The ability for users to leave comments by audio (microphone) 
 -  Audio comments gives your site members a unique opportunity, an audio recording of voice, and placing it in site's comments or in chat like in the "whatsUp".
Now you do not need to spend a lot of time typing text comments, just write down your thoughts using the microphone.

- IF this is a good suggestion, in Admincp have this option per usergroup we want to allow to use this. 
  
![image](https://user-images.githubusercontent.com/29802466/28489115-47fb4a38-6e6f-11e7-892f-af4ad8a5a3f8.png)

**Comment by dawn2323** [comment]
Seems Cool!

**Comment by neil96** [comment]
Hi @Erick000 ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
