### ISSUE TITLE
Share reading, watching, earning activity points based on your liking

### ISSUE THREAD

**Issue by Promastertr** [PHPfox-Official/phpfox-v4-feature-requests#437]
To ensure that members are more active on the Site, they should be allowed to earn Activity Points as they are viewed, read, and watched as they are shared. In this Sayede Members will spend Effort to get liked, read or watched. It will make quality Shares.

**Comment by dawn2323** [comment]
Nice

**Comment by neil96** [comment]
Hi @Promastertr ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
