### ISSUE TITLE
Easy Pic access 

### ISSUE THREAD

**Issue by Erick000** [PHPfox-Official/phpfox-v4-feature-requests#438]
If you have a custom friends list - With custom Albums, when you visit another persons profile page, you can give them access to your custom album directly form the profile pages (This is known as unlocking your private pics). 
*This works better then going back to manage friends lists, and having to find/search for that friend you want to give access to add to the list. 
![image](https://user-images.githubusercontent.com/29802466/28495630-4a292fba-6f09-11e7-9082-d3fd64180dd7.png)

**Comment by neil96** [comment]
Hi @Erick000 ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
