### ISSUE TITLE
Recent Premium Members block

### ISSUE THREAD

**Issue by JOJOA1** [PHPfox-Official/phpfox-v4-feature-requests#439]
For the members that have upgraded recently for us to have a block to display them in to encouraged others to upgrade too.
    - When we add/edit membership packages, allow a selection where we can check mark.. If checked members in that membership will appear in this new block. 
   Or if you see another way of doing it :+1: 
![image](https://user-images.githubusercontent.com/30337528/28497078-ffdad70a-6f31-11e7-85f4-06b97fc74e91.png)
![image](https://user-images.githubusercontent.com/30337528/28497092-5a507708-6f32-11e7-9a85-9a73e88560bb.png)

**Comment by dawn2323** [comment]
Good One!

**Comment by Scheinwelt-Media** [comment]
maybe this is something for you? https://store.phpfox.com/product/1944/subscribers

**Comment by neil96** [comment]
Hi @JOJOA1 ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
