### ISSUE TITLE
Make Better ads BETTER

### ISSUE THREAD

**Issue by foxophile** [PHPfox-Official/phpfox-v4-feature-requests#442]
Ad space monetization requires flexibility. Limiting Better Ads to 237X160px severely limits the value of the application. Since promoting "Better Ads" as one of the buyup motivations for the Pro Version it should have true value to the customer. Most sites that monetize based on sold ad placements need/use a flexible ad layout as the ad size is directly related to ad cost/revenue.

**Comment by heebeha** [comment]
Remove ads from the homepage/landing page for visitors.  They throw off the page big time
