### ISSUE TITLE
Monthly calendar on the events page...

### ISSUE THREAD

**Issue by starplan** [PHPfox-Official/phpfox-v4-feature-requests#444]
Could you add a calendar to the Events page/s so that a visitor can view events on a particular day. For example, clicking on todays date would show you all the events happening today. You could maybe add a checkbox that would filter out events that have already started. For days clicked on in the future the checkbox would not be visible. 

I forgot to add, that a date range would be nice too. For example, if you wanted to view the events that were happening over the weekend, you could click on Saturday and Sunday. I guess that would take two calendars, one for the first day and a second for the last day.

**Comment by dawn2323** [comment]
Nicee!
