### ISSUE TITLE
Ideas for viewing photos

### ISSUE THREAD

**Issue by ancelsan** [PHPfox-Official/phpfox-v4-feature-requests#446]
There are two features that users of my site ask for in relation to photos:

_ One of them is that the photo was viewed without needing to be directed to another page as it is currently. They ask that the image be viewed in a superimposed screen on the page that is the image, similarly to Facebook.

_ Another feature they ask is that the photos be displayed on the instagram-sized photos page, in full size, one below the other, as in a feed.

**Comment by neil96** [comment]
#115
