### ISSUE TITLE
Public Internet Relay Chat Client Platform

### ISSUE THREAD

**Issue by dawn2323** [PHPfox-Official/phpfox-v4-feature-requests#447]
Internet Relay Chat client which can be used by individuals and organizations to communicate, share, play and work with each other even if they are not friends.

This feature will make people keep coming back to use this feature and other features can also get more mileage. Individuals and Organizations can create their own Chat Rooms and we can have multiple Roles like Owner of Chat Room, Moderators etc having different powers like to Kick a person out, take polls or assign smaller powers to members etc. Each Room Name should be Registered which will be Unique(Ex: Premium Members only can create) and even Each Nick Name should be Registered - Again Unique names.

If this Idea is liked by all, I can help you get more ideas on this concept. This I assure you will be an amazing feature which will keep the traffic active and also give loads of promotion and revenue options! It will also make people give and send offers On the Go! Also it will make any current event or an ongoing event more fun like a Soccer Match or a Cricket match etc. Huge scope and potential. 
Imagine you are inside a shopping mall, and you join the Mall Official Room Chat, You may get on the spot offers and info on all promotions. There is unlimited potential with this if we get it right. Please do give your comments and suggestions. Thanks!

![channels](https://user-images.githubusercontent.com/29255464/29747953-9a9ab41a-8b28-11e7-9bd7-a655fdca8574.png)
![ircchat 1](https://user-images.githubusercontent.com/29255464/29747955-a50775dc-8b28-11e7-9163-6e3e82515852.png)
![join-room](https://user-images.githubusercontent.com/29255464/29747956-a9953da0-8b28-11e7-9dd9-f489ddf7c1fa.jpg)
![chat-room](https://user-images.githubusercontent.com/29255464/29748006-d2b35e1e-8b29-11e7-87ba-db5a72097f51.png)

**Comment by neil96** [comment]
Hi @dawn2323 ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.

**Comment by dawn2323** [comment]
So does it mean this feature will never be implemented?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by neil96** [comment]
Currently, we do not have plan to implement for this feature. However, in the future, our plan can change and this feature might be implemented.
Regards.
