### ISSUE TITLE
support CKEditor for blocks

### ISSUE THREAD

**Issue by erick260** [PHPfox-Official/phpfox-v4-feature-requests#448]
We should already have support for CKEditor with  blocks. With this when adding blocks, we can make the content the way we want. 

   
![newtest](https://user-images.githubusercontent.com/19263189/29941136-5cea09ba-8e46-11e7-9ea4-3a2021a4782d.jpg)

**Comment by neil96** [comment]
Thanks @erick260 ,

We can't use CKEditor for this field. This is php/html code, it isn't document text.

Regards.
