### ISSUE TITLE
Visitor Home Page on Mobile needs a visible Login option

### ISSUE THREAD

**Issue by darksolar1** [PHPfox-Official/phpfox-v4-feature-requests#45]
On the visitor home page on the mobile phone, the visitor is presented register form and no visible login option. Most people will not know to click on upper right square with the 3 dashes to bring up the login option.

**Comment by GreenMan123** [comment]
Yes

**Comment by neil96** [comment]
Dear @darksolar1 ,

This feature is now available on phpFox 4.6.0.

Regards.
