### ISSUE TITLE
usergroup in profile icon

### ISSUE THREAD

**Issue by erick260** [PHPfox-Official/phpfox-v4-feature-requests#451]
When we add/Edit usergroups,  allow usergroups to be displayed in profile photo icon. This is a better way of making the member stand out! everyone will know what usergroup there in. 

![usergroup](https://user-images.githubusercontent.com/19263189/29943630-0bcbcad8-8e4f-11e7-8296-34484c801b5f.png)
![lable](https://user-images.githubusercontent.com/19263189/29943633-0fdf6b7a-8e4f-11e7-865d-a9c2fdfebfb3.png)

**Comment by dawn2323** [comment]
Nice one!

**Comment by kirkkhua** [comment]
There is a very similar app in phpFox store: [User Group Icon for phpFox](https://store.phpfox.com/product/1662/user-group-icon)
