### ISSUE TITLE
Leaderboard for Activity Based Points

### ISSUE THREAD

**Issue by dawn2323** [PHPfox-Official/phpfox-v4-feature-requests#452]
Keeping a Leaderboard for Activity Based Points will make it fun and will make users to be more active and will make the website more dynamic. Leaderboard with sorting options like All time, Yearly, Monthly, Daily, or specific criteria wise - Like, Photos, Polls, Reviews, Sharing etc.. Also if the user doesn't want their name to appear then they could opt for Anonymous. We can also have Leaderboard based on Membership level too!

**Comment by dawn2323** [comment]
Thanks :-)

**Comment by neil96** [comment]
Hi ,

Thanks for your suggestion. But currently it does not map with our plan.

Regards.
