### ISSUE TITLE
Badge Achievements Unlocked

### ISSUE THREAD

**Issue by dawn2323** [PHPfox-Official/phpfox-v4-feature-requests#453]
I am aware of Badge Add on. Thought could add more badges like like 30 days login in a row, 100 days, 365 days, 50/100/500/1000 friends, Activity Points Badge 100/1000/10000 etc... Activity based on specific criteria like Photos upload 500 Points and other similar badges. It will be fun too and will surely keep the patrons more active. Badges can be shown in one of the sections of their profile page. Badge achievement sharing could also be incorporated to be put on their wall or other social networks. Also in addition mutual badge achievements between your friend or multiple friends could be done as comparison which will be so much fun. (Ex: What are the common badges they share and what is unique for each friend).

**Comment by kirkkhua** [comment]
There is a badge app for phpFox: [Advanced Badges for phpFox](https://store.phpfox.com/product/1874/advanced-badges)
