### ISSUE TITLE
Auto-Unique Code Generator for links

### ISSUE THREAD

**Issue by dawn2323** [PHPfox-Official/phpfox-v4-feature-requests#455]
Auto-Unique Code Generator for links - We find at times tough to find our friends profile page or any specific link or event page etc as there may be similar content or we may be using a wrong search name. What if there is an auto generated unique code for each link like Profile Page, Business page or even links for specific events, blog headings, polls etc. Unique code could be DFCA95362 or something like tat which will be random and not in any continuous order. So search by code option they could enter the above code and find the link straight away. It will be easy for us to share such codes with friends and community and it will be easy for them to locate the specific link. Just a suggestion. It would make things really simple and also make it easier for stakeholders to promote whatever they want to.

**Comment by dawn2323** [comment]
Thanks!

**Comment by neil96** [comment]
Hi @dawn2323 ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
