### ISSUE TITLE
Allow only admin to add HTML code to certain user pages or groups in various blocks

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-feature-requests#456]
It would be really nice if phpfox site owner/admins can insert html codes into various blocks of  certain user pages or groups.

For example a user creates a group or a page, but need extends the function for their specific page. The site admin, can then insert some html  into certain blocks or widgets.  

..or users can select from various pre-made widgets or custom widgets for a fee which can be paid either with points , currency or subscription. and which they can move around or insert the widget into one or more blocks of their page. This will allow users to customize their pages to a certain extent while without allowing users to introduce any malicious code.

The possibilities are endless.. This gives the site owner another way of generating revenues from value added services.

**Comment by neil96** [comment]
Hi @prepperz ,

phpFox 4.6.0 allow adding html for this block via CKEditor.

Regards.
