### ISSUE TITLE
Add search field and options to all pages of apps.

### ISSUE THREAD

**Issue by starplan** [PHPfox-Official/phpfox-v4-feature-requests#458]
I would like to see the search field that appears at the top of the blog, video, markets home pages etc on all pages of the blogs, videos, markets etc. There would then be no need to go to the home page of the app in order to search.

**Comment by dawn2323** [comment]
Nice n simple Yes!

**Comment by neil96** [comment]
Hi @starplan ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
