### ISSUE TITLE
News Feed & CKEditor

### ISSUE THREAD

**Issue by juniortimeline** [PHPfox-Official/phpfox-v4-feature-requests#462]
Hi, I think this is better looks and professional way.

If some one create a blog, music, events, and more app that support ckeditor. I suggest to change the function of "read more" instead to view the whole text on news feed, better to go directly to the page of blog, music, etc that user post after they click the "read more"

**Comment by dawn2323** [comment]
Yes reduces unwanted space wastage

**Comment by neil96** [comment]
hi @juniortimeline 

This feature is now available on phpFox 4.6.0.

Regards.
