### ISSUE TITLE
Limitations on Pages, and groups Vanity url:

### ISSUE THREAD

**Issue by JOJOA1** [PHPfox-Official/phpfox-v4-feature-requests#463]
it would be nice to allow limitations on user created pages, and groups Vanity url. Allowing free users to set them. Once they have been set, it cannot be changed. The only way it can be changed is to upgrade your account. 
* Can this usergroup change urls? If so How many times, 0 for unlimited. 
![image](https://user-images.githubusercontent.com/30337528/30672426-2bc45314-9e21-11e7-9173-b2d13505a9c5.png)

**Comment by starplan** [comment]
Good idea, this would prevent users from cyber squatting. Setting criteria for being able to have a vanity URL like Facebook, Youtube etc would show that the website cares.

**Comment by dawn2323** [comment]
Nice!

**Comment by neil96** [comment]
Hi @JOJOA1 ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
