### ISSUE TITLE
Pull Video Info from YouTube In Timeline

### ISSUE THREAD

**Issue by PENTAGON4** [PHPfox-Official/phpfox-v4-feature-requests#464]
The old version of PHPFox would pill a thumbnail and the video info/comments when you pasted a YouTube link in the timeline or Videos section. I'd like to see that again.

**Comment by neil96** [comment]
Hi @PENTAGON4 ,

This issue is reported here PHPfox-Official/phpfox-v4-issues#2010

Regards.
