### ISSUE TITLE
Sponsored Items does not appear when scrolling 

### ISSUE THREAD

**Issue by erick260** [PHPfox-Official/phpfox-v4-feature-requests#467]
I've noticed when you sponsored items in feed, it only appears at the TOP of the feed, and does not  Re-appear back when scrolling down, (Like on Facebook.) Sponsored items should reappear in feed when scrolling.

**Comment by erick260** [comment]
Sponsored item only appear at the top. it would be nice to have them in sight when the page keeps scrolling.  When the Page scrolls down, so does the Sponsored Items.

**Comment by david-phpFox** [comment]
We implemented it in the newest version.
