### ISSUE TITLE
Slack like features in Pages and Groups

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-feature-requests#469]
Having Slack like features on the pages and groups would really create a big opportunity for phpfox. Collaboration tools like slack would greatly compliment the usefulness of a phpfox site.

**Comment by neil96** [comment]
Hi @prepperz ,

Could you explain more detail about "**Slack like features**".

Thanks!

**Comment by prepperz** [comment]
Like: https://slack.com/

**Comment by neil96** [comment]
Hi @prepperz ,

Please describe your request detail here.

Regards.
