### ISSUE TITLE
Purchase with Points

### ISSUE THREAD

**Issue by Rodios** [PHPfox-Official/phpfox-v4-feature-requests#471]
Hi, I have enable user can Purchase with Points.
If a user sale a product on Marketplace, and another user bye this product with points, i wonder why the points do not go to the seller???
And what happen with this points????
I use the default phpFox Marketplace and the point system that include with phpfox Neutron...

**Comment by neil96** [comment]
Hi @Rodios  ,

On phpFox 4.6.0, these points will go to seller account.

Regards.
