### ISSUE TITLE
Blood Group Feature for each Profile

### ISSUE THREAD

**Issue by dawn2323** [PHPfox-Official/phpfox-v4-feature-requests#472]
Can we add a BLOOD GROUP FEATURE - so that each user can state their blood group during registration. May be in time of emergency a group message could be shot for a specific blood category if anyone is interested to donate blood within a particular area or region. This could be really helpful and save lives. Also this feature will be very beneficial to the society.

**Comment by erick260** [comment]
This sounds like it can be done in profile Questions?

**Comment by Scheinwelt-Media** [comment]
this can be done with custom fields allready implemented in the core script.

**Comment by dawn2323** [comment]
Cool Thanks :-)

**Comment by neil96** [comment]
Hi All,

Thanks for your contribution. We will consider adding this feature to version 4.7.0. Thanks.

Regards.

**Comment by dawn2323** [comment]
Thank you :-)

**Comment by neil96** [comment]
Hi @dawn2323 ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.

**Comment by neil96** [comment]
Currently, we do not have plan to implement for this feature. However, in the future, our plan can change and this feature might be implemented.
Regards.
