### ISSUE TITLE
Unavailable vanity URL listing in admin

### ISSUE THREAD

**Issue by starplan** [PHPfox-Official/phpfox-v4-feature-requests#473]
I would like to see the ability for admin to paste a list of vanity URLs that cannot be used, for example. You could have in a list the word "insurance", no member would then be able to have the vanity URL http://www.yourwebsite.com/insurance. These could then be premium URLs or banned URLs.

**Comment by dawn2323** [comment]
Nice one! these premium URL can be sold or auctioned too!
