### ISSUE TITLE
Daily Spins 

### ISSUE THREAD

**Issue by erick260** [PHPfox-Official/phpfox-v4-feature-requests#474]
WE need something for users to keep coming back to our sites. how about adding Daily spins, each day you log in, you can get a chance to SPIN the wheel for prizes. Some prizes will be harder to hit. 
The Prizes can be:  *
*A set number of activity points awarded. (Known as Jackpot amount))
*A membership for a day.  (Get upgraded to a new membership for  day. )
*  or just more spins. 

  To Spin Wheel extra times, requires a set number of activity points. 
 
![image](https://user-images.githubusercontent.com/19263189/31511694-61a4e0a2-af3d-11e7-9c7f-42ca9d9ea61c.png)

**Comment by dawn2323** [comment]
Yes! Good suggestion! It will make them come back daily! default points should be like nominal!
