### ISSUE TITLE
Can create vanity URL option in admin

### ISSUE THREAD

**Issue by starplan** [PHPfox-Official/phpfox-v4-feature-requests#475]
Could you add an option in Admin>User Groups>Manage User Settings for groups, pages etc that would disallow or allow that group to create vanity URLs.

I guess this would be a case of making the URL tab unavailable to the relevant user group. It would be great if you could add this feature to 4.6? :)

**Comment by neil96** [comment]
Hi @starplan ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
