### ISSUE TITLE
Activity points cost per Action 

### ISSUE THREAD

**Issue by erick260** [PHPfox-Official/phpfox-v4-feature-requests#477]
I wish we can sell our sites features with memberships, or activity points. In Addition to earning points, but it also be set a cost to: send a message, add a blogs, photo, forms post, music, and other modules IF you do not have a membership, each module has its own cost per action using activity points.
 ("IF enabled per module: This feature/module requires the member to have a membership,  or buy it using points... Members that have paid for a membership do not need to buy with  points. Buying with point is only for the Free Users option. ")

The more active you are on the site, the more points you'll get to do other things.

**Comment by neil96** [comment]
Hi @erick260 ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
