### ISSUE TITLE
Better Ads-HTML

### ISSUE THREAD

**Issue by erick260** [PHPfox-Official/phpfox-v4-feature-requests#480]
i noticed you offer ads to be created as HTML type... but we cannot place an ad code in there. I'm still placing my google ads in a block location due to this. Please allow better ads to also  post Ads HTML code.

**Comment by erick260** [comment]
WE should have another ads type where we can just post ad code.

**Comment by neil96** [comment]
Hi @erick260 ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
