### ISSUE TITLE
Allow CKEditor for profile fields-Text areas

### ISSUE THREAD

**Issue by erick260** [PHPfox-Official/phpfox-v4-feature-requests#481]
it would look much better if we allowed users to use the CKEditor for there profile fields-Large Text areas.

**Comment by neil96** [comment]
Hi @erick260 ,

Could you give us detail example.

Regards.

**Comment by erick260** [comment]
Sure, when a member goes to edit there profile, they can use this editor when filling out there profile info when it comes to large text areas. It will be a lot easier to add images, text color, make text bold, underlined or highlighted,or changing the font size.

**Comment by neil96** [comment]
Hi @erick260 ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
