### ISSUE TITLE
Custom locations 

### ISSUE THREAD

**Issue by Lukey199223** [PHPfox-Official/phpfox-v4-feature-requests#483]
We need the option to add a custom location to status updates instead of just checking in , in one of the locations that actually exist, we need upgrades to these features to not get left behind by other networks , 

Eg : "Me, Mam and Dad are all chilling at the Jones Household

**Comment by neil96** [comment]
Hi @Lukey199223 ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
