### ISSUE TITLE
Allow Developers to edit core files

### ISSUE THREAD

**Issue by Lukey199223** [PHPfox-Official/phpfox-v4-feature-requests#484]
To allow developers to edit the core files without breaking their websites, i think this would be useful to further allowing phpfox site creators to make their website more unique, but most importantly, I think it would give developers more power when creating apps that work along side the core phpfox features :) , to be able to manipulate the core features into doing what the developers want them to do, i think this will allow them to create more powerful apps :)

**Comment by neil96** [comment]
Hi @Lukey199223 ,

We currently support plugins and events for 3rd party developers to add code to core. This feature is used by many developers.

We do not allow edit core files because this can cause other apps to not work or kill the site.

Regards.
