### ISSUE TITLE
Bingo Game for Members

### ISSUE THREAD

**Issue by dawn2323** [PHPfox-Official/phpfox-v4-feature-requests#487]
Can we create a Bingo Game (90 nos) - Add on app? It will be really a fun loving activity for all the users of our social networking website - where each user get an electronically generated random Bingo ticket or Tickets to play the game. The Bingo game will randomly call out numbers and only users who have logged into that page at that time can play the game. They just need to watch the numbers been called out and their electronic ticket will automatically detect if the number matches with their tickets. 

The admins of the site can create the Bingo Game timings in advance or on a particular day. There is a huge scope to generate revenue via ads as well as prize sponsorship's etc.  

Scope of Revenue & benefits:

a) Ads on the page
b) Ads between the number been called out
c) Prize Sponsorship's
d) Ticket Price or Corporate Ticket Sponsorship(Where Business houses buy and share to employees or customers).
e) Fun & Entertainment
f) More traffic for the Social Network
g) Referring friends to play can get them as well as their friends Free Tickets etc,,, (More Traffic with personal pull) and many more benefits!

**Comment by neil96** [comment]
Hi @dawn2323 ,

Thanks for your idea. This idea is great for developers to make a 3rd-party app. So we mark the label as "Third Party Dev" for all developers to see.

Currently, our store has an app with features that closely resemble your idea. You can refer to [here](https://store.phpfox.com/product/1281/lottery).

Regards.
