### ISSUE TITLE
Drag and Drop blocks 

### ISSUE THREAD

**Issue by Lukey199223** [PHPfox-Official/phpfox-v4-feature-requests#488]
It'd be really useful and time efficient for the admin to be able to Drag and drop blocks and Save them, the blocks you cant move in admin cp EG:The Navigation menu, The news feed blocks and general content blocks (Music page block etc) , The cover photo, profile photo  Blocks In Admin Cp , Just generally open it up and make it more flexible for the admin to get the site exactly how they want and make it their own

**Comment by neil96** [comment]
Hi @Lukey199223 ,

We already have the ability to drag and drop items in the same block. If you want to drag and drop between blocks, this is not possible with the current design.

Regards.

**Comment by neil96** [comment]
Hi @Lukey199223 ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
