### ISSUE TITLE
Need Better Block manager

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-feature-requests#490]
Currently it's very hard to find previously created blocks

**Comment by neil96** [comment]
Hi @prepperz ,

Currently we manage blocks by location. You can suggest in detail how to better manage them? Thanks!

Regards.

**Comment by prepperz** [comment]
To start off, having the ability to search for blocks would help greatly. Also having a tree like structure would make it so much easier to work with as far as organization is concerned.

**Comment by neil96** [comment]
Hi @prepperz ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
