### ISSUE TITLE
Photos Added BY:

### ISSUE THREAD

**Issue by JOJOA1** [PHPfox-Official/phpfox-v4-feature-requests#492]
I've noticed when we let people do photo moderation, it does not state the person who approved it. 
    Each photo details of the photo should also contain who approved that photo, and/or this photo was last edited by username.

**Comment by neil96** [comment]
Hi @JOJOA1 ,

Thanks for you request. We will discuss with team and consider adding this feature in next versions.

Regards.

**Comment by neil96** [comment]
Hi @JOJOA1 ,

We separated moderation settings on phpFox 4.6.0. Could you check again.

Regards.
