### ISSUE TITLE
let normal users do photo moderation 

### ISSUE THREAD

**Issue by JOJOA1** [PHPfox-Official/phpfox-v4-feature-requests#493]
For some sites on a large scale, having moderators is just not enough.  How about the option  letting anyone approve photos, that comply with our photo policy If any. Each photo can tell site staff/admins who the photo was approved by. 
   These users can approve, or reject photos. Photos that are rejected will be sent to moderators, or site admin to officially delete the photo.

**Comment by neil96** [comment]
Hi @JOJOA1 ,

This feature is already available. You can enable this feature by go to user group setting -> select a normal user group -> select app photo -> enable these settings:
- Can edit all photos?
- Can delete all photos?
- Can edit all photo albums?
- Can delete all photo albums?
- Can approve photos that require moderation?

Regards.
