### ISSUE TITLE
Add Cover Photos category for Photos

### ISSUE THREAD

**Issue by JOJOA1** [PHPfox-Official/phpfox-v4-feature-requests#494]
When using the photos app, it would be nice to have a category for Cover Photos. For All images uploaded as a cover photo get listed in this category.

**Comment by neil96** [comment]
Hi @JOJOA1 ,

Thanks for your request. We will discuss with team and consider adding this feature in next versions.

Regards.

**Comment by neil96** [comment]
Dear @JOJOA1 ,

This feature is now available on phpFox 4.6.0.

Regards.
