### ISSUE TITLE
Add Profile Photos category to photos. 

### ISSUE THREAD

**Issue by JOJOA1** [PHPfox-Official/phpfox-v4-feature-requests#495]
For the photos app, "If this is enabled: Display User Profile Photos within Gallery" it would be nice to use category's for browsing Users Profile Photos. This way, users can search for only Profile Photos, Or Cover Photos, using categorys.  For all images uploaded as a Profile Photo, get added to this category.

**Comment by neil96** [comment]
Hi @JOJOA1 ,

Thanks for your request. We will discuss with team and consider adding this feature in next versions.

Regards.

**Comment by neil96** [comment]
Hi @JOJOA1 ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
