### ISSUE TITLE
"Location" enhancement 

### ISSUE THREAD

**Issue by Lukey199223** [PHPfox-Official/phpfox-v4-feature-requests#497]
Hello, 

The "Location" section of a users profile, where the location name is a link, 

I think it would be a cool idea if the link instead of directing you to the members page (like it currently does) , instead it would direct the user to the wikipedia page of the Specified location, So then other uses can read about that Place :)

**Comment by neil96** [comment]
Hi @Lukey199223 ,

Thanks for your ideas. But I'm afraid we do not have enough resources to map all the locations to the wiki pages. I marked your idea as "Third Party Dev" so developers can see and write into an app.

Regards.

**Comment by Lukey199223** [comment]
Thank you Neil for the quick reply :) I Apologise for the delay on mine, i;ve been swarmed with work the last couple of days ha, ah right thank you very much :)
