### ISSUE TITLE
captcha for blogs

### ISSUE THREAD

**Issue by erick260** [PHPfox-Official/phpfox-v4-feature-requests#498]
It seems there are bots just signing up, and adding blog post, and nothing else. Only thing that accounts like this does is just post 1 blog, and never comes back. Lets try to prevent this by adding captcha or Anti-Spam Security Questions to blogs.

**Comment by neil96** [comment]
Hi @erick260 ,

You can enable this feature by goto user group -> select a user group -> manage user group settings -> select app captcha -> Change **Enable CAPTCHA challenge when adding a new blog.** to yes.

Regards.
