### ISSUE TITLE
Feature and Sponsored icon show featured and sponsored items

### ISSUE THREAD

**Issue by starplan** [PHPfox-Official/phpfox-v4-feature-requests#499]
In the new Material Template... It would be nice if when you clicked on the Featured or Sponsored icons all the sponsored and featured items are listed for members, photos, blogs and videos etc.

**Comment by neil96** [comment]
Hi @starplan ,

We will discuss with team and consider adding this feature in next versions.

Regards.

**Comment by neil96** [comment]
Hi @starplan ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
