### ISSUE TITLE
"From" and "To" age set to minimum eligible age for site

### ISSUE THREAD

**Issue by starplan** [PHPfox-Official/phpfox-v4-feature-requests#500]
If finding a friend, could the "From" and "To" age be set to the minium age eligilble to use the website.

**Comment by neil96** [comment]
Thanks @starplan ,

We will discuss with team and consider adding this feature in next versions.

Regards.

**Comment by neil96** [comment]
Hi @starplan ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
