### ISSUE TITLE
blog categories

### ISSUE THREAD

**Issue by Scheinwelt-Media** [PHPfox-Official/phpfox-v4-feature-requests#501]
when clicking a blog category the categories block disappears. this block should stay for easy browsing through the categories.

**Comment by dawn2323** [comment]
Agreed!

**Comment by neil96** [comment]
Thanks @Scheinwelt-Media ,

We will discuss with team and consider adding this feature on next versions of phpFox.

Regards.

**Comment by neil96** [comment]
Dear @Scheinwelt-Media ,

This feature is now available on phpFox 4.6.0.

Regards.
