### ISSUE TITLE
private photos access 

### ISSUE THREAD

**Issue by Erick000** [PHPfox-Official/phpfox-v4-feature-requests#502]
On my request #438 I noticed we can only set a photo album to  Album(s) Privacy-Custom to people that are on friends list only. This new feature should work without being friends by just having an allowed list, people that are on this list, should be able to view your private album.

   When visiting another persons profile page, If you have a Custom Photo Album, you can give them access to your Album directly from the profile pages without actually being friends on the site. This is known as unlocking your pics. What ever user you browse you can give them access to your pics if you want.

**Comment by neil96** [comment]
Thanks @Erick000 ,

We will discuss with team and consider adding this feature in next versions of phpFox.

Regards.

**Comment by neil96** [comment]
Hi @Erick000 ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
