### ISSUE TITLE
Profile Skins

### ISSUE THREAD

**Issue by Erick000** [PHPfox-Official/phpfox-v4-feature-requests#503]
It would be cool to allow user profile pages to be able to change the theme/looks. If a member can change their profile page the way the want it to appear, more likely they are to come back.  Like how yall had it on v3.

**Comment by neil96** [comment]
Thanks @Erick000 ,

We will discuss with team and consider adding this feature in next versions of phpFox.

Regards.

**Comment by dawn2323** [comment]
Good one! Customization is the need of the hour! Everyone have their own choice of colours icons pics etc!
