### ISSUE TITLE
Profile widget 

### ISSUE THREAD

**Issue by Erick000** [PHPfox-Official/phpfox-v4-feature-requests#504]
Like on some sites, they allow user profile pages to have widgets. It would be nice to allow our phpfox sites to have them too.  
    **Widget locations Left wall block1, Right wall block3**
  ![image](https://user-images.githubusercontent.com/29802466/32702917-0e8a6e90-c7bc-11e7-907e-789130d4ce3c.png)

   **Widget Contents**
   When adding in Widgets you have option of adding a photo, youtube video via URL, Text using CKEditor,  and code.  You can only add one at at time. 
![image](https://user-images.githubusercontent.com/29802466/32702977-2aa8da2a-c7bd-11e7-853c-8e1986067bbc.png)

**Comment by neil96** [comment]
Thanks @Erick000 ,

We will discuss with team and consider adding this feature in next versions of phpFox.

Regards.
