### ISSUE TITLE
Add Activity points upon Account Creation 

### ISSUE THREAD

**Issue by Erick000** [PHPfox-Official/phpfox-v4-feature-requests#505]
When members first sign up for an account for us to be able to give them Activity points right away for the account creation.

**Comment by neil96** [comment]
Thanks @Erick000 ,

We will discuss with team and consider adding this feature in next versions of phpFox.

Regards.

**Comment by neil96** [comment]
Hi @Erick000 ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
