### ISSUE TITLE
Live Stream Broadcasting Option

### ISSUE THREAD

**Issue by dawn2323** [PHPfox-Official/phpfox-v4-feature-requests#506]
Live Stream Broadcasting - where only Admins or Premium members can shoot via their mobile phones and their friends list will get a notification stating that person is going Live Now! In case Admin is going Live then all in the network can view. Also Admins can give permission to certain individuals to broadcast for the entire network (Monetization can be huge for this feature itself). Similar to Instagram and Facebook Live streaming! It can be a huge value addition to social networks. Misuse of this service can be reported etc. Also ad slot blocks could be kept to increase monetization.

Features:
a)Number of present viewers 
b)Total viewers so far 
c) Option for friends to like and comment on the go! 
d) Comment options could be set as Public only or Private Only or Public or Private set by the person broadcasting or other option could be the person sending the comment can choose to post in public view or private view (Again the broadcaster can set what option they would want to give before starting the broadcast)
e) Report Misuse etc
f) Set limit time on broadcasting by admins

**Comment by dawn2323** [comment]
![facebook live streaming](https://user-images.githubusercontent.com/29255464/32716478-32ba2344-c87c-11e7-8572-8991c5c6a5df.png)
similar to this!

**Comment by neil96** [comment]
Thanks @dawn2323 ,

We will discuss with team and considering adding this feature in next versions of phpFox.

Regards.

**Comment by dawn2323** [comment]
Thanks!

**Comment by neil96** [comment]
Hi @dawn2323 ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.

**Comment by dawn2323** [comment]
Hi, So does it mean all these suggestions will never be implemented?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by neil96** [comment]
Hi @dawn2323 ,

Currently, we do not have plan to implement for this feature. However, in the future, our plan can change and this feature might be implemented.

Regards.
