### ISSUE TITLE
Group Chat Feature

### ISSUE THREAD

**Issue by dawn2323** [PHPfox-Official/phpfox-v4-feature-requests#507]
In addition to the One on One chat, adding a Group Chat option will be very useful where 3 or more people can join in to have a combined chat. Creator of the group will have few powers like Kicking someone out or to Add someone into the group chat. It will create excitement similar to whatsapp group chat. People can share files, comment, like specific comment, reply to a specific comment, send emojis, take an opinion poll(Advanced), Comment Received, Read options can also be there.

**Comment by dawn2323** [comment]
Thanks!!

**Comment by metall13** [comment]
I'm for such an update, im an excellent program, sorry to enjoy the unit

**Comment by neil96** [comment]
#395
