### ISSUE TITLE
Enable searching for hashtags from main search field

### ISSUE THREAD

**Issue by starplan** [PHPfox-Official/phpfox-v4-feature-requests#508]
Can you make it possible for a hashtag search from the main search field. Currently you can click on a hashtag to get its search results, but you can't search for the hashtag. It is not possible to find the information of interest if you can't view the hashtag in order to click on it.

Fitering of results should be available just as normal searches made from the main search field.

**Comment by dawn2323** [comment]
Nice

**Comment by neil96** [comment]
Thanks @starplan ,

We will discuss with team and consider adding this feature in next versions of phpFox.

Regards.

**Comment by neil96** [comment]
Hi @starplan ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
