### ISSUE TITLE
Hightlight friend button...

### ISSUE THREAD

**Issue by starplan** [PHPfox-Official/phpfox-v4-feature-requests#510]
Using the Material template, after clicking on Members, could you please highlight buttons that are ticked with a color so that they are easier to spot. This should also apply when searching members.

**Comment by neil96** [comment]
Thanks @starplan ,

We will discuss with team and consider adding this feature in next versions of Material template.

Regards.

**Comment by starplan** [comment]
Thanks Neil... It would be nice if there was an option to change the tick buttons color in CSS.

**Comment by neil96** [comment]
Hi @starplan ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
