### ISSUE TITLE
Become Featured using activity points

### ISSUE THREAD

**Issue by erick260** [PHPfox-Official/phpfox-v4-feature-requests#512]
i wish our site could allow people to become a featured member, by purchasing  it with  activity points. 
![image](https://user-images.githubusercontent.com/19263189/32924564-392d39aa-cb0b-11e7-8c37-364f5267a3d4.png)
   Price for featured 
3 Days own price ranage
1 week own price ranage
1 month: own price range

**Comment by neil96** [comment]
Thanks @erick260 ,

We will discuss with team and consider adding this feature in next versions of phpFox.

Regards.

**Comment by dawn2323** [comment]
Nice Idea! It will increase revenue for the owners and also create some buzz for users!
