### ISSUE TITLE
Toggle Photos using Arrow keys of keyboard

### ISSUE THREAD

**Issue by dawn2323** [PHPfox-Official/phpfox-v4-feature-requests#513]
Toggle Photos using Arrow keys of keyboard - it will make it a smoother and easier experience for users who access it via laptop/desktop and a flip/flick feature on mobiles to toggle between photos using mobile phone.

**Comment by neil96** [comment]
Thanks @dawn2323 

We will discuss with team and consider adding this feature in next versions of photo App.

Regards.

**Comment by dawn2323** [comment]
Thank you :-)

**Comment by dawn2323** [comment]
Thank you :-)
