### ISSUE TITLE
Flip/Flick feature to check various feeds for Mobile App

### ISSUE THREAD

**Issue by dawn2323** [PHPfox-Official/phpfox-v4-feature-requests#514]
Flip/Flick feature to check various feeds for MOBILE APP- it would be a great experience for users if we have a feature where by feeds are shown one at a time and users can flick Right(Just seen feed) or Left (New feed) ONE at a time. Feeds can be generated based on users liking. Options could be Random Public Feeds (Top/Latest), Random Friends Feeds(Top/Latest), Random Friends Circle Feeds(Top/Latest), or events, blogs, videos, quizzes, polls, or admin rated etc.  

Have seen this in few of the other apps. It makes the user experience really nice. Can also generate good revenue as admins can put ads between every X feeds (3 or 5 etc). Even sponsored feeds can be a huge revenue generator.

**Comment by neil96** [comment]
Hi @dawn2323 ,

phpFox does not have an official Mobile App. I mark this request as **Third Party Dev**, so developer can see and implement your request.

Thanks for your suggestion.
Regards.

**Comment by dawn2323** [comment]
Hi @neil96 ! Since PhPfox is coming with their own Native Mobile app, This above feature could be considered may be in its next release :-)
