### ISSUE TITLE
Make Photo My Profile Photo 

### ISSUE THREAD

**Issue by erick260** [PHPfox-Official/phpfox-v4-feature-requests#516]
This this a good feature, but however, i dont like how you can just make anyone profile pic your main profile picture. This would also be the same as stealing someones photo without actually having to download it . 

   The Make My Profile Pic should only appear on Your uploaded photos. Not No on elses.

**Comment by neil96** [comment]
Thanks @erick260 ,

We will discuss with team and consider adding this feature in next versions of Photo app.

Regards.
