### ISSUE TITLE
Allow Photo Albums public/private 

### ISSUE THREAD

**Issue by erick260** [PHPfox-Official/phpfox-v4-feature-requests#518]
i wish our site could allow  users to create just 1 Public Album, and 1 Private album.  If a member uploads a photo, they will be uploading to one of these albums, its either public or private by default and cannot be changed. More albums allowed per usergroup.
   If you create a default photo album for users that is 
   1 Photo Album Public
   1 Photo Album Private

**Comment by neil96** [comment]
Thanks @erick260 ,

We will discuss with team and consider adding this feature in next versions of Photo app.

Regards.

**Comment by neil96** [comment]
Hi @erick260 ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
