### ISSUE TITLE
Anonymous Posting with Moderation

### ISSUE THREAD

**Issue by dawn2323** [PHPfox-Official/phpfox-v4-feature-requests#519]
Can we generate a feature called Anonymous Posting for Pages/Groups etc where admins can enable disable this feature at their own discretion. It could be useful in some circumstances and it will lead to people stating their opinion if required or when they do not want to be known in public. May be only ADMINS of the site will only know who they really are incase a serious breach takes place.

**Comment by neil96** [comment]
Thanks @dawn2323 ,

We will discuss with team and consider adding this feature in next versions of pages/groups app.

Regards.

**Comment by dawn2323** [comment]
Thank you :-)

**Comment by neil96** [comment]
Hi @dawn2323 ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
