### ISSUE TITLE
Separate "Report" boxes 

### ISSUE THREAD

**Issue by Lukey199223** [PHPfox-Official/phpfox-v4-feature-requests#520]
Currently we have the same report option (box) for a Status as we do for a user

We need a Report box (with reasons) for Status posts (like we do now) but we need a separate report box (with the option to add different options) for a user 

for example, 

if one of your options are "Report for containing Malicious content" on a status, that doesnt make sense when reporting a user

thank you :)

**Comment by neil96** [comment]
Thanks @Lukey199223 ,

You already report this feature here #121,

Regards.
