### ISSUE TITLE
Checkbox Profile Questions

### ISSUE THREAD

**Issue by erick260** [PHPfox-Official/phpfox-v4-feature-requests#522]
I noticed If you have a profile question checkbox, If you have a lot of options, the list just keeps going down, and down. How about making the check boxes appear on the side insead of going down
 
![image](https://user-images.githubusercontent.com/19263189/33087516-d58b0e34-ceb8-11e7-96ea-9b42cab73c0a.png)

**Comment by neil96** [comment]
Thanks @erick260 ,

We will discuss with team and consider adding this feature in next versions of phpFox.

Regards.
