### ISSUE TITLE
Option  of being featured upon upgrade

### ISSUE THREAD

**Issue by erick260** [PHPfox-Official/phpfox-v4-feature-requests#523]
I noticed, our site does not have the option of being featured upon account upgrade. it would be nice to have the option for our members to be a featured member for a set number of days upon account upgrade.

**Comment by dawn2323** [comment]
Nice!!

**Comment by neil96** [comment]
Thanks @erick260 ,

We will discuss with team and consider adding this feature in next versions of phpFox.

Regards.

**Comment by neil96** [comment]
Hi @erick260 ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
