### ISSUE TITLE
Rich Text Editor for Blogs

### ISSUE THREAD

**Issue by dawn2323** [PHPfox-Official/phpfox-v4-feature-requests#525]
Hello. Can we get a better Rich Text Editor for blogs or forums similar to one we are using here where we can Highlight text and have more features which will look much better to connect and make an impact.

**Comment by neil96** [comment]
Hi @dawn2323 ,

You can install app [CKEditor](https://store.phpfox.com/product/1655/ckeditor) to have this feature.

Regards.

**Comment by dawn2323** [comment]
Thx!!
