### ISSUE TITLE
Add Subscription  to account settings

### ISSUE THREAD

**Issue by erick260** [PHPfox-Official/phpfox-v4-feature-requests#526]
on account settings page, it should also include Subscription and  Payments & Show, manage activity points,Buy more, Earn more/chart
   IF user is not in a membership, they will be offered membership packages. 
![image](https://user-images.githubusercontent.com/19263189/33138275-18cf96c8-cf78-11e7-85f8-f233ad25e9fd.png)

**Comment by neil96** [comment]
Thanks @erick260 ,

We will discuss with team can consider adding this feature in next versions of phpFox.

Regards.
