### ISSUE TITLE
Share Content on Page/Group

### ISSUE THREAD

**Issue by dawn2323** [PHPfox-Official/phpfox-v4-feature-requests#528]
Right now the share content is either on your own wall or friends wall. Can we add Page or Group to choose (if approved by admin). It makes the Core post more popular rather than uploading each time on multiple page/groups.

**Comment by neil96** [comment]
Thanks @dawn2323 ,

We will discuss with team and consider adding this feature in next version of pages/groups app.

Regards.

**Comment by dawn2323** [comment]
Thanks!

**Comment by neil96** [comment]
Hi @dawn2323 ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.

**Comment by dawn2323** [comment]
So does it mean this feature will never be implemented?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
