### ISSUE TITLE
Country, State / State and city

### ISSUE THREAD

**Issue by metall13** [PHPfox-Official/phpfox-v4-feature-requests#529]
In the user profile, you could specify the Country, State / State and city, and not write the city yourself.

**Comment by neil96** [comment]
Hi @metall13 ,

There are many of cities. We can't list all cities in the world.

Regards.

**Comment by metall13** [comment]
http://www.instantcms.ru/  This is the free engine on which you did this, look, it can inspire.

http://bardel.org/  This is a real example of the project, in the registration you can see that not all cities are being pulled, but they can be filled in


It is the functional that is important, it is not necessary to fill everything, this can be done by third-party developers, for example, as with the region / State

**Comment by neil96** [comment]
Hi @metall13 ,

They don't have enough cities. I tried with Thailand.
<img width="406" alt="screen shot 2017-11-27 at 15 30 18" src="https://user-images.githubusercontent.com/15936115/33257224-01bcadc2-d388-11e7-9a17-b5e3e303a1b2.png">

The text field for city is the best selection. There are many small and new cities, our cities list can't up to date.

Regards.

**Comment by metall13** [comment]
https://youtu.be/EgkwbSbz8m4

**Comment by metall13** [comment]
I ask you to reproduce not the content, but to repeat the logic of the work.

**Comment by neil96** [comment]
Hi @metall13 ,

I tested  with Thailand, and I can't find Bangkok city. Even, I can't find some countries in the list. They can list all cities in some countries, but not all countries in the world.

I add label "Third Party Dev", so all developers and see and make to an app. We already have an [app](https://store.phpfox.com/product/1697/regions-states) that lists all states. I hope they will implement your request.

Regards.
