### ISSUE TITLE
Logged out page

### ISSUE THREAD

**Issue by starplan** [PHPfox-Official/phpfox-v4-feature-requests#532]
In version 4.6.0 when you log out you are sent to the home page. I would like you to consider the idea of an option to send members logging out to the home page or a logged out page.

The logged out page could be simpler than the home page i.e. doesn't have a background image? and have a form on it similar to that on the home page but in reverse i.e. a "Sign back in" form shown first and a click to register form second. Rather like the "Sign In" form that you see when you click on the "Sign In" button on the home page. It could also have some text saying something like "See you soon" or "Have a great day".

On this page the option to show an advert, image, video (sponsored of course) by a member, non member or admin could be set via the admin panel.

**Comment by neil96** [comment]
Thanks @starplan ,

We will discuss with team and consider adding this feature in next versions of phpFox.

Regards.

**Comment by starplan** [comment]
Amazing .... Thank you.

**Comment by spirogg** [comment]
@starplan i have added a sign in page see last photo 
https://store.phpfox.com/apps/redirect-users-to-specific-url-when-they-log-out
