### ISSUE TITLE
Change Site Logo via usergroups

### ISSUE THREAD

**Issue by erick260** [PHPfox-Official/phpfox-v4-feature-requests#533]
it would be cool IF each usergroup has its own area to change site logo. We can have a different site logo for Free users. Upgraded users can see another site logo. Just look at amazon for example Amazon main site logo is different from an upgraded members logo. 
 This could result into better branding options  for our networks. 

![image](https://user-images.githubusercontent.com/19263189/33248292-4c50f370-d2f2-11e7-891a-4b9075f1b3c5.png)
![image](https://user-images.githubusercontent.com/19263189/33248339-6def9f68-d2f2-11e7-97c5-6d714f24f7f4.png)

**Comment by neil96** [comment]
Thanks @erick260 ,

We will discuss with team and consider adding this feature in next versions of phpFox.

Regards.

**Comment by neil96** [comment]
Hi @erick260 ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
