### ISSUE TITLE
Photo size in feed and on page after it is clicked

### ISSUE THREAD

**Issue by starplan** [PHPfox-Official/phpfox-v4-feature-requests#534]
I belive the "Photo" app will be different in 4.7.0, but I was looking at the size of the photos on the page after the photo is clicked and saw that there was quite a bit of grey on the left and right sides of the photo. I then noticed that the photo size on the feed.

Full frame dslr cameras photos have an aspect ratio of 2:3 and video cameras 16:9. So I am suggesting that the area devoted to the photo should have an aspect ratio of 2:3. There should be less grey on the sides when showing square photos and portrait orientated photos too.

As I am looking at this page again https://v4-material.phpfox.com/index.php/ I realize that the site is in a transitional state so the above my not be relevant.

**Comment by neil96** [comment]
Thank @starplan ,

We will discuss with team and consider adding this feature in next versions of video app.

Regards.
