### ISSUE TITLE
Make site serach ajax too

### ISSUE THREAD

**Issue by Ylmzef** [PHPfox-Official/phpfox-v4-feature-requests#535]
I run my phpfox site with site wide ajax but seacth function not working with it.
Also i use some apps like music player that plays music background, but when someone use phpfox seacrh function the music stoped.
It's not useful for visitors.

If you can do it with ajax too, i am sure there wil be come more nice apps from other developers.

**Comment by neil96** [comment]
Thanks @Ylmzef ,

We have discussed this issue before, and we will not implement this feature in phpFox v4.

Regards.
