### ISSUE TITLE
Option to Upload Photo Contents Into Exisitng Pages Albums

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-feature-requests#536]
In the pages album there is no way to upload to an existing album except your own which is totally counter productive. Any member of the page should be able to upload to any album on pages.

It would make it more productive if it people can upload to those albums. Otherwise what's the point of having a community page?

**Comment by neil96** [comment]
Thank @prepperz !

**Comment by neil96** [comment]
Dear @prepperz ,

This feature is now available on phpFox 4.6.0.

Regards.
