### ISSUE TITLE
v4.6.0 - translate phrases

### ISSUE THREAD

**Issue by CimborNet** [PHPfox-Official/phpfox-v4-feature-requests#539]
ver 4.6.0 (beta1) - Material themplate

We have't translate phrases for this... (look on pic)

![nothevetranslate](https://user-images.githubusercontent.com/11414490/33960482-294357cc-e04b-11e7-90b9-9eade43ed517.jpg)

But on system we have phrases: `rotate_left `and `rotate_right`

**Comment by neil96** [comment]
Thanks @CimborNet ,

We will fix this issue on 4.6.0 stable. If you find more issue like this, please report us [here](https://github.com/PHPfox-Official/phpfox-v4-issues/issues/new).

Thanks!
