### ISSUE TITLE
Option to Sticky a pages forum thread on the pages home page above the "post / write write something" area

### ISSUE THREAD

**Issue by darksolar1** [PHPfox-Official/phpfox-v4-feature-requests#54]
It would be really great have an option to be able to Sticky a pages forum thread not only on the forum, but on the pages home page above the "post / write write something" area as well. This way they can see what's hot / important in the forum, and have quick access to it while still being able to post to the status. This will definitely make the pages section a very usable area to carry ongoing conversations and discussions.

**Comment by Data66PF** [comment]
As we allow one thing per request, we are interested in only the first part of the request

**Comment by IsabellaJolie** [comment]
Hi darksolar1,
We're not sure if we understand your request correctly. So please confirm our description as following
1. Currently, to sticky a thread, admin has to go thread detail page, then click on Thread Tools --> Stick Thread. Ex: Go to this page: https://v4.phpfox.com/forum/thread/29/construct-your-record-and-develop-your-enterprise-with-e-mail-advertising/ to sticky this thread
2. You want to have a feature that allow admin to sticky threads at the listing page, like this page: https://v4.phpfox.com/forum/2/general/

If it is not your idea, please help us to explain it more detail. You can give us the flow and screenshots if any.
Regards,

**Comment by neil96** [comment]
Hi @darksolar1 ,

This feature is now available on phpFox Forum 4.6.0.

Regards.
