### ISSUE TITLE
Be the first to comment 

### ISSUE THREAD

**Issue by erick260** [PHPfox-Official/phpfox-v4-feature-requests#541]
I noticed you have a new setting for be the first to comment, If you are the first one to comment it should come with a set number of activity points. Be the first one to comment an earn points. -_-
   This could also be a good way of getting people more active.

**Comment by neil96** [comment]
Hi @erick260 ,

Admin can disable points feature, or user does not earn point when comment. So your suggest might not correct in some cases.

In your site, you can edit phrase in phrase manager. 

Regards.
