### ISSUE TITLE
Testimonial Add On Feature for Profiles & Business Pages etc

### ISSUE THREAD

**Issue by dawn2323** [PHPfox-Official/phpfox-v4-feature-requests#545]
Testimonial Feature is the need of the hour. People would love to read about a person or a business page etc! Testimonial Feature can be a separate tab in either profile or business page etc! Here either people could click "Add Testimonial" and leave a text (Editable by the one who posts)or a video msg(This would make it more fun).. or the individual can invite someone to leave a testimonial about himself or for his business page! This can be fun and also would increase the involvement! It could be used across features like for pages too where people leave a testimonial about how good or fun the page is! Reviews in general are many but Testimonials will be the GO TO place to get the right info!  Ofcourse the owner of the Profile/Page have the right to accept or decline or keep it pending!

**Comment by neil96** [comment]
Thank @dawn2323 ,

Your request is great. However it is quite unique to everyone. I mark this issue as "**Third Party Dev**" for all developers can see and make to an app.

Regards.

**Comment by dawn2323** [comment]
Hi! Thanks @neil96 :-)

**Comment by dawn2323** [comment]
Hi! Thanks @neil96 :-)
