### ISSUE TITLE
Reduce white vertical spaces

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-feature-requests#546]
Currently there are too much vertical space above photo. Same case for videos. pages, groups, etc.... forces users to keep scrolling down all the time... very annoying.

![screenshot](https://user-images.githubusercontent.com/19594886/34107038-a7a02246-e3c8-11e7-981b-2571172ada3c.png)

**Comment by neil96** [comment]
Thank @prepperz ,

We will discuss with team and consider adding this feature in next versions of Photo app.

Regards.

**Comment by harrison05** [comment]
We improved photo detail page in the newest version of Photos. Please check.
