### ISSUE TITLE
Cross or Minus in Quizzes

### ISSUE THREAD

**Issue by starplan** [PHPfox-Official/phpfox-v4-feature-requests#547]
I was adding a quiz in 4.6.0 and thought it would be easier to see and understand the addition and removal of a field if the icons next to the fields were + and -  rather than + and x. See images below.

![quiz-1](https://user-images.githubusercontent.com/17064302/34132689-f31d1762-e448-11e7-86ba-8864b9e1daf7.jpg)
![quiz-2](https://user-images.githubusercontent.com/17064302/34132690-f33d3cfe-e448-11e7-938c-6b2608664070.jpg)

**Comment by neil96** [comment]
Thank @starplan ,

We will discuss with team and consider adding this feature in next versions of Quizzes app.

Regards.
