### ISSUE TITLE
Forum Post title should be larger

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-feature-requests#549]
The current forum post title is way too small.
![screenshot](https://user-images.githubusercontent.com/19594886/34157912-7fc6f74e-e491-11e7-8435-d20a1a276d82.png)

**Comment by neil96** [comment]
Thank @prepperz ,

We will discuss with team and consider adding this feature in next versions of Forum app.

Regards.

**Comment by neil96** [comment]
Hi @prepperz ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
