### ISSUE TITLE
Fun feature idea! Have option for pages to customize their pages with sub-themes

### ISSUE THREAD

**Issue by darksolar1** [PHPfox-Official/phpfox-v4-feature-requests#55]
So people are making pages and putting in all their info and all that great stuff. It would be really fun and awesome to let each page have their own sub theme within the over all main theme of the site.

For example: You have the bootstrap main theme and a farm pages community. So the farm pages would have their own fun farm theme with different colors and maybe some background etc... just some basic customization they can do themselves without messing up the site.

This also opens up opportunities for other things as well.

**Comment by neil96** [comment]
I think this suggestion is better for third-party.

**Comment by lueung** [comment]
I'm talking about the basic framework for the idea that phpfox can implement as this would open up so many new opportunities for monetization and make phpfox more attract as a core base. After that, 3rd parties can extend it.
