### ISSUE TITLE
phpFoX should have its own social button...

### ISSUE THREAD

**Issue by starplan** [PHPfox-Official/phpfox-v4-feature-requests#550]
Facebook, Twitter, LinkedIn etc have buttons that website owners can place on their pages that allow their visitors to like on the respective social media website.

Would it be possible to have the option for phpfox to make available code that can place a button on a website that would allow their visitor to like or post on a phpfox website?

The code could be made available in the account menu or elsewhere.

**Comment by neil96** [comment]
Hi @starplan ,

On our [store](https://store.phpfox.com/apps?search=social), there are many apps support this feature.

Regards.

**Comment by starplan** [comment]
Hi Neil

I can't see an app that does what I am trying to describe. The button that I am describing should link back to the phpFoX website not Facebook or Twitter etc. The person can then log into their account and leave their comments/like about the page or website the button was on. Rough button examples below.

![socialbutton1](https://user-images.githubusercontent.com/17064302/34174976-bd9a6748-e4f2-11e7-828a-643337288c7f.jpg)
![socialbutton2](https://user-images.githubusercontent.com/17064302/34174978-bdba8b5e-e4f2-11e7-91fa-184bbc4307cc.jpg)
![socialbutton3](https://user-images.githubusercontent.com/17064302/34174975-bd7f607e-e4f2-11e7-8748-2c9b6d03a5fa.jpg)

**Comment by neil96** [comment]
Hi @starplan ,

We've got apps like this. However, developers did not continue maintenance and now it is disabled on the store. I mark this request as "**Third Party Dev**" for them can see and maintenance then publish them again.

Regards.
