### ISSUE TITLE
Clickable blog photo

### ISSUE THREAD

**Issue by starplan** [PHPfox-Official/phpfox-v4-feature-requests#551]
Can you make the main blog photo clickable please?

**Comment by neil96** [comment]
Hi @starplan ,

This feature is available. Please double check on our [demo](https://v4-material.phpfox.com/blog/).

Regards.

**Comment by starplan** [comment]
Sorry, I should clarify. I mean in feeds.

**Comment by neil96** [comment]
Thank @starplan ,

We will discuss with team and consider adding this feature in next versions of Blog App.

Regards.
