### ISSUE TITLE
eGifts have transparent backgrounds

### ISSUE THREAD

**Issue by starplan** [PHPfox-Official/phpfox-v4-feature-requests#552]
It should be noted somewhere in admincp that eGifts should not have transparent backgrounds... "BFF", "I love you" and "Send a beer" eGifts icon have transparent backgrounds... Their backgrounds should be filled in white.

**Comment by neil96** [comment]
Hi @starplan ,

We support transparency and any background color. Admins can use the way they like.

Regards.
