### ISSUE TITLE
Option to sponsor during creation/sharing.

### ISSUE THREAD

**Issue by starplan** [PHPfox-Official/phpfox-v4-feature-requests#553]
When a blog, marketplace, photo etc is being created/shared. The option to sponsor that item should be given on the creation/sharing page.

**Comment by neil96** [comment]
Thank @starplan ,

We will discuss with team and consider adding this feature in next versions of ads app.

Regards.

**Comment by neil96** [comment]
Hi @starplan ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
