### ISSUE TITLE
Phrases

### ISSUE THREAD

**Issue by Biaprom** [PHPfox-Official/phpfox-v4-feature-requests#555]
Problem with variables and his register. So i think good idea to have 2 different variables if it have same phrase but different register. Example: "Music Home", "Music home" now it was same, and create an errors. Just a suggestion.

**Comment by neil96** [comment]
Thank @Biaprom ,

We will discuss with team and consider adding this feature in next versions of phpFox.

Regards.

**Comment by neil96** [comment]
Hi @Biaprom ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
