### ISSUE TITLE
Thickbox

### ISSUE THREAD

**Issue by Biaprom** [PHPfox-Official/phpfox-v4-feature-requests#556]
Try to click on image with thickbox css class, it will open it in popup. But this action removes main scrolling of page, and page jerks

**Comment by neil96** [comment]
Thank @Biaprom ,

We will discuss with team and consider adding this feature in next versions of phpFox.

Regards.

**Comment by neil96** [comment]
Hi @Biaprom ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
