### ISSUE TITLE
Critical Navigation Improvements Needed Before Stable Release

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-feature-requests#558]
The current 4.6 rc navigation is a total nightmare as it requires the user to incessantly scroll up and down constantly to get anywhere. The back to the top button only compounds the problem by adding another click instead of  a UI that completely avoids all of it. This is a total nightmare for the users. After using it for just two minutes, it drove me crazy and I never want to use it again. So imagine what's it's like for someone that's never used phpfox before.

I hope that the stable version doesn't get release without these critical improvements. If you take a look at facebook, you'll notice that the left, top and right side of the screen does not move. The only part that moves is the center content which they can access from the menus  on the left, top and right side.

The other things that is needed are drop-down menus. This has been said, again and again and aigain. for the past 2-3 years....

**Comment by neil96** [comment]
Thank @prepperz ,
We will discuss with team and consider adding this feature in next versions of phpFox.

Regards.
