### ISSUE TITLE
Option for poking

### ISSUE THREAD

**Issue by ryanmiller159** [PHPfox-Official/phpfox-v4-feature-requests#559]
Hello, 

I would like an option to allow the admin to turn off poking appearing in the newsfeed.

It will cause privacy issues and it will drown the newsfeed with content the users really dont want to see.

**Comment by neil96** [comment]
Thank @ryanmiller159 ,

We will discuss with team and consider adding this feature in next versions of Poke app.

Regards.

**Comment by neil96** [comment]
Dear @ryanmiller159 ,

This feature is now available on phpFox 4.6.0.

Regards.
