### ISSUE TITLE
No like button on feed

### ISSUE THREAD

**Issue by ryanmiller159** [PHPfox-Official/phpfox-v4-feature-requests#561]
When a user adds another user and it is shown in the newsfeed as seen in the photo. There is no like button 
, however it does say " BE THE FIRST ONE TO LIKE THIS "
.
.
.
.
![no like button](https://user-images.githubusercontent.com/21185363/34428187-2211b416-ec18-11e7-8c65-2f0f8e5efd81.PNG)

**Comment by neil96** [comment]
Hi @ryanmiller159 ,
This issue is reported here PHPfox-Official/phpfox-v4-issues#2118
Regards.
