### ISSUE TITLE
sending a friend request 

### ISSUE THREAD

**Issue by ryanmiller159** [PHPfox-Official/phpfox-v4-feature-requests#562]
Hello, 

I have notice that the speed of sending a friends request is way to long to process. When i click on add friend , The pop up window shows up for you to send the request. When i send the request the window takes more the 5 secs to disappear . 

Can you increase the response time to instantly disappear when the user clicks on add friend. 

This feature will be users a lot and i don't want my users being annoyed with the slowness of the popup window.

 
![friend](https://user-images.githubusercontent.com/21185363/34428320-7611dc3e-ec19-11e7-9e15-614f3b039ec6.PNG)

![friend1](https://user-images.githubusercontent.com/21185363/34428326-7a7bc1ea-ec19-11e7-8f52-3db34cd67b2d.PNG)

**Comment by neil96** [comment]
Thank @ryanmiller159 ,

We will discuss with team and consider adding this feature in next versions of phpFox.

Regards.

**Comment by neil96** [comment]
Hi @ryanmiller159 ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
