### ISSUE TITLE
Add profile menu icon into callback

### ISSUE THREAD

**Issue by Biaprom** [PHPfox-Official/phpfox-v4-feature-requests#563]
If i add new icon code it is not work. I can do that using plugin feature, but it is not convenient.

`public function getProfileMenu($aUser)
	{
        if (!Phpfox::getParam('profile.show_empty_tabs')) {
            if (!isset($aUser['total_event'])) {
                return false;
            }
            
            if (isset($aUser['total_event']) && (int)$aUser['total_event'] === 0) {
                return false;
            }
        }
		$aTotal = $this->getTotalItemCount($aUser['user_id']);
		$aMenus[] = array(
			'phrase' => _p('events'),
			'url' => 'profile.advancedevent',
			'total' => $aTotal['total'],
			'icon' => 'module/event.png'	????????????
		);	
		
		return $aMenus;
	}`

**Comment by neil96** [comment]
Thank @Biaprom ,

**icon** is old field from v3, we do not use it on v4. We will discuss with team and consider adding this feature back in next versions of phpFox.

Regards.

**Comment by Biaprom** [comment]
I mean: How to put icon from 3rd party app in this section of profile menu(look at picture)? 

http://prntscr.com/hvedan 

I checked code and didn't find a way. Please explain, or i need to use hook option?

Thanks,

**Comment by harrison05** [comment]
Hi @Biaprom 

With the current version of phpFox, you can use property: **'icon_class' => 'ico ico-play-circle-o'** for profile menu.

Regards.
