### ISSUE TITLE
Allow full HTML / Javscript on pages/groups for user group Administrator

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-feature-requests#566]
Allowinging the phpfox site admin to add pages with full HTML / Javascript for special uses is a very useful function for the phpfox site owners to have while restricting regulars users to normal permissions. This will add another dimension of flexibility and opportunities and dynamic that the site owner would not otherwise have.

**Comment by neil96** [comment]
Thank @prepperz ,

We will discuss with team and consider adding this feature in next versions of phpFox.

Regards.

**Comment by prepperz** [comment]
Ok. I've raised this issue before. Phpfox should allow the phpfox site owner to choose how they want to run their site. For example, I use to be able to display dynamic data such as a ticker from an exchange in the widget block.. Now that doesn't work any more.

The following request should feature request should be reconsidered and at least give the site owner the option for the phpfox site owner to include a java script widget if he or she wants to

We are talking about only the phpfox site owner is allowed this option. Not the regular users.

Due to v4.6, Now the site cannot display any useful dynamic market information on pages. and is less functional than before.

**Comment by neil96** [comment]
Hi @prepperz ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.
