### ISSUE TITLE
When viewing pages menu items, everything should stay onpages (same for groups)

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-feature-requests#567]
Currently, everything takes the users away from the pages they are using. When viewing pages menu items, everything should stay on pages such as blogs, videos, forums, etc., etc.....

**Comment by neil96** [comment]
Hi @prepperz ,

I do not understand your request. Pages and Groups have similar design. Could you describe more detail. 

Thanks!

**Comment by prepperz** [comment]
What I mean is that it currently takes the users away from the "peges" section.

For example, if I go to pizza shop, everything I do should stay within the confines of the pizza shop until I'm ready to go to a different store,

**Comment by neil96** [comment]
Thank @prepperz ,

We will discuss with team and consider adding this feature in next versions of Pages and Groups app.

Regards.

**Comment by neil96** [comment]
#511
