### ISSUE TITLE
Adding and removing friends to and from custom lists...

### ISSUE THREAD

**Issue by starplan** [PHPfox-Official/phpfox-v4-feature-requests#569]
In version 4.6.0 RC - Once a friends list is created it is not possible to add anyone from the list/s. You should be able to do this. The whole list would have to be deleted and added again with the new amendments.

I would like to see the ability to edit the contents of the friends list/s created.

**Comment by neil96** [comment]
Thank @starplan ,

We will discuss with team and consider adding this feature in next versions of phpFox.

Regards.

**Comment by neil96** [comment]
Hi @starplan ,

As checked with team, you can add more friends to a list by go to all friends, select a friend then add to list.

Regards.
