### ISSUE TITLE
phpFox - CEOfox Stories

### ISSUE THREAD

**Issue by Robby1986** [PHPfox-Official/phpfox-v4-feature-requests#570]
Hello, I would be glad if the module / app is restored
Has been a good module of CEOfox
Thanks & Greetings
![3132113cdde25ee5c56436c67f629433](https://user-images.githubusercontent.com/8863784/34689044-6fa1a002-f4b4-11e7-8732-279914660b37.jpg)

**Comment by kirkkhua** [comment]
New Stories app is now available for phpFox: https://store.phpfox.com/product/2089/stories
