### ISSUE TITLE
Enable/Disable Download option for Music by ADMIN 

### ISSUE THREAD

**Issue by dawn2323** [PHPfox-Official/phpfox-v4-feature-requests#571]
Enable/Disable Download option for Music feature by ADMIN is crucial as some of the Copy Righted songs which SHOULD NOT BE AVAILABLE for FREE DOWNLOAD or Unauthorized sources sharing it! Creating an enable/Disable Backend feature for the ADMINS will be really helpful if that can be done soon! Thank You!

**Comment by neil96** [comment]
Thank @dawn2323 ,

We will discuss with team and consider adding this feature in next versions of Music app.

Regards.

**Comment by neil96** [comment]
Dear @dawn2323 ,

This feature is now available on phpFox 4.6.0.

Regards.

**Comment by dawn2323** [comment]
Amazing! Now we can use MUSIC feature without any issues!!
