### ISSUE TITLE
Music App - add a Playlist - for continuous playback

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-feature-requests#574]
Hi can we get a playlist where users can save there favorite mp3 songs from other users or their own songs uploaded and it can have player to play those songs continuously.  Maybe a pop-up window with a player so while online they can listen to their favorite music while on the site. Or even stream the playlist on their computers  phones etc. 

Playlist would be awesome. 

Thanks 

Spiro

**Comment by neil96** [comment]
Thank @spirogg ,

We will discuss with team and consider adding this feature in next versions of Music app.

Regards.

**Comment by spirogg** [comment]
@neil96 Thank you can you please look at the other issue I am having.

thanks again

**Comment by neil96** [comment]
Hi @spirogg ,

Thanks for your suggestion. But currently it does not fit with our plan.

Regards.

**Comment by bennington111** [comment]
"Add song to my music" is very importment option. Why upload the same song if it already exists? If user can just add it to yourself. This will also save space on the server. Please create this option. Before downloading a new song, you can check if this song already exists, and suggest not download another one, but add it to your existing one.
