### ISSUE TITLE
More Flexibility for Admins 

### ISSUE THREAD

**Issue by Lukey199223** [PHPfox-Official/phpfox-v4-feature-requests#577]
Hello :) I Hope everyone had a good christmas and new year :) 

Although Phpfox has provided with an awesome platform and continue to release good updates, I think phpfox admins still could do with slightly more flexibility when it comes to editing/removing core features on their particular website without breaking the script

I've suggested a few features that I need done on my website ASAP and their "Not in phpfox's plan" , so i think it would be nice, instead of admins on to phpfox all the time about "can you edit this or that on the core features" i think it'd be nice for the admin to be able to do it themselves from their end

for example, A while ago I wanted the "recently active" removed on my website, I dont know if we have the option in 4.6 (I havent upgraded yet) , but I Wasnt allowed to do it because it was a core feature, and even just that removing recently active and replacing it with just memberss, even that on its own slowed down the release of my website, because i didnt have it how i wanted it, 

I just think it'd give the admin more power and it'd just make the community in general happy, even if 70% of admins dont choose to edit any core feature, atleast the option and flexibility is there :) , 

it'd also take a bit of the weight off phpfox, because dev's can then programme enhancements etc for core features
sorry i didnt realise how long this turned out to be ha, 

If that makes sense ?

Thank you :)

**Comment by neil96** [comment]
Thanks for your thoughts @Lukey199223 . But your request is general, could you tell us detail features that you expected on the next versions of phpFox.

Regards.

**Comment by Lukey199223** [comment]
firstly sorry for the late reply, Didnt get this notification, 

Yes ofcourse i can give more info, What i mean is right now, Is the admin should be 100% incharge of their site (Edit whatever they want) Without fear of breaking the script of phpfox, for example phpfox told me before that if I went ahead with my plan and got a developer to edit some core files to the way I Want them or remove them completely if they are not necessary for my users , i got told it would break the script , I've just seen now that this has been accepted for 4.8. thats awesome :) I Cant wait to have even more power on my website :) , Just hope 4.8 comes out soon :)

**Comment by neil96** [comment]
Hi ,

Thanks for your suggestion. But currently it does not map with our plan.

Regards.
