### ISSUE TITLE
admincp/setting/license/  can we hide the lic ID and KEY in case we get hacked ?

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-feature-requests#580]
Hi in admincp/setting/license/
can we make it as we type in our license ID and KEY 

( make it so that it doesn't show the actual characters ? )
so in case someone is able to login to our admincp or we get hacked 
they don't see the actual License ID and Key

------------------------------------------------------------------
something like below 
Enter your license ID & Key:
License ID
` *************************** `
License Key
` *************************** `
**`Save Changes`**     **`Cancel`**

**Comment by neil96** [comment]
Thank @spirogg ,

We will discuss with team and consider adding this feature in next versions of phpFox.

Regards.
