### ISSUE TITLE
Ability to rename Group Category Name and Group Subcategory Name

### ISSUE THREAD

**Issue by matthewpomar** [PHPfox-Official/phpfox-v4-feature-requests#584]
Since our Groups are geographically based, we are going to use Group Categories as US States and Group Subcategories as US Cities. It would be nice to be able to rename them in the Globalization -> Phrases vs having to write JS to manipulate the DOM.

Here's an example of where we will have to use JavaScript to find and replace "sub-category" with "City":

![2018-01-23_07-33-43](https://user-images.githubusercontent.com/7439207/35278504-e5fea716-000f-11e8-87ca-659de43f577c.png)

**Comment by neil96** [comment]
Hi @matthewpomar ,

You can do this by edit/delete current category/sub-category or add new.

Regards.
