### ISSUE TITLE
Daily/Weekly digest email summarizing activity.

### ISSUE THREAD

**Issue by matthewpomar** [PHPfox-Official/phpfox-v4-feature-requests#587]
A great way to encourage engagement on a community is to have a daily or weekly activity digest email. This could include hot feed topics, popular members, groups, events, etc. 

User can disable this, or set it to daily or weekly.

**Comment by matthewpomar** [comment]
Hi @neil96 , I appreciate you considering my ideas. I have lots more :)

For those with the `This Party Dev` label, does this indicate there will be no plans for phpFox to add this feature, and I'll have to develop it on my own or hire a developer?

I also see you added this to the `4.8.0` milestone. What does that indicated.

**Comment by neil96** [comment]
Hi @matthewpomar , The `Third Party Dev` label means your request is compatible for 3rd-party app rather than core feature.  We add milestone `4.8.0` to easier to filter. We will notice to our developers after a period of time.

Regards.
