### ISSUE TITLE
Control who can post a feed item to Everyone via Membership Plan

### ISSUE THREAD

**Issue by matthewpomar** [PHPfox-Official/phpfox-v4-feature-requests#588]
Right now, any member can post anything they want on the feed. This is ripe for abuse and spam. It would be nice to limit who can post to "Everyone" as well as "Friends of Friends" on the activity feed by limited this to certain Membership Plans.

For example, a free membership plan may only be able to post to his Friends and Only Me. However, a paid plan may be able to post to Friends on Friends. And a higher paid plan can post to Everyone.

![2018-01-23_08-53-04](https://user-images.githubusercontent.com/7439207/35282531-58562374-001b-11e8-8c9d-65b3b45932ad.png)

**Comment by neil96** [comment]
Thank @matthewpomar ,

We will discuss with team and consider adding this feature in next versions of phpFox.

Regards.

**Comment by neil96** [comment]
Hi ,

Thanks for your suggestion. But currently it does not map with our plan.

Regards.
