### ISSUE TITLE
SEO - Improvements to page Titles 

### ISSUE THREAD

**Issue by matthewpomar** [PHPfox-Official/phpfox-v4-feature-requests#590]
SEO is critical component in the success of an online community. I believe phpFox is missing some essential SEO attributes and features to allow it to be found and indexed by Google and other search engines.

This specific feature request is arguably the most important. Following recommendations from Google, page titles should not be duplicated. It appears phpFox uses duplicate, default title on all pages, except when looking at specific records, such as a specific member, group, event, etc.  This will have negative impacts on SEO.

phpFox does have and "SEO" setting in admincp. However, this only allow you to set the page keywords (no seo value), and meta description. However, the most important page setting, Title, is not configurable.

My request is to make each page have a unique page Title out of the box. For example, in the Groups app, the page Title could be something like this:

1. {cat_name} Groups - {site_name}
2. {cat_name} > {subcat_name} Groups - {site_name}

If just this were to be implemented for any/all out-of-the-box apps having a category system, it would fix many of the Title problems.

With that, however, it would be nice to configure would you want a title to be. So, if you were to take the Group app as an example, a few text boxes could be added to settings like so:

Level 1 Page Title Template:
{cat_name} Groups - {site_name}

Level 2 Page Title Template:
{cat_name} > {subcat_name} Groups - {site_name}

Then, it would be simple for anyone to configure their preferred page title for potentially hundreds or thousands of page titles (btw, I see my community having over 1k cat/subcat configurations in the future).

I hope this feature will be implemented soon.

**Comment by neil96** [comment]
Thank @matthewpomar ,

We will discuss with team and consider adding this feature in next versions of phpFox.

Regards.
