### ISSUE TITLE
Allow phpfox site owner to insert unique blocks into specific pages

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-feature-requests#591]
Currently, there's no ability to have specific pages pull / display any dynamic data. It would be very useful to be able to insert blocks into specific pages to allow this.

See post for more detail: https://community.phpfox.com/forum/thread/56835/we-do-not-support-javascript-in-widgets-content-it-will-be-automatically-re/

**Comment by neil96** [comment]
Thank @prepperz ,

We will discuss with team and consider adding this feature in next versions of phpFox.

Regards.
