### ISSUE TITLE
Remove unused strings from phpFox

### ISSUE THREAD

**Issue by untilbit** [PHPfox-Official/phpfox-v4-feature-requests#592]
phpFox v4.6.0 contains strings that are not used.

I suggest removing all the that will not be used in next versions.

Some strings that could be removed:

- we_are_unable_to_find_a_branding_removal_assigned_to_this_license_dot
- you_cannot_rate_your_own_profile
- this_poll_is_being_moderated_and_no_votes_can_be_added_yet
- rate_this_image
- you_cannot_rate_your_own_album
- top_rated_members
- you_have_rated_all_the_available_images
- no_available_images_to_rate
- rate_photos
- top_rated
- you_have_already_rated_this_user
- you_cannot_rate_yourself
- rate_your_profile

**Comment by untilbit** [comment]
Duplicate phrase.

The following phrases have the same content. One should be removed.

- i_have_read_and_agree_to_the_terms_of_use_and_privacy_policy
- i_have_read_and_agree_to_the_a_href_id_js_terms_of_use_terms_of_use_a_and_a_href_id_js_privacy_policy_privacy_policy_a

**Comment by neil96** [comment]
Thanks @untilbit , We will check and remove theme.

**Comment by neil96** [comment]
These phrases are still using:
- this_poll_is_being_moderated_and_no_votes_can_be_added_yet
-
 i_have_read_and_agree_to_the_a_href_id_js_terms_of_use_terms_of_use_a_and_a_href_id_js_privacy_policy_privacy_policy_a

Others are removed on phpFox 4.6.1.

Regards.

**Comment by untilbit** [comment]
Great.
