### ISSUE TITLE
Pages Avatar when sharing pages status  to wall

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-feature-requests#593]
When sharing a page status to a wall it only show the title and not the Avatar of the pages.

**Comment by neil96** [comment]
Thank @prepperz ,

We will discuss with team and consider adding this feature in next versions of Pages app.

Regards.

**Comment by prepperz** [comment]
No it does not.

![screenshot](https://user-images.githubusercontent.com/19594886/38009743-d3dc88aa-3223-11e8-9aa6-5813798dd59d.png)

**Comment by david-phpFox** [comment]
We implemented it in the newest version.
