### ISSUE TITLE
embedded links

### ISSUE THREAD

**Issue by tyjay33** [PHPfox-Official/phpfox-v4-feature-requests#594]
Allow users to post embedded links from other sites into status post, or directly to, music, videos, blog etc.....

for example, SoundCloud embedded link you can play the music file within the site it's posted rather than going to the site by the link.

Thanks 

<img width="847" alt="screen shot 2018-02-01 at 11 01 37 am" src="https://user-images.githubusercontent.com/36044948/35688225-84bbe0be-0725-11e8-9694-bc1f1fa2d958.png">
<img width="531" alt="screen shot 2018-02-01 at 11 02 24 am" src="https://user-images.githubusercontent.com/36044948/35688226-84c840a2-0725-11e8-8655-32168a411739.png">

**Comment by neil96** [comment]
Thank @tyjay33 ,

We will discuss with team and consider adding this feature in next versions of phpFox.

Regards.

**Comment by neil96** [comment]
Hi @tyjay33 ,

Actually, phpFox supports this feature via bbcode tag `iframe`.  However, we do not encourage use this feature, because it can break your site layout.

Regards.
