### ISSUE TITLE
Message thumbnail should support smileys

### ISSUE THREAD

**Issue by Lukey199223** [PHPfox-Official/phpfox-v4-feature-requests#596]
Hello :) , Hope your all ok :) 

I've noticed one small thing we need

when your talking to someone via message, and you send a smiley, it shows up (obviously_ 

but when you click the message icon, to see all of the conversations you have, it just says "Luke Jones Sent a smiley"

The message thumbnail should show the smiley

**Comment by neil96** [comment]
Thank @Lukey199223 ,

We will discuss with team and consider adding this feature in next versions of phpFox.

Regards.

**Comment by harrison05** [comment]
Implemented on Message App.
