### ISSUE TITLE
pictures 

### ISSUE THREAD

**Issue by tyjay33** [PHPfox-Official/phpfox-v4-feature-requests#598]
post for photos are cut off awkwardly taking away from the content, the thumbnails need to be a better dimension accord to its size, the first two images are from phpfox,

the next three are a better ux design, the post has better positioning of the photos,not cutting out important  parts of the image and then when you click to view the image it doesn't take up the whole screen allowing the user to view the full image will out having to scroll

<img width="671" alt="screen shot 2018-02-04 at 5 42 51 pm" src="https://user-images.githubusercontent.com/36044948/35783238-c32aa6ce-09b8-11e8-963e-c31c2ee5c705.png">
<img width="1440" alt="screen shot 2018-02-04 at 5 43 19 pm" src="https://user-images.githubusercontent.com/36044948/35783240-ca54c1aa-09b8-11e8-98ff-a6994d9a3e49.png">

**examples** 

<img width="618" alt="screen shot 2018-02-04 at 5 38 24 pm" src="https://user-images.githubusercontent.com/36044948/35783269-2e0cc2ec-09b9-11e8-8dc2-a2eeb4f4045a.png">
<img width="1440" alt="screen shot 2018-02-04 at 5 41 11 pm" src="https://user-images.githubusercontent.com/36044948/35783271-3fcc8f44-09b9-11e8-8190-dd97893b66b9.png">
<img width="1435" alt="screen shot 2018-02-04 at 5 41 25 pm" src="https://user-images.githubusercontent.com/36044948/35783272-456dfe24-09b9-11e8-8d51-bbb0b0c6bfba.png">

**Comment by neil96** [comment]
Hi @tyjay33 ,

In phpFox 4.6.1, we improved the thumbnail photo in feed. However, we are still use 4 photos if the feed have 4 or more photos.

Regards.
