### ISSUE TITLE
Custom fields

### ISSUE THREAD

**Issue by djafrika** [PHPfox-Official/phpfox-v4-feature-requests#599]
Custom field group must be as a single block. This right now serve no purpose as each custom field acts like a separate block. Also, custom fields on profile info page are on the top. They should be on the bottom...
Text field needs to have ability to ad prefix and suffix. So that when we use it for url, that we have nice [link](url) instead of [http://link.com/some-url-that-is-ugly](url)

**Comment by neil96** [comment]
Hi ,

Thanks for your suggestion. But currently it does not map with our plan.

Regards.
