### ISSUE TITLE
Profile picture name with another language

### ISSUE THREAD

**Issue by kirkkhua** [PHPfox-Official/phpfox-v4-feature-requests#602]
If we try to upload a new profile picture when we're using another language it will be named like `February 7, 2018`. Seems that this value is automatically generated by the script. Is there an option to set locale according to user's chosen language (or network default locale)?

**Comment by neil96** [comment]
Thanks @kirkkhua ,

In next versions of phpFox, we will not display photo title in photo detail.

Regards.
