### ISSUE TITLE
Angular and Mongodb 

### ISSUE THREAD

**Issue by tyjay33** [PHPfox-Official/phpfox-v4-feature-requests#603]
Phpfox should be made with Angular and you should allow the database to be used with Mongodb

**Comment by neil96** [comment]
Thank @tyjay33 ,

We will discuss with team and consider adding this feature in next versions of phpFox

Regards.

**Comment by neil96** [comment]
Hi ,

Thanks for your suggestion. But currently it does not map with our plan.

Regards.
