### ISSUE TITLE
Profile Crop Images

### ISSUE THREAD

**Issue by juniortimeline** [PHPfox-Official/phpfox-v4-feature-requests#606]
Hello Guys,

Could you return back the option to disable the crop image on profile picture? This cropping image not work properly. 99% of my site users asking where is the photo that we need to crop? The photo is not show on the cropping tool.

http://prntscr.com/ifrczz

**Comment by arcticwolf8** [comment]
Banner crop ability would be nice also.

**Comment by spirogg** [comment]
This is good option to have please.

**Comment by neil96** [comment]
Hi ,

Thanks for your suggestion. But currently it does not map with our plan.

Regards.
