### ISSUE TITLE
Ban filter by email domain using wildcard is not working

### ISSUE THREAD

**Issue by elite1290** [PHPfox-Official/phpfox-v4-feature-requests#611]
In Cp Ban filter by email domain using wildcard * is not working
By ip is working 46.*
but email domain we tried *@mail.ru or *.ru not working
Please help fix the code because in Cp it mention use wildcard * for email domain
but is not working for 4.6.0 also.

**Comment by flarecoins** [comment]
spammer use abc@a.abc.com abc@b.abc.com abc@c.abc.com 
this mean .. one website where many subdomain create & then email created ... spammer use this  & present phpfox.com not provide help to block domain using wildcard
previous version of phpfox 3+ ... we easily block just *abc.com then full site blocked ... why your team remove this feature not understand.
provide us to help
thank
Anurag
