### ISSUE TITLE
Chat is slow

### ISSUE THREAD

**Issue by elite1290** [PHPfox-Official/phpfox-v4-feature-requests#612]
When we type to the chat it took say like 3-4 second before the chat appear in the chat, 
which is not acceptable as user will thing something wrong with the system as there is like a pause or delay whenever type

to the chat reply, the 1st time type to new chat is fast, but subsequent attempt to the chat reply it become slow 3-4 second then it appear to chat. 

Please update code to fix this issue to make chat instantly display and no pause no delay.

**Comment by elite1290** [comment]
Chat response speed to post is critical because phpfox is a social platform for chat interaction.

**Comment by elite1290** [comment]
![chat-slow](https://user-images.githubusercontent.com/3941435/37010747-eb0bb7e2-2127-11e8-983f-c59863e0af4c.png)

**Comment by elite1290** [comment]
![chat-slow](https://user-images.githubusercontent.com/3941435/37010821-5120a5e2-2128-11e8-8c43-3c2c949f585b.png)

**Comment by neil96** [comment]
Hi @elite1290 ,

When you add a new comment, the site will email to all relate users. That is the main reason for this delay.  We improved it by adding setting "Email Queue". The email will be sent via cron job. Could you turn on this setting and try again.

Regards.
