### ISSUE TITLE
Add a user / users from admincp

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-feature-requests#614]
Hi I want to be able to add a user / users  from the admincp section, I want to add a user / users without going through all the steps to sign up.  if this is possible can you show me how? 

if not can you make this available feature for us please. 

Thanks,
 Spiro

**Comment by kirkkhua** [comment]
Spiro, 

You can try [CSV User Import](https://store.phpfox.com/product/1855/csv-user-import) app to add users from the AdminCP.

**Comment by spirogg** [comment]
Hi. Thanks for link. But I truly think this is a easy and common core feature that should be free and part of phpfox. I have a few scripts and each one of them come.with a feature to add and or edit user / users.

**Comment by spirogg** [comment]
even assimple as adding one user at a time. thisis a needed feature. i can create a user from admin, set them as admins or whatever i want (user group) please this is not a delveoper feature, this should be feature in script part of phpfox

thanks again i hope you can make this for phpfox 4.6.1

**Comment by spirogg** [comment]
Please can you add this
 just one user at a time, 

I don't need multiple at a time, 
but it would be nice to add a user from admincp = just require: username, email, and password, 
then when login as user we can change all other details

thanks if you can find it in your Heart to add this would be awesome 🥇
