### ISSUE TITLE
Export ban ip

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-feature-requests#618]
It would be nice to be able to export the ban IP list so it can be moved to ip tables or other methods at the server level. This would certainly free up web site resources and speed up performance a bit since it doesn't have to process through too many ip's.

**Comment by prepperz** [comment]
I'm perplexed why this function is being offloaded to a third party dev as this should work hand in hand with this this: https://github.com/PHPfox-Official/phpfox-v4-feature-requests/issues/616

Also there should should be an option to "select all" to delete all the banned IP once it has been exported to a text file or something.

**Comment by neil96** [comment]
Hi,
Banned IPs are individualized for each site. So most people will not need this feature.
Btw, IP is a shared resource, it will continuously grant to many different people. So you can not ban an IP forever.

Regards.
