### ISSUE TITLE
Support for Digital Ocean Spaces CDN

### ISSUE THREAD

**Issue by adrianbro** [PHPfox-Official/phpfox-v4-feature-requests#620]
It would be good if phofox supported Digital Oceans Spaces service. They claim their api is s3 compatible so should be easy to implement at your end. More cost effective than S3

**Comment by neil96** [comment]
phpFox now has this feature. It's a separate app, you can download here: https://store.phpfox.com/product/2061/digital-ocean-space

Regards.
