### ISSUE TITLE
main signup : please add username search at signup - username available or not available as they type in box

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-feature-requests#621]
hi, could you add a username search, so when users signup it will tell them automatically if username is available or taken. 

this would be useful feature instead of making user do all the signup and then ( Sorry username is taken )

if we had it automatic search while typing in username box user will know if it is available (check mark OK) username is available
thanks hope this is easy to do

Spiro

**Comment by spirogg** [comment]
so basically I am asking for this

> that the script needs to check explicitly for a duplicate user name before attempting to create an account, for example as soon as the user leaves the user name field. In that case, the user name field would return error username already exists   or check mark as all good you can use this username, then you can continue to fill in the rest of the form

please 

Spiro

**Comment by spirogg** [comment]
this is also how github has this feature. when you type a username to signup after leaving that field it tells you of ok or already taken please is is much needed

![username search on github](https://user-images.githubusercontent.com/17736688/38054581-0ab4c904-329d-11e8-852f-6f3d62fe0f8d.PNG)

**Comment by petrus08** [comment]
This feature was already in v3, it should be also in V4.
