### ISSUE TITLE
make option for logo to be displayed above the Signup form on mobile devices 

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-feature-requests#630]
Can you make option for logo to be displayed above the Signup form on mobile devices possibly.. just right above the wording ( Signup - Login ) this way the logo always show when you first go to any website via a mobile phone ?

https://github.com/PHPfox-Official/phpfox-v4-issues/issues/2158

**Comment by neil96** [comment]
Hi ,

Thanks for your suggestion. But currently it does not map with our plan.

Regards.
