### ISSUE TITLE
when set user registration to upload photo 

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-feature-requests#634]
Hi can we get an updated look and feel of the area where we upload a photo and the browse button on registration? please

 It looks like a button from 10 years ago. the rest of the registration looks very nice, buttons, layout of buttons, form fields, etc.. 
 but the area where we upload a photo looks very outdated - ( especially the browse button )

see photo below. 

## Browser Windows 10 Edge ( looks Bad not part of the Material Theme Look)
----------------------------------------------------------------------------------------------------
![profile image upload - browse button](https://user-images.githubusercontent.com/17736688/38019754-139c53d4-323e-11e8-9263-0121b28c3b2b.PNG)
<br>
![windows edge full signup page](https://user-images.githubusercontent.com/17736688/38020864-f455b260-3240-11e8-840c-40b8279051b7.PNG)
---------------------------------------------------------------------------------------------------

## Browser Google Chrome (not that bad but could look nicer)

----------------------------------------------------------------------------------------------------
![not that bad](https://user-images.githubusercontent.com/17736688/38020336-91cd3d12-323f-11e8-9fd3-fc114c4ba284.PNG)

---------------------------------------------------------------------------------------------------

## Browser Firefox (not that bad but could look nicer)

----------------------------------------------------------------------------------------------------
![not that bad either](https://user-images.githubusercontent.com/17736688/38020348-9a72fa92-323f-11e8-9566-75b72b49623f.PNG)

---------------------------------------------------------------------------------------------------

## Something Like This One would look very awesome and more of the blue signup button and buttons of the Material theme look and Feel.

![something like this](https://user-images.githubusercontent.com/17736688/38020240-5159ae50-323f-11e8-8a4f-0f9089a31e96.PNG)

Thanks so much if you can get this done for version 4.6.1

**Comment by harrison05** [comment]
We just improved the layout of Profile Image section on Sign up form. Please upgrade to phpFox v4.8.4

Regards.
