### ISSUE TITLE
Create for feed pages an option for turn on off load more button. 

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-feature-requests#635]
Dear friends,

Would be nice option to have for front page Feed Page Feed and agroup Feed user page feed and all feeds  when you are on feed page  If I want to click on invite, contact, read privacy, terms, rss while I'm on that page. I have to wait till I scroll all the way down to click on it. Maybe in another version you could make this option to have load.more button. 
In feeds use load.more button - option.
 Yes / No 

This would be nice option. Please.
Thanks again Spiro.

**Comment by neil96** [comment]
Hi ,

Thanks for your suggestion. But currently it does not map with our plan.

Regards.
