### ISSUE TITLE
Video App - Create Block for Related videos to the right side of actual Video

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-feature-requests#638]
Can you Create a Related videos Block just to the right of the video player when viewing a video. it will pull all videos related to the video that is playing. 

it would be nice also because it will fill in the dead space of the videos playing when user uploads videos.
There is too much dead space left and right of actual video, if you have a block to the right with related videos that will fix the dead space of uploaded videos and registered users have more videos to choose from :)
![related videos](https://user-images.githubusercontent.com/17736688/38176722-a8789d54-35b9-11e8-9681-d20e6260d519.PNG)
![related videos](https://user-images.githubusercontent.com/17736688/38176742-32aa7fd8-35ba-11e8-9053-ac92577dd4b2.PNG)

**Comment by spirogg** [comment]
i see you have suggested videos but that seems to only work with youtube videos ?? 





![suggested videos](https://user-images.githubusercontent.com/17736688/38176785-d0ed3b86-35ba-11e8-9f8c-6fb2bcb10c05.PNG)

**Comment by neil96** [comment]
Hi @spirogg ,

This block is available for both upload video and shared video. It shows video in the same category.

Regards.
