### ISSUE TITLE
Video App - Share - Embed videos

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-feature-requests#639]
Can you Create under Share or another link to Embed Videos ?

something similar to this

![share-embed videos](https://user-images.githubusercontent.com/17736688/38176921-5f3798e4-35bd-11e8-9ce0-75eff9548230.PNG)

**Comment by neil96** [comment]
Hi ,

Thanks for your suggestion. But currently it does not map with our plan.

Regards.
