### ISSUE TITLE
Video App - When Viewing a Video can we keep Left side menu in place like music app

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-feature-requests#640]
Hi when Viewing a video - can we keep the left side menu in place all the time please like the music app

see photo

![just like music app](https://user-images.githubusercontent.com/17736688/38176944-dd585452-35bd-11e8-8e5d-aef78eec6f39.PNG)

**Comment by neil96** [comment]
Hi @spirogg ,

You can do it in adminCP:
Go to AdminCP -> Appearance -> Blocks -> add new blocks -> Controller: v.play; Component: v-category; block 1 -> save.

Regards.

**Comment by spirogg** [comment]
@neil96 
Would this be the same for other apps with menus - categories ?

**Comment by neil96** [comment]
Yes, they are the same.
