### ISSUE TITLE
groups and pages users to add Category then Threads like Forum App ?

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-feature-requests#642]
Is it possible to make Group Discussions and Pages Discussions have the ability to create Categories then Threads. Like forums instead of just Threads ?

**like this** 

![how to create forum discussion categories for groups and pages](https://user-images.githubusercontent.com/17736688/38184004-32d446d8-360a-11e8-9080-342a87794f91.PNG)

**not like this ?**

![user groups and pages should be like forum app be able to have categories then threads](https://user-images.githubusercontent.com/17736688/38183940-cceb5db6-3609-11e8-91e8-c6b96e0c209c.PNG)

**Comment by neil96** [comment]
phpFox does not support this feature in Pages/Groups.

Currently, we do not plan for this feature. Thanks for your suggestion

Regards.

**Comment by spirogg** [comment]
Ok no worries. Thanks
