### ISSUE TITLE
In admincp left side menu - please make it click to Hide left and click to appear 

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-feature-requests#645]
HI the admincp is hard for someone with mobile device or IPad - handheld device to really do anything,

 Im thinking the left menu to be able to close left, CLICK to hide the left side menu CLick  to Open the menu.. when you close menu to the left the right side of page opens wider so we can see

this would be nice feature to the already nice looking NEW admincp

Spiro

**Comment by spirogg** [comment]
you have this on your website https://store.phpfox.com/
![capture](https://user-images.githubusercontent.com/17736688/38891882-4d87fbf8-424b-11e8-9269-8f03a97778d6.PNG)
![capture1](https://user-images.githubusercontent.com/17736688/38891886-5031166e-424b-11e8-9dd2-29e9e183359a.PNG)

**Comment by spirogg** [comment]
please make this for us in admincp this is good for when were on the go and do not have laptop access. we can use mobile to view admincp and work better 👍

**Comment by neil96** [comment]
Thanks @spirogg ! We will update to status to you here.

**Comment by spirogg** [comment]
@neil96 anyway to get this in next update really can help when not infront of laptop or desktop to control admin adrea for phpfox websites.

**Comment by spirogg** [comment]
Thank you for Accept this.. :) this is going to be so useful for everyone on the go 

thank you again

**Comment by harrison05** [comment]
This feature is working in the current version of phpFox.
