### ISSUE TITLE
can you make the swatch for photos smaller size or make option to turn on or off ?

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-feature-requests#646]
hi,

is there a way to make the photo swatch smaller in size when viewing photos ? about half the height ?
 on smaller devices it takes up to much space to view the actual photo, kind of seems to be in the way

also can you make it an option in admincp to turn ON swatch or OFF swatch but keep the next prev buttons always available ?

thanks

Spiro

![capture](https://user-images.githubusercontent.com/17736688/38784742-412f2df6-40dc-11e8-8658-0f7a5bd2d821.PNG)

**Comment by harrison05** [comment]
We improved photo detail page in the newest version of Photos App.
