### ISSUE TITLE
MUSIC Module - Ability to save tracks to own playlist?

### ISSUE THREAD

**Issue by simyas** [PHPfox-Official/phpfox-v4-feature-requests#653]
It's nice to see music tracks uploaded from other members, however, can we add a button/feature that allows us to "add track to my playlist" for multiple tracks?  That way we can build a custom playlist by saving various tracks from around the community.  Search Engine (SE) has this feature and it would be really helpful for our platform too.

**Comment by spirogg** [comment]
Playlist would be nice

**Comment by dawn2323** [comment]
Very nice. It would be very useful and convenient too!!

**Comment by harrison05** [comment]
We implemented Playlists in the newest version of Music App. Please check.
