### ISSUE TITLE
can we get a block to show on forum when reading post page ?

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-feature-requests#655]
I would like to know if you can make possible to be able to create blocks in forum post please

for ads sponsored whatever

![forums-needs-entry-for-blocks](https://user-images.githubusercontent.com/17736688/39108888-eb2a96de-468f-11e8-93d5-b08aa124c4ae.png)

**Comment by david-phpFox** [comment]
Fixed in Forum 4.6.2
