### ISSUE TITLE
Invite Friend - Add field to create a custom message

### ISSUE THREAD

**Issue by simyas** [PHPfox-Official/phpfox-v4-feature-requests#658]
Allow users to create a custom message before sending out invites to potential members

**Comment by neil96** [comment]
Hi @simyas 
Please explain your request more detail. Thanks!

**Comment by simyas** [comment]
When you click “invite” you can only list email addresses to send out.  It would be nice to have a field so that you can create a custom message.  I.e.  “Hi Friends!  I want you to sign up for this website and add me as a friend” etc.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by neil96** [comment]
Thanks @simyas .

We will discuss with team and consider adding this feature in next versions of phpFox

Regards.

**Comment by spirogg** [comment]
Maybe allow user to see default message first. If they want to add thier own message they can if not they can send the default message we have already.

**Comment by dawn2323** [comment]
Yes Nice idea! Needed!
