### ISSUE TITLE
Option to Cast Poll Votes anonymously? 

### ISSUE THREAD

**Issue by dawn2323** [PHPfox-Official/phpfox-v4-feature-requests#660]
Hello. Can we have an option under "POLLS" where users can vote without others coming to know who they have voted for? For Ex: I vote on a Poll but I DO NOT want people to know who I Voted for! Only my Vote adds up to the selected category thereby maintaining my privacy. It is an option for the user to choose or alternatively we could enable or disable this feature depending upon the creator of the Poll who can choose either of the options?

**Comment by neil96** [comment]
Dear,

Thanks for your suggestion. But currently we do not have plans to implement this feature.

Regards.
