### ISSUE TITLE
Add Search filters for Groups

### ISSUE THREAD

**Issue by simyas** [PHPfox-Official/phpfox-v4-feature-requests#661]
It would be nice to filter your search for Groups just as you filter for Friends.  Filters could include:

- Location
- Category
- Status:  Open/Closed (meaning accepting members or not)
- Total Members
- Age range (i.e. all ages, 18+, 25-30 etc)
- Keywords

**Comment by neil96** [comment]
Dear,

Thanks for your suggestion. But currently we do not have plans to implement this feature.

Regards.
