### ISSUE TITLE
Ability to subscribe to Blog Author button from blog page

### ISSUE THREAD

**Issue by simyas** [PHPfox-Official/phpfox-v4-feature-requests#664]
I know you can always click on the blog author and add him/her as a friend (by leaving the blog post page), but it would be nice to have a button, on the blog page, that allows you to follow/subscribe to the blogger's future blogs or just follow SOME of the author's blogs (via category subscription).

p.s.  "View all entries" should be another button

**Comment by spirogg** [comment]
very nice Idea ... Subscribe button 👍
