### ISSUE TITLE
Update phpfox CKeditor - new features - plugins for embed videos etc please

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-feature-requests#667]
https://docs.ckeditor.com/ckeditor4/latest/guide/dev_example_setups.html

**new features we could use some more of these plugins especially for embed videos**

The Article Editor is based on the Standard package with a few modifications:

Added five additional plugins:
Auto Embed and Semantic Media Embed for inserting embedded media resources like videos (e.g. from YouTube, Vimeo), tweets or slideshows.
Enhanced Image to provide captioned images.
Upload Image and Upload File to support file uploads via drag&drop and pasting images from clipboard.
Adjusted the toolbar configuration to display buttons in a single row.
Adjusted content CSS styles, including usage of Nunito Sans font from Google Fonts.

https://community.phpfox.com/forum/thread/57142/core-blog-app/?view=348694

**Comment by prepperz** [comment]
This should include being able to embed videos that's already on a phpfox based site.
