### ISSUE TITLE
Navigation Bar takes up too much space

### ISSUE THREAD

**Issue by simyas** [PHPfox-Official/phpfox-v4-feature-requests#668]
I'm submitting this because a lot of PHPfox developers are telling me that condensing/changing the menu structure is too hard.  As of now, the navigation menu bar functions so that it is 3 rows/lines--that's too much space (especially for modern website designs; they only require 1 line, 2 max):

Line 1 - Top Menu - with logo, search, sign up buttons

Line 2 - Primary Menu - with main navigation items (i.e. Home, Events, Blogs, Members, etc)

Line 3 - Sub-menu - with sub category menu items that belong to Primary menu items (i.e. All events, My events, 
etc)

This is all taking up too much space.  Can we design it so that Primary menu items go inside the Top menu and the Sub-menu items go inside a drop-down menu when you click/hover on Primary menu item?  That is only 1 line.  

If you can't do all of this (condense menu to 1 line), then can you at least shorten it to 2 lines?  Still put Primary menu items into Top menu, then move sub-menu to where Primary menu used to be.

**Comment by neil96** [comment]
Dear,

Thanks for your suggestion. But currently we do not have plans to implement this feature.

Regards.
