### ISSUE TITLE
As ADMIN, ability to switch to user without having to log out

### ISSUE THREAD

**Issue by simyas** [PHPfox-Official/phpfox-v4-feature-requests#669]
Many users may have problems.  As an Admin, i'd like to easily "switch to User view" instead of having to log out then log in as the user.  This would function similarly to "switch to Admin CP" or "Login as Page" in my Avatar drop down menu (top right corner).

Problems to solve:
- Act on behalf of user and correct problems...just like you guys can/do when we submit support tickets.

**Comment by neil96** [comment]
Hi @simyas ,

I already have feature login as another user. However, we do not support feature login admin back, and currently, we do not have plan for this feature.

Regards.

**Comment by simyas** [comment]
how do you easily log in as another user?
