### ISSUE TITLE
Sort users search filter listing in admincp

### ISSUE THREAD

**Issue by darksolar1** [PHPfox-Official/phpfox-v4-feature-requests#67]
Currently there are no sort filter capability in the admincp. It would be nice to be able to select one of filters, IP for example, or names etc... 

Having this feature would really come in handy... so you can quickly see which IP may have multiple accounts, but that's just one use case... So then the question is why? Are they creating multiple account to spam? to claim prizes multiple times of a contest we did? or is it legit accounts by other family members? I'm sure there are other use cases...

**Comment by Data66PF** [comment]
So you want the headings of each column to be clickable as sort filters, basically.

**Comment by lueung** [comment]
yup

**Comment by neil96** [comment]
Dear @darksolar1 ,

This feature is now available on phpFox 4.6.0.

Regards.
