### ISSUE TITLE
Privacy setting to hide pages you create

### ISSUE THREAD

**Issue by nativedragon11** [PHPfox-Official/phpfox-v4-feature-requests#673]
Would really like a setting to be able to hide the pages I create from my profile.

The block that shows the pages I "like" makes sense, but if I am an admin or creator of a page, I may not want other users to know (such as if I created a page for my site's support team and don't want to be contacted on my personal page with site issues, or I am acting on behalf of a brand). 

I know I can hide admins from the page itself, but on my personal profile it still shows the pages created/administrated by me.

This could be a user group setting, or a privacy setting in the account. Like: 
Who can view pages you created/own?
Anyone
Community
Friends Only
No One

**Comment by dawn2323** [comment]
Yes! makes sense!! Needed!

**Comment by spirogg** [comment]
Yes would be nice feature.

**Comment by neil96** [comment]
Dear,

Thanks for your suggestion. But currently we do not have plans to implement this feature.

Regards.
