### ISSUE TITLE
Ability to display usernames instead of full name throughout site

### ISSUE THREAD

**Issue by nativedragon11** [PHPfox-Official/phpfox-v4-feature-requests#676]
Would like the option to display usernames throughout site instead of full names. That way, site members could refer to each other by their unique username instead of their full name.

Example 1: If site member "Steve Jones" is friends with me, and there are many people with the same full name "Steve Jones" (or other people with similar names like "Steve James") on my friend list, then it would be easier to identify which one is which by their unique usernames.

Example 2: A site member is an artist with full name "James Palmer" that prefers to be called by his nickname "jimmytheartist" which he has chosen as his username and vanity url. Instead of being limited to creating a page to use his nickname throughout the site, his personal profile would display "jimmytheartist", and his username would also display with the photos of his art he posts, or next to the comments he make on other items.

This would also make it easier for people that use stage names (like dancers, singers, actors, models, artists, etc.) to claim their unique username to make sure there was no fake accounts pretending to be them. This would also make the displayed username match their vanity url for consistency, allow site members to search for their unique username, and negate the need for everyone to create a separate page just to have their username as the displayed name throughout the site.

This could be an option in the admin panel like:
Display Username or Full Name throughout site:
Username
Full Name

If username is selected to be used throughout the site, then full name would still be visible in profile info section with the option to make it visible to only the account holder.

**Comment by spirogg** [comment]
this is nice to have username or full Name option i agree i believe in older versions we had this option also to to have full search capabilities of both username display name full name when friends are looking for friends or family..

**Comment by neil96** [comment]
Dear,

Thanks for your suggestion. But currently we do not have plans to implement this feature.

Regards.
