### ISSUE TITLE
Google maps warning to setup billing soon for maps API. 

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-feature-requests#678]
Neil i got an warning that Google API for maps says  

We have made changes to billing. You will soon be required to setup a billing account, in order to continue to use Google Maps APIs.

Can we use another map API for free open source somehow ??

**Comment by spirogg** [comment]
Here is a link I found to 3 free mapping sites 
leaflet is one thats open source 
not sure how easy would be to implement  
but worth a read to keep costs down in map features with phpfox 

 https://opensource.com/life/15/11/getting-started-web-mapping

**Comment by spirogg** [comment]
Google introduces a revamp of Google Maps Platform

Google yesterday announced a revamp of its Google Maps business. http://bit.ly/2JM8A0A

The new Google Maps Platform offers streamlined API products, a simplified customer experience, a single pricing plan with pay-as-you-go billing, free support, a single console, and new industry solutions. 

Starting on June 11, you’ll need a valid API key and a Google Cloud Platform billing account to access the core Google Maps APIs.

With this new plan, developers will receive the first $200 of monthly usage for free.

**Comment by neil96** [comment]
Hi @spirogg ,

As I checked here: https://developers.google.com/maps/current-pricing, if your site is free for everyone, you can continue use google maps for free, else you still have **Free up to 25,000 map loads per day**.

Regards.

**Comment by chena321** [comment]
https://developers.google.com/maps/billing/understanding-cost-of-use  is the current rates.
