### ISSUE TITLE
General Data Protection Regulation (GDPR) compliance

### ISSUE THREAD

**Issue by starplan** [PHPfox-Official/phpfox-v4-feature-requests#681]
In a few days GDPR will take effect in all of Europe, it affects Facebook, Google and Twitter etc. phpFox should be in compliance. Could you please provide the necessary compliance tools for phpFox so that websites using phpFox wll be in compliance with GDPR.

For more information, go to the following pages.
https://ico.org.uk/for-organisations/guide-to-the-general-data-protection-regulation-gdpr/

**Comment by neil96** [comment]
Hi @starplan ,

Our next version will support these compliances

Regards.
