### ISSUE TITLE
Option to show a splash screen on login.

### ISSUE THREAD

**Issue by starplan** [PHPfox-Official/phpfox-v4-feature-requests#683]
How about an option to show a splash screen immediately after logging in. On this page an ad, video or some information can be shown. An option to set how long this page is shown for or, a button could also be on this page that once clicked would continue and complete the logging in process.

**Comment by spirogg** [comment]
I think you can make this if they not allow for splash screen. You can create a page and then in admincp there is option to redirect user to a page  when user signup and also I believe when user logs in. In that page you can make html and use ad or video or whatever you want. ? Just in case they don't make this a feature. For us. :)
