### ISSUE TITLE
Status update field open by default?

### ISSUE THREAD

**Issue by starplan** [PHPfox-Official/phpfox-v4-feature-requests#685]
I'd like to see an option to have the status input field open by default.

Open:
![status-field-open](https://user-images.githubusercontent.com/17064302/42327820-9bfee826-8064-11e8-8532-84b33e452413.jpg)

Closed:
![status-field-closed](https://user-images.githubusercontent.com/17064302/42327819-9bdc77aa-8064-11e8-9057-f3db6cad8651.jpg)

**Comment by neil96** [comment]
Dear,

Thanks for your suggestion. But currently we do not have plans to implement this feature.

Regards.
