### ISSUE TITLE
when users do a search can we add a log in admincp of search words ?

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-feature-requests#687]
when users do a search on our sites can we add a log in admincp of the  search words they used?

example 
5 users searched the word SEO
1 user searched the word: phpfox
10 users searched the word: Money

Based on these words we can adjust our keywords and descriptions to better our SEO 
 what users most searched for on our site

Thanks

Spiro

**Comment by spirogg** [comment]
@harrison05 any word on this feature?

**Comment by harrison05** [comment]
@spirogg our develop team improved this feature, it will available in the next version of phpFox.

**Comment by harrison05** [comment]
This feature is now available in phpFox v4.8.4 (AdminCP > Maintenance > Search Words)

Regards.
