### ISSUE TITLE
we need a better place to see promotion and activity points so users can work hard to get to next level in promotion

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-feature-requests#689]
the only issue i see is that there is no place for user to see what the promotion is ?? 
 **i am user,  then magically I get promoted to user 2 ???**
 **_as a user, I say: I don't know about this ???_**

**so its really not an exciting thing for me as user** 

 
**we need a better place to see promotion and activity points so users can work hard to get to next level in promotion

even a place where we see a list of all promotions users qualify for
 so user can see them and work hard to achieve them...**

**Comment by spirogg** [comment]
please add activity points here in drop down so users can get to activity points easier

then when they see activity points page make the promotion level show at bottom of page so users can see what they get for promotion


**- Please add activity points here in drop down so users can get to activity points easier**

![promotions and activity points](https://user-images.githubusercontent.com/17736688/42933517-994d0b70-8b0a-11e8-98d9-b7b4def09ca3.PNG)


**- now here at bottom of page we show what the promotion is and how many points and or days we need to get promotion**

![promotions activity points](https://user-images.githubusercontent.com/17736688/42933672-f3a6ab26-8b0a-11e8-92d0-432fc975614f.PNG)

**Comment by dawn2323** [comment]
Very nice! Like this!
