### ISSUE TITLE
buying music

### ISSUE THREAD

**Issue by erick260** [PHPfox-Official/phpfox-v4-feature-requests#691]
my site users have been asking me for a while now If they can sell there music tracks on the music page. It would be nice to let users upload music, and sell it If they wanted too.

**Comment by spirogg** [comment]
@erick260 is your idea for website owner to make money too ? charge a percentage of what they sell it for. Like 10% or 15% 20% etc. That would be cool if that was an option also. We can charge users or not charge users. 

Thanks good idea.
