### ISSUE TITLE
need to approve user signup Emails - 1 verify Email, 2 pending approval Email, 3 Welcome - Approved Email

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-feature-requests#695]
hi when we enable in admincp verify email on signups, and approve users when they signup

- first they get 1 email : you have to verify email address: 

- then after they get email for verify and click on the link they get a second email
 Welcome email below:

Hello sppirogg, 

Thanks for joining our community

Kind Regards, 
mywebsite domain

- **IS there a way to get another email before the welcome email (that says something like: )**

Hello Spirogg

We are reviewing your account and pending approval.
Someone will get back to you soon. 
we appreciate your patience 

_(Approval processes may take up to 24 hours.)_

kind regards,
mywebsite domain

- and then after pending approval Email - Then they get the Welcome - Approved email 

Hello sppirogg, 
Your account has been approved.
Thanks for joining our community https:mywebsite domain	

Kind Regards, 
mywebsite domain

- **approve user signup emails **
- **1) verify email, 2) pending approval email, 3) Welcome - Approved email**

**Comment by spirogg** [comment]
@harrison05 will this make it into 4.7.8 ? I hope so thanks

**Comment by harrison05** [comment]
Yes, we will add this feature to 4.7.8.

**Comment by spirogg** [comment]
@harrison05 and phpFox

THANKS SO MUCH THIS WORKS GREAT NOW 👍 🥇

**Comment by harrison05** [comment]
I'm glad to hear that.

Thanks.
