### ISSUE TITLE
when sponsor or feature in pages and groups can we add the blocks (Sponsor) (Feature) ?

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-feature-requests#697]
when sponsor or feature in pages or groups can we add the blocks (Sponsor) (Feature) ? other wise who will pay to sponsor an item if it not show in block Sponsor

also if we can Feature would be nice

thank you

Spiro

**Comment by harrison05** [comment]
What exactly do you mean? 

1. Mark feature or sponsor items in Page/Group such as Photo, Event... and then have these blocks will be shown at:
1.1 detail page of Page/Group (The page have activity feed)?
**or**
1.2 listing page of Photo, Event... in Page/Group?

2. Feature / Sponsor a Page/Group?

Regards.

**Comment by spirogg** [comment]
Hi.
 First in pages and groups. The owners of a page or group can pay to sponsor  thier page or group  so #2 of what you asked  
 
- I think sponsor/ feature, pages and groups was already approved. 



What I meant was :

I want a sponsor and feature block in photos events music etc etc... 

 1.2 listing page of Photo, Event... in Page/Group?

Example  

 if I am view a page and select photos. I will see a sponsor block and feature block there. 

Also if I view a group and select photos
 I will see sponsor block and feature block there. 

This will be in line with the rest of the website. Photos events music videos etc. 
If in a page or in a group /viewing photos events music videos discussion etc. 
 We have sponsor blocks and feature blocks just like the main website has.

**Comment by harrison05** [comment]
We're working on sponsor/feature a page/group and they will be released in next version.
About block sponsor/feature in pages/groups as your request, we will consider and inform you later.

Thank you.

**Comment by spirogg** [comment]
@neil96 @harrison05 
thank you... this now works: 4.6.1.b6 
feature and sponsor groups and Pages.. you guys are awesome !!!!
