### ISSUE TITLE
Search ASC and DESC

### ISSUE THREAD

**Issue by Apps2018** [PHPfox-Official/phpfox-v4-feature-requests#699]
Is it possible to have the Search filter display items on the ascending and descending order.
At the moment we can only view "Latest" items displayed.  Can you please add a Search Filter that can display "First" items too?

**Comment by harrison05** [comment]
We understand your request, but filter by ASC and DESC might only use in some Apps, so we can't apply this to all apps. Which apps do you want to have this feature?

Regards.
