### ISSUE TITLE
AutoPlayer for Photos

### ISSUE THREAD

**Issue by Apps2018** [PHPfox-Official/phpfox-v4-feature-requests#700]
It would be really great if photo albums could have on/off button that autoplays the photos in a loop
I hope you will consider adding this feature in the future.

**Comment by harrison05** [comment]
Can you give us more information about your request? Which page and section do you want autoplay the photos? (listings page, detail page...?), it would be great if have any screenshots.

Regards.

**Comment by Apps2018** [comment]
![photos](https://user-images.githubusercontent.com/42245599/44022342-3ad5ab86-9edf-11e8-99df-452e7821d58d.png)
