### ISSUE TITLE
admin - login as other user from front end:  https://domain.tld/username 

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-feature-requests#701]
hi is it possible to add this feature to the front end
see photo - I would like ot have this feature from front end, give us the option as we are using the frontend to make changes as other user if we needed to

see photo to where im thinking we can add this feature to click on in frontend /username 

![login as other user](https://user-images.githubusercontent.com/17736688/43976554-a8e4e988-9ca6-11e8-8ecd-31e319a9b833.PNG)

**Comment by spirogg** [comment]
@harrison05 any word on this ?

**Comment by harrison05** [comment]
Hi @spirogg 

Admin can log in as a user from AdminCP and we don't have a plan to move this feature to frontend.

Regards.

**Comment by spirogg** [comment]
Well that's kind of BS. You excepted it and now said no. Oh well that fine
