### ISSUE TITLE
Landing Page Improvement

### ISSUE THREAD

**Issue by vanucci** [PHPfox-Official/phpfox-v4-feature-requests#702]
The landing page is in need of better customisation options without having to modify core files directly. 

The ability to add a main image and it be resized its self and have it as a seperate entity to the  background image would be a better option.  The text area also needs to be improved maybe the ability to edit with bbcode. 
https://i.gyazo.com/d7b94753743c854fe3ac039ade45d471.jpg

**Comment by harrison05** [comment]
We improved for landing page in v4.7.1, for more detail:
https://www.phpfox.com/blog/2018/make-your-creative-home-page-with-custom-blocks/
