### ISSUE TITLE
Grid View in Feed when upload multiple photos ?

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-feature-requests#707]
- hi is it possible to make grid view in Feed like we have in photos app

![capture](https://user-images.githubusercontent.com/17736688/44330511-d0005880-a42c-11e8-8733-07e0d36b878f.JPG)
- this would be nice feature for Feed 

thanks Spiro

**Comment by harrison05** [comment]
Hi, new feed currently show photos as grid view

![screen shot 2018-08-22 at 14 11 47](https://user-images.githubusercontent.com/41947198/44448411-5c6d6f80-a615-11e8-9c30-b2c824581c3d.png)

Regards.
