### ISSUE TITLE
be able to delete posts from apps in feed  example from pages groups no option: see photos

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-feature-requests#709]
there are some posts that a user can not delete from feed,
there is no option from groups pages etc on main site feed. see photo, i update my cover photo and profile photo on my groups. but in feed it show but no option to delete from feed this post like when we add a photo or video or post something we have the option to delete it. we should be able to allow or disallow users and staff to delete from feed
- cover photo updated shows in feed but no delete option
![be able to delete anything that is posted to feeds](https://user-images.githubusercontent.com/17736688/44333082-69326d80-a433-11e8-9547-35f9a696a7c2.JPG)
- profile photo updated but no delete from feed option
![capture](https://user-images.githubusercontent.com/17736688/44333131-8e26e080-a433-11e8-802a-3cac3fa28e30.JPG)

im sure this is for blogs etc, please check what apps would need this feature to give usergroup YES NO option to delete from feed

thanks

**Comment by harrison05** [comment]
I just checked on 4.6.1b5, if you are an Admin or owner of that feed, you can remove it. Take a look on my screenshot 
![screen shot 2018-08-27 at 15 05 17](https://user-images.githubusercontent.com/41947198/44648310-d4b7a480-aa0a-11e8-968d-ff9d6d87d5d9.png)

**Comment by spirogg** [comment]
its from groups and pages, if you update cover photo its not delete
I am a user - on your demo site and created a group, I updated my group cover photo and seems I do not have that option to delete it from Feed

![no delete in feed from group](https://user-images.githubusercontent.com/17736688/44649080-85408c80-a9a8-11e8-850c-7c54319be73b.JPG)

**Comment by spirogg** [comment]
@harrison05 is your demo site (v4.phpfox.com) not allow a user (me) to delete from feed a cover photo or profile pic that I update in my groups or my pages and then when it shows up in feeds ?

 if you have that option turned off i have to test on my site as user to see if it works 

thanks

**Comment by harrison05** [comment]
@spirogg Okay, I see that. 

> if you have that option turned off i have to test on my site as user to see if it works

No, we don't have any option to control this case. We will review your request and inform you later. 

Regards.

**Comment by harrison05** [comment]
Implemented, please check in the newest version of Pages/Groups
