### ISSUE TITLE
can you create for all blocks the cache option or at least the featured members block please

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-feature-requests#710]
Hi,
i saw how you configured the sponsored and featured blocks to cache or set to 0 for no cache.

this would be **Best Feature** if you can make all blocks the same.
Also if admin creates a block, it will automatically  have this option to set cache time or set to 0 for no cache

please this should follow all blocks to have same features when edit settings to that block
- Because I change profile pic and in: members browse>> the featured members block not change,
 you need to clear cache to see update of profile pic

PS. I have set this option to YES and still featured members block still not update until clear cache

Profile Photo Cache Prevention
 - Enable this option to force a users own profile photo from being cached. This will always assure the user will see the latest profile photo they uploaded. YES
Spiro
![capture](https://user-images.githubusercontent.com/17736688/44443766-0a8a0280-a59f-11e8-936b-759c3e27b2d9.JPG)
Spiro

**Comment by harrison05** [comment]
@spirogg We will implement cache option for block Feature members

**Comment by david-phpFox** [comment]
Support in Core 4.7.0
