### ISSUE TITLE
feature request if different languages available for better ads and sponsor ads

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-feature-requests#721]
If we have different languages, is there a way to select to advertise by language. ? 
Somehow. ?? 

So if I have English and Spanish 
I want to advertise or sponsor ads to only Spanish people. We need option for this. 
Somehow it detect Spanish language and serves someone's Spanish ads only when they select that language. In better ads and sponsor ads. ??

**Comment by spirogg** [comment]
This way they don't waste clicks and money to English language people. 

- They can select what language they want. 
- Or even add country too
 and
- state if in USA. 

So I live in Chicago. 
I want to advertise but only to Chicago users.
 Or Greece country users 
or just by language since spanish people live in all different countries.  ?

This would be the most awesome feature to  make more money and have better results for users in better ads. Will make users better clicks and more relevant to what they are looking for and continue to advertise on our websites so we can continue to make money. 

Thank you. 

Spiro

**Comment by spirogg** [comment]
@paulkellow @harrison05 @Vivian-phpFox @phpfoxaccount 

> **For better ads and sponsor ads**

- **We should be able to advertise by languages, genders, user groups, countries, States, Cities, by zipcode(s)**

- this would make so much more sense to people who want to **reach a certain clientele**

 

- I live in chicago - I would want to advertise to **greek people who speak greek**, so **greek language** and also who live in **Illinois and Chicago and by zipcode**

- also to **gender male female** or if they are **other gender that I have created**

**this would be nice to have all these features in Better ADS we can Call it "Excellent ADS" then, instead of Better Ads :)**

**Comment by david-phpFox** [comment]
We implemented it in the newest version.
