### ISSUE TITLE
Points Tracing

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-feature-requests#724]
Points are the most underdeveloped and most needed app in the phpfox arsenal. Been saying this for years. It would be very useful if there is a feature to trace user points or bring attention to  the admin when points are anomalies such as suddenly racked up by certain users and how they are acquiring those points.

This is important to see if people are cheating or not in a points based economy.

**Comment by harrison05** [comment]
Currently, we don't support system auto tracking hack on activity point. But, we will release the Activity Point app soon (on early October of this year) and we allow admin to track history point of users manually with it.

Regards.
