### ISSUE TITLE
When Create pages and groups, please only allow sub category drop down to show if we have created sub categories

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-feature-requests#729]
Dear friends,

When Create pages and groups, please only allow **sub category drop down** **to show if we have created sub categories**

**if there is no sub categories we don't show the drop down**

see photos

- **no sub categories in photo** so we:  HIDE - DONT SHOW DROP DOWN

![capture](https://user-images.githubusercontent.com/17736688/45534380-7d625400-b7c0-11e8-8f86-ef516b2641f2.JPG)

- **here we have categories** so WE SHOW DROPDOWN with sub categories
![capture](https://user-images.githubusercontent.com/17736688/45534462-ce724800-b7c0-11e8-96e4-e4dbbc0155cc.JPG)

**Comment by harrison05** [comment]
We implemented it in the newest version of Pages/Groups. Please check
