### ISSUE TITLE
Available for new friend requests?  privacy setting

### ISSUE THREAD

**Issue by Gatsby-PF** [PHPfox-Official/phpfox-v4-feature-requests#74]
Provide a new user setting (i.e. privacy settings):

Available for new friend requests?  Yes / No 

that if selected to yes, will cause the system to display the message

"Sorry, this user is not accepting new friends at this time"

when someone goes to friend them. 

This would be useful in closed groups/cliques who are not interested in interaction with outsiders, and save them from having to sleight someone by not acknowledging or rejecting their friend request.  By doing it upfront, it de-personlizes the decline (not linked to a particular person, but everyone in general).

**Comment by Data66PF** [comment]
I think you mean that if it is set to No that it would display the message. Or, perhaps if they are not accepting friend requests that the add as friend buttons would just hide.

**Comment by Gatsby-PF** [comment]
I think you are exactly right.

**Comment by Gatsby-PF** [comment]
In a button hide, could they still be sneaky and use a url though?

**Comment by Ylmzef** [comment]
+1

**Comment by Data66PF** [comment]
I believe the friend request is a popup so I am not sure how they would go direct url method.
