### ISSUE TITLE
Sub-men and profile menu sortering

### ISSUE THREAD

**Issue by Ylmzef** [PHPfox-Official/phpfox-v4-feature-requests#741]
Allowing to sub-menu and profile menu sortering in AdminCP will be nice for site regularity.

**Comment by harrison05** [comment]
Could you give us more information about your request?

Thanks.

**Comment by Ylmzef** [comment]
Allow to ordering other menus in AdminCP like as users profile menu, pages menu, groups menu, users dropdown menu(top right side)

![2018-11-11 1 _li](https://user-images.githubusercontent.com/8562514/48313271-23142280-e5ba-11e8-9d5e-a134170076f3.jpg)
![2018-11-11 2 _li](https://user-images.githubusercontent.com/8562514/48313272-23142280-e5ba-11e8-9827-123db5705c04.jpg)
![2018-11-11 3 _li](https://user-images.githubusercontent.com/8562514/48313273-23142280-e5ba-11e8-871c-c58315bf99e2.jpg)
![2018-11-11_li](https://user-images.githubusercontent.com/8562514/48313274-23142280-e5ba-11e8-83a8-0668eb7fbcd8.jpg)
