### ISSUE TITLE
Enable/Disable Activity Points in MarketPlace

### ISSUE THREAD

**Issue by pdensy** [PHPfox-Official/phpfox-v4-feature-requests#746]
Hello,

When adding a new product in the Marketplace, **could we have a button within the form to Enable payment using Activity Points**? Then, if the button is OFF; members will only have to pay with PayPal option (see screenshot) - and the Enable/Disable option could also be on the User Group Settings for Marketplace for Admin to give access per group user.

![activity_points-n-marketplace](https://user-images.githubusercontent.com/44970110/48355079-36c69400-e661-11e8-9432-a4b2f427cb3b.png)

Let's say I am just a regular member and want to sell products to make profits, I would not want to get paid with activity points unless Admin will reimburse me that money for every item sold. Not everyone adding products in the MarketPlace would want to get paid with Activity Points.

Looking forward for feedbacks!

Best,
Densy

**Comment by pdensy** [comment]
We need this option quickly on the script.
Admin may be able to accept both Activity points and PayPal, but not all members would want to get paid by Points unless Admin will reimburse them; that's why I think that option will be helpful for the community. Please take it in consideration or bring something that will stop members from using Activity Points on the Marketplace.

**Comment by david-phpFox** [comment]
Hi pdensy, 

Thank for your suggestions, we will check and support in the next version of Marketplace.

Regards,
David

**Comment by david-phpFox** [comment]
Supported in Marketplace 4.6.3

**Comment by pdensy** [comment]
Thanks for the integration!
I really appreciate the fact that you took my suggestion in consideration. I needed that feature so bad.
