### ISSUE TITLE
Make material home text work like bootstrap. It is currently terrible.

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-feature-requests#754]
Currently, if you add any text it darkens the entire photo image on the material theme. This look really uninviting and the thought that comes to mind is some is off (wrong). Please make it work like the boot strap where if you add text, it will only darken the text area. or make it optional.

this look really dreary and very uninviting
![mat](https://user-images.githubusercontent.com/19594886/50378080-94061b80-05f7-11e9-8794-57d817b5c8d2.png)

This looks better
![boot](https://user-images.githubusercontent.com/19594886/50378092-c3b52380-05f7-11e9-8f62-871f4a49e057.png)

**Comment by david-phpFox** [comment]
Improved in Core 4.7.6
