### ISSUE TITLE
CKeditor package switch for various membership groups

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-feature-requests#768]
It would be very useful to automatically switch the ckeditor package for different membership groups. For example, regular users are presented with a standard package, while the phpfox site admin is presented with the full package. Additionally and option to create customize packages would be very helpful to be able to disable/enable features for each group (i.e. enable flash (or whatever)  for admin and staff, but not regular users, etc...).

I can currently do this manually, but to have this automated would be much more productive and convenient as a site admin managing content.

**Comment by lethality** [comment]
God I'd love this! I hate CKEditor anyway, I think it's ugly, needs updating to version 5, if not entirely switched out for a newer, cleaner, more resource friendly wysiwyg editor. But as an admin, I want the full range of editing options when writing pages like TOS/Privacy, I don't want front-end users to see the full package though, with it's 3/4 lines of badly styled icons

**Comment by spirogg** [comment]
@harrison05 any update on this?

was waiting for long a time as well as other phpfox clients - can you give us ETA and Maybe update to latest version as well..
will this be soon this year or next year ? in version 5 of phpfox ?

Spiro



HOPEFULLY WE CAN GET SOME BUILDS LIKE IN VERSION 5 

then as @prepperz request we can select which one of the usergroups get to use what package.

thanks

BELLOW IS A PHOTO 

![Capture](https://user-images.githubusercontent.com/17736688/99023787-f12c5280-252a-11eb-850b-55e6d823c73a.PNG)

**Comment by harrison05** [comment]
Hi 

@prepperz 
From version 4.2.5 of CKEditor, you can switch packages for various user groups.

@spirogg We will support CKEditor 5 in the next version.

Regards.
