### ISSUE TITLE
monetizing ads for mobile app 

### ISSUE THREAD

**Issue by YouOnline** [PHPfox-Official/phpfox-v4-feature-requests#769]
i want insert  monetizing ads on mobile app your mobile app with ads, google ads, adroll.com

**Comment by harrison05** [comment]
Yes, we're working on it to support Google Ad and Better ads. 
Please wait for new the version.

Thanks.

**Comment by david-phpFox** [comment]
We have supported Google AdMob in Mobile 1.3.
