### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by djafrika** [PHPfox-Official/phpfox-v4-feature-requests#776]
Make so that when you click on /events, the upcoming events are displayed. And add menu for "past" events...
It's a bit silly to have events that are finished on main page...

**Comment by harrison05** [comment]
You can change **Default time to sort events** setting become **Upcoming** to hide past events.

**Comment by djafrika** [comment]
That solves the displaying events, but it still says **All events** on main page... It should be **Upcoming**. It's misleading...

**Comment by harrison05** [comment]
Yes, users still can filter by All Events, we don't prevent that. 
Please understand this is the business rule of Event App.

Regards.
