### ISSUE TITLE
Hi please create tye music playlist to be like video player 

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-feature-requests#784]
Dear friends,

The new video app is a delight with picture in picture mode. I would suggest when users create a playlist, the music player has the same option as video player so they can browse the site while listening to thier music playlists or someone else's music playlist. Right now if I listen to my music playlist and click to go to feed or photos or any part of the site the music stops...

unless I open a different window and have 2 windows open, one for player and a new window to browse the site. Which defeats the purpose. Easier way is to make it like. Video player.  Should be a popout of player so we can browse and listen to music at the same time :)

PS. Should work with all browsers and mobile phones like android and iPhones  too (popout - picture in picture for music player )

This feature is really needed for music player 

Thanks,

Spiro

**Comment by prepperz** [comment]
Did you see this? https://github.com/PHPfox-Official/phpfox-v4-feature-requests/issues/779

**Comment by spirogg** [comment]
Double #779
