### ISSUE TITLE
Hide status messages / Posts from other Members

### ISSUE THREAD

**Issue by ArnoSchiemann** [PHPfox-Official/phpfox-v4-feature-requests#787]
I would like to suggest a change / supplement to you:

Currently, all status messages - new friendships, new pictures in profile, and more - are displayed in the feed. A user can not delete or hide these status messages in the feed.

Similarly, a user can not hide posts from other members in his feed.

As a result, the feed on many members is full of status messages and messages that a member does not want to see at all, and status messages are displayed page by page.

Here, in the profile settings area, there should be a way for a member to be able to set whether he wants to see status messages in the feed or not. This can be done so that a member can specify in his settings "hide all status messages in feed" - on / off.

An administrator can delete posts and messages from other members. So there is already a basic routine.

It should be set up so that members can hide posts from other members in their own feed, either as a single post or as a whole "hide all posts by this member". Each member should therefore have the option to make settings in posts and status messages: "hide status message"
"Hide all status messages"
"Hide post"
"Hide all posts by member xyz".

We would like to see this change for the next new version of PhpFox.

Best regards

Arno Schiemann

**Comment by harrison05** [comment]
We will review your request. 
P/s: Currently, you can try Advanced Feed app, it might usefully.
