### ISSUE TITLE
announcements in app

### ISSUE THREAD

**Issue by cyristvirus** [PHPfox-Official/phpfox-v4-feature-requests#800]
Would like to have it so that announcements are added to the app until a user closes it like the desktop users can.

**Comment by harrison05** [comment]
Do you want to add Announcement App into Mobile App?

Regards.

**Comment by cyristvirus** [comment]
It needs a place to display the announcements in the main feed of mobile so that people get the message. Not just a menu item.

**Comment by harrison05** [comment]
It sounds interesting. Our team will check your request and inform you if have any update.
