### ISSUE TITLE
Интеграция с Rocket.Chat

### ISSUE THREAD

**Issue by loid345** [PHPfox-Official/phpfox-v4-feature-requests#829]
I propose to integrate with rocket.chat. Rocket.Chat is the most advanced free chat, which will replace the standard php fox chat. Integration with Rocket. Chat already has phpfox competitors: https://ci.una.io/docs/group__RocketChat.html

**Comment by harrison05** [comment]
Our team is working on it, a new rocket chat for phpFox will be released in the future. Please wait.

Regards.

**Comment by prepperz** [comment]
Any rough ETA on this?

**Comment by cyristvirus** [comment]
Any eta on this?

**Comment by loid345** [comment]
Does this integration already exist or not?

**Comment by Elshara** [comment]
I doubt it.

**Comment by cyristvirus** [comment]
Wating on ETA

**Comment by Twiub** [comment]
They promised before the end of year 2019 few days to. They names it "chat plus"

**Comment by cyristvirus** [comment]
I am still waiting as well. Just submitted a ticket for this. This is a big feature for me...

**Comment by harrison05** [comment]
Hi, you can pre-order ChatPlus from now. For more information, please follow this link: https://www.phpfox.com/chatplus/

Regards.

**Comment by cyristvirus** [comment]
Can we beat test this?

**Comment by harrison05** [comment]
You can test it at demo site: https://solutions-demo.phpfox.com/

Regards.

**Comment by cyristvirus** [comment]
How do you use the chat, it doesn't appear in the desktop version.

Thanks,

*Lee Adams*
Founder
*Embleholics*
*Veteran Owned & Operated*
*O*: 888.657.2511
*M*: 208.841.9785
*E*: lee@embleholics.com

**Comment by spirogg** [comment]
@cyristvirus you might want to remove your email phone from this post

**Comment by spirogg** [comment]
@cyristvirus you must of responded from your email and your signature is showing in the post here. For your safety please login and edit your post in GitHub.

**Comment by cyristvirus** [comment]
It looks like in the demo site its not possible to activate the chat, unless I am missing something.

**Comment by loid345** [comment]
> Hi, you can pre-order ChatPlus from now. For more information, please follow this link: https://www.phpfox.com/chatplus/
> 
> Regards.

Great. Waiting for the integration with elasticsearch:) 
https://github.com/bellodox/phpfox-elasticsearch

**Comment by harrison05** [comment]
> It looks like in the demo site its not possible to activate the chat, unless I am missing something.

It's at the right corner bottom of the demo site
![Screen Shot 2020-05-15 at 09 26 53](https://user-images.githubusercontent.com/41947198/82018934-7a63e900-96b0-11ea-8fb8-52f5e37f6522.png)

**Comment by cyristvirus** [comment]
I do not see this on chrome 
![image](https://user-images.githubusercontent.com/48768620/82102682-21528000-96c5-11ea-905c-997810e42b76.png)

**Comment by harrison05** [comment]
Hi @cyristvirus 

It had an issue on the demo site and our team fixed it. You can use ChatPlus now.

Regards.

**Comment by cyristvirus** [comment]
It is still not fixed. No way to see the chat icon or interact with it. 
![image](https://user-images.githubusercontent.com/48768620/82241402-f3518380-98f0-11ea-8703-9f90659129db.png)
