### ISSUE TITLE
PWA

### ISSUE THREAD

**Issue by AmineBAIK1** [PHPfox-Official/phpfox-v4-feature-requests#846]
When do we will have a PWA (Progressive Web App ) for phpfox ?

**Comment by cyberhmong** [comment]
Yeah we need it bad. The responsive mobile web browsing is just so slow and killing the entire user experience atm.
There seem to be no way to speed it up regardless of optimisation or display feed limit. Even at low display limits it is just a tiny bit bit better. We do need a better mobile on web browsing solution.

**Comment by AmineBAIK1** [comment]
Yes, Totally agree.

**Comment by harrison05** [comment]
We don't have plan to implement PWA, but we're planning to upgrade phpFox using Reactjs and it will start in the next few months. Btw, we have native Mobile App, for more information, please visit https://www.phpfox.com/features/mobile-readiness/phpfox-native-mobile-app/

Regards.
