### ISSUE TITLE
Add the Conversionrate of Activitypoints to the Frontend

### ISSUE THREAD

**Issue by Bjoern3003** [PHPfox-Official/phpfox-v4-feature-requests#853]
I can not find, where Users can have to see, what the value of 1 Point is.

A small Mockup Example:
https://prnt.sc/oe34nq

**Comment by spirogg** [comment]
@Bjoern3003 
sorry here it is, you have to create at least 1 pkg
-
![Capture1](https://user-images.githubusercontent.com/17736688/61169826-33a0e200-a527-11e9-9f76-196c1497fe52.PNG)


![Capture](https://user-images.githubusercontent.com/17736688/61169827-33a0e200-a527-11e9-9f86-235c521242cd.PNG)

**Comment by spirogg** [comment]
you create each pkg so you can make it whatever you want and user when go buy pkg will see how much each point worth

**Comment by spirogg** [comment]
i can make price of each point more in pkg i sell so it should no calculate the way you say see photos

- 
![Capture2](https://user-images.githubusercontent.com/17736688/61169934-3fd96f00-a528-11e9-903f-b15de2112c61.PNG)

- above i have 1 point .50 cents and the other option is 5 points .10 cents 

example, if users buys 5 points he gets discount
if user only buy 1 point no discount and he pay more .50 cents 

just example

![Capture1](https://user-images.githubusercontent.com/17736688/61169962-86c76480-a528-11e9-90a4-09422e838fb6.PNG)

**Comment by Bjoern3003** [comment]
Sure, you can see it, by buying Packages. But where should Users see this, if they are not buying points, and only earn it for activity?

**Comment by spirogg** [comment]
@Bjoern3003 @harrison05 
 I don't think this is possible, because there is multiple values to points if you have packages setup, how we can have a value with prices that are different ? 
unless there is a way to make this show for users 
(only if we set 1 value for each point - all packages ? meaning everything you buy is 1.00 only no other option for pkgs) 

not for sure just my thought

**Comment by Bjoern3003** [comment]
Hi, there is a fixed value, configured in backend: activitypoint.activity_points_conversion_rate

I think, this is the value, you have to calculate with the total of points.

**Comment by harrison05** [comment]
Implemented in Activity Point v4.7.8. 
The conversion rate is shown on "Point Transactions" page.

Regards.
