### ISSUE TITLE
Integrate Facebook kit

### ISSUE THREAD

**Issue by Twiub** [PHPfox-Official/phpfox-v4-feature-requests#854]
Facebook account kit is very import in phone number verification. It is free to verify phone numbers unlike twilio nexmo etc 

https://developers.facebook.com/docs/accountkit/faq/#faq_184327531988271

**Comment by spirogg** [comment]
Is there a charge for using SMS with Account Kit?
To make it easy for developers using Account Kit, we will not institute any SMS charges through August 2018. At that point, standard SMS rates may apply for apps exceeding 100,000 SMS confirmation messages per month. For FbStart apps, our program for early-stage mobile startups, we will not institute any Account Kit SMS charges indefinitely. Learn how to apply by going to the FbStart application page.

**Comment by Twiub** [comment]
You can opt not to use sms and use whatsapp verification which is free.

**Comment by Twiub** [comment]
![Uploading Screenshot_20190812-133634.jpg…]()
See the attachment. You can verify phone number for free using whatsapp. This is better than twilio
