### ISSUE TITLE
Blurred photos 

### ISSUE THREAD

**Issue by Twiub** [PHPfox-Official/phpfox-v4-feature-requests#855]
I have realized photos appear blurred or of low quality when scrolling the feeds on mobile apps. You have to click and open it to see it original quality. I suggest make it load the whole quality or make it a setting for admin to choose.

**Comment by harrison05** [comment]
Could you show us an example? On Mobile app, we use image thumbnail on listing screen to make it load faster than the original image.

Regards.

**Comment by Twiub** [comment]
New app version solved it. Thank you
