### ISSUE TITLE
Menus fileld Active/Inactive option

### ISSUE THREAD

**Issue by DonnaScriptTechs** [PHPfox-Official/phpfox-v4-feature-requests#86]
_From @SalmanKhan86 on March 15, 2016 10:6_

how can i Enable/ Disable Menus options.i have to go to database tables for status change to Active/Inactive. in Menus Toggle option need here,check PFA the same
![enable disable](https://cloud.githubusercontent.com/assets/13433124/13774182/9f704d26-eac3-11e5-9bd6-c1cc25369ec2.png)

_Copied from original issue: moxi9/phpfox#1207_

**Comment by GreenMan123** [comment]
Can you please this option to the 4.3. 1

**Comment by Data66PF** [comment]
No we are not adding features yet. We will be looking for adding things after 4.4.

**Comment by GreenMan123** [comment]
Then how can I disable the Market menu

**Comment by PhpFoxJohnJr** [comment]
we should be back group setting on menus as well.  That was a very nice feature.
