### ISSUE TITLE
Notification not linking to posts, but peoples profiles.

### ISSUE THREAD

**Issue by cyristvirus** [PHPfox-Official/phpfox-v4-feature-requests#873]
The notifications are linking to people's profiles and not the feed timeline, so if I comment on a post and get a notification when I click the notification I'm directed to the profile of the poster and not the post itself. Does that make sense? If the poster has a private profile, I can't find the post at all.

**Comment by harrison05** [comment]
It might be an issue, our team will check it.

Regards.

**Comment by david-phpFox** [comment]
Fixed in Core 4.7.8.
