### ISSUE TITLE
LANGUAGE SELECTION IN APPS

### ISSUE THREAD

**Issue by Twiub** [PHPfox-Official/phpfox-v4-feature-requests#878]
Bring language selection on login/registration page. It hard for user to navigate all the way to setting without understanding the current language.

**Comment by harrison05** [comment]
Hi @Twiub 

We improved language selection on mobile app:

- When we open the app, mobile will get the device locale and send to the server to get the language pharse for guest (need enable "Auto-detect language for guest?" setting)
- When user login, we continue to normal flow, get user language

Regards.
