### ISSUE TITLE
Events app: view on Google change link to new feature view on map to stay on same website 

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-feature-requests#891]
Hi, 
Can we change the view on Google link in the event app and change it to The new feature View on Map. So we don't leave the site we are on. 

When you click: View on Google it opens a new page and takes you away from the website. 
If we can change the link to: View on Map, users will stay on the website and won't have to be taken away from our site, Plus it  will look more uniform.

**Comment by spirogg** [comment]
This is the link that says: 
- view on Google Map

![Screenshot_20190925-155540](https://user-images.githubusercontent.com/17736688/65639898-b70e9300-dfae-11e9-8096-4e0a8f30a750.png)

- If we change to: view on map
 it will be so more uniformed and keep users on the website not take you away to Google maps, 

![Screenshot_20190925-155451~2](https://user-images.githubusercontent.com/17736688/65640506-220c9980-dfb0-11e9-8eb4-c5f6d6db8a54.png)

**Comment by harrison05** [comment]
Hi @spirogg , 

Currently, **View on Map** page doesn't support get direction from your current location to event's location but **Google Maps** has. So we redirect to Google Maps (user can view the event on map without redirect by click on **Show Map** link).

Regards.

**Comment by spirogg** [comment]
@harrison05 
no worries i get it now thanks for your time in reply

regards,

Spiro
