### ISSUE TITLE
photo

### ISSUE THREAD

**Issue by vadhol** [PHPfox-Official/phpfox-v4-feature-requests#896]
It’s possible to make something like the one on vk.com, it’s possible in a slightly different way, but the main theme is that the photo should be displayed in full view, it does not need to be scrolled!
example...
https://clip2net.com/s/43RVgjW
https://clip2net.com/s/43RVdwk
https://clip2net.com/s/43RW2ml
       and this is from our site
https://clip2net.com/s/43RW4NO

**Comment by harrison05** [comment]
Hi @vadhol 
Photo app hasn't supported this feature yet. But you can find some 3rd Apps in our store https://store.phpfox.com/. They supported it.

Btw, we will review this feature request.
Regards.
