### ISSUE TITLE
Polls in groups

### ISSUE THREAD

**Issue by cyristvirus** [PHPfox-Official/phpfox-v4-feature-requests#898]
It would be great to allow for polls to be added to group specific topics. Add it in as blogs and other items are.

**Comment by harrison05** [comment]
Hi @cyristvirus 

Could you explain more about your request? 

Regards.

**Comment by cyristvirus** [comment]
The poll feature just needs to be added to groups.

**Comment by harrison05** [comment]
Ok, I got this. 
We will improve: Support add Polls in Groups/Pages. 

Regards.

**Comment by david-phpFox** [comment]
Improved in Polls 4.7.1.
