### ISSUE TITLE
Req Translation tools

### ISSUE THREAD

**Issue by Unite2Me** [PHPfox-Official/phpfox-v4-feature-requests#902]
How i had already ask more Times in ticket, i need this feature back in v4...

https://github.com/PHPfox-Official/phpfox-v4-feature-requests/issues/823

Thanks, i hope someone of staff will reply now.

**Comment by harrison05** [comment]
Hi @Unite2Me 

I understand your request. But I'm afraid this is not possible, our new translate system doesn't separate phrases by apps, it will help admins saving time to translate the duplicate phrases in many apps.

Regards.
