### ISSUE TITLE
create a setting to change category names for multiple languages, when you switch language,  category will translate and will change to that launguage

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-feature-requests#905]
Dear friends,

I know when we add a new language we have to manually edit the categories in the apps to a different language.
 The issue is ;
- We can only change to one language, since the categories are not phrases we can't translate. 

- but I see some code you have in developers docs that seems it would be nice if you can create this for all our apps categories / sub categories. 

please see below from your dev docs
https://docs.phpfox.com/display/FOX4DEVDOC/phpFox+Template+Utilities
------------------------------------

Multiple Languages Field (field_language)
Requires: phpFox version 4.6.0 or higher.

phpFox Template

`{field_language phrase='name' label='name' field='name' format='val[name_' size=30 maxlength=100}`

Generated HTML

```
<div class="form-group">
    <label for="name_en">Name in English (US)</label>
    <input id="name_en" class="form-control" type="text" name="val[name_en]" value="" size="30" maxlength="100">
    <p class="help-block"></p>
    <div class="clearfix collapse-placeholder open">
        <a role="button" data-cmd="core.toggle_placeholder">Name in other languages</a>
        <div class="inner">
            <p class="help-block">If the category is empty then its value will have the same value as default language.</p>
            <div class="form-group">
                <label for="name_es"><strong>Español (ES)</strong>:</label>
                <input class="form-control" type="text" id="name_es" name="val[name_es]" value="" size="30" maxlength="100">
            </div>
        </div>
    </div>
</div>
```

Results

![image](https://user-images.githubusercontent.com/17736688/67830790-05c9b400-faaa-11e9-8aa3-744e4dbff4d0.png)

if in admincp under apps > in each app that has categories,  you can create something like this, it would be so awesome!

-  If I have English default language and then I also have spanish, I can translate the categories in spanish for each app.
- when users change language to spanish on my site, the categories get translated to spanish based on the admins translation in this block that would be for each category.

- This box would appear in each app > under categories/ create categories> it would show up after you have created a category or where we have the default categories, then we can add the translation for the other language(s) and click save. 

- this would be super awesome and would complete your translation issues, for multiple languages for admin created categories / sub categories in all apps.

![image](https://user-images.githubusercontent.com/17736688/67830790-05c9b400-faaa-11e9-8aa3-744e4dbff4d0.png)

Thanks, hope this is possible, based on your example in your developers docs :)

Regareds,
Spiro G

**Comment by spirogg** [comment]
If you can create this, please make this available (compatible) for mobile apps IOS and Android also :)

**Comment by chena321** [comment]
yes.  its very important.  can you include this in 4.8?

**Comment by davchy** [comment]
Actually, it was quite surprised that the essential thing is not implemented long ago.

**Comment by harrison05** [comment]
Hi @spirogg 

Our phpFox Apps (Blogs, Events, Music...) were supported Categories with multiple languages via "Multiple Languages Field". So, what is your request mean?

Regards.

**Comment by chena321** [comment]
@harrison05  pages & groups too?

**Comment by spirogg** [comment]
> Hi @spirogg
> 
> Our phpFox Apps (Blogs, Events, Music...) were supported Categories with multiple languages via "Multiple Languages Field". So, what is your request mean?
> 
> Regards.

Sorry everyone, 
@harrison05 I totally forgot this section has the little link and goes into a drop down sorry... 
you are correct my friend.. 

i will close this already a feature we have :)


![phpfox](https://user-images.githubusercontent.com/17736688/71376049-e02ac980-2585-11ea-8547-5cb885bf0c90.PNG)
