### ISSUE TITLE
Nicer Mentions Display in Comments

### ISSUE THREAD

**Issue by Bjoern3003** [PHPfox-Official/phpfox-v4-feature-requests#913]
I think, it would be a nice feature, if the Mentions in the textarea (after select a user/group or something else) are looking like facebook and not bbcode. Here you can see an example: https://www.jqueryscript.net/form/Facebook-like-mention-Autocomplete-Plugin-With-jQuery-mentiony.html

Maybe the Username / Groupname can added in front of with the profile picture.

**Comment by jwpwhite** [comment]
Agreed, the current solution is not a great visual experience for users. Your proposal would make it look a lot better.

**Comment by spirogg** [comment]
@harrison05 we need good visuals can you implement this for us ? 

- unless you guys have a surprise for us coming soon in 2021 phpfox V5 ? :)

**Comment by spirogg** [comment]
@harrison05 any updates on this I want to go live with my site, but little things like this make it look not so professional please you guys this should if been implemented before we did it for the app versions ?

**Comment by harrison05** [comment]
This feature was implemented from version 4.1.7 of Comments app.

Regards.
