### ISSUE TITLE
New Plugin Hook in PF.Base/module/user/include/service/verify/process.class.php

### ISSUE THREAD

**Issue by Bjoern3003** [PHPfox-Official/phpfox-v4-feature-requests#989]
Hi there,

can you please add a new Hook in PF.Base/module/user/include/service/verify/process.class.php on Line 84

Before:
// check if they should be logged out immediately after changing it. Only then should their status_id be changed

`(($sPlugin = Phpfox_Plugin::get('user.component_service_verify_process_changeemail_after_update')) ? eval($sPlugin) : false);`

**Comment by harrison05** [comment]
Hi @Bjoern3003 

We added new hook: user.component_service_verify_process_change_email_end in that file from phpFox v4.8.6

Regards
