### ISSUE TITLE
Bring more options out of the profile menu 

### ISSUE THREAD

**Issue by Lukey199223** [PHPfox-Official/phpfox-v4-feature-requests#99]
Hello :) 

I think it would be good, if Admins could bring more options out of the profile menu 

for example 

profile,info, friends ....(more) where you see photo's, pages etc

but it'd be cool if the admin could bring more of pages out off the (more list) , to fill the menu a bit more :)

**Comment by Data66PF** [comment]
Please see our posting guidelines and please give us more info based on the guidelines as I'm not clear what you are asking for.

**Comment by Lukey199223** [comment]
Sorry, What I meant was

where you've got the profile menu (profile, info,friends etc) , then after about 3 options you've got the dots (for more) ... where you can see photo's, pages etc, what I want, is to be able to bring more options out of the dots and be able to put them on the profile menu, so there are less options inside the dots (more) and more options visible on your profile when you click to go to your profile :) , Hope I've made that a bit more clear haha

**Comment by Data66PF** [comment]
Ok so you want a setting in AdminCP >> Settings >> Profile (for example) for admins to choose which 4 menus show on the profile page. Perhaps one to set how many menus show too. however, with responsive design, it needs to be limited. 

Is that what you had in mind?

**Comment by Lukey199223** [comment]
Ah ye that's it aha, that's what I was trying to explain :) , ah right, that's why sites havent got all the menu's on show haha, ye if we had the option to show say like for example 6 out of 10 of the menu's , that'd be awesome :) I Just think it'll look better for the design i've gone for on my site :)

**Comment by Lukey199223** [comment]
thank you Donna :)
